### ISSUE TITLE
Disconnect handling

### ISSUE THREAD

**Issue by kleunen** [redboltz/mqtt_cpp#125]
Hello redboltz, 

i have another (minor) issue. The MQTT Client has two disconnect functions: disconnect and force_disconnect. Disconnect performs a clean shutdown, force_disconnect just closes the client socket. I have a connect procedure running (the asio socket attempts to connect to my server), i connect to the wrong port and the firewall drops any connection packets, so the connect does not fail but stays lingering. I have a signal handler, which handles the user pressing Ctrl+C. I now which to cancel the connect. 

If I do disconnect, it does not work, because the socket is not connected yet. I should use force_disconnect in this case. However, the connected() method in the client is protected, so I would have to track the connected state myself .. which is inconvenient. 

Is it possible to make the connected() method public ? Or have some kind of close functions, which itself handles closing the connection cleanly or uncleanly based on connection state ?

**Comment by redboltz** [comment]
I changed `connected()` accessibility from protected to public. In addition added a small fix that `connected()` returns true only if socket level connected and MQTT level connected.
Could you check #131 ?
