### ISSUE TITLE
Test broker subscription handling

### ISSUE THREAD

**Issue by kleunen** [redboltz/mqtt_cpp#128]
Hello redboltz, 

I had a look at the test broker code in the mqtt library, and I noticed it does not have wildcard handling. I was thinking about how this can be handled efficiently and I came up with an approach to handle the subscriptions efficiently. It uses an std::unordered_map now, but a std::map or boost::flat_map can be used as well as internal data structure. Please have a look at the following code, maybe you can use it in the test broker ? 

```C++
#include <iostream>
#include <string>

#include <unordered_map>
#include <boost/tokenizer.hpp>
#include <boost/functional/hash.hpp>
#include <boost/function.hpp>

template<typename Value>
class SubscriptionMap
{
    typedef size_t NodeId;
    typedef std::pair< NodeId, std::string> PathEntryKey;
    
    enum { RootNodeId = 0 };

    struct PathEntry;
    
    typedef std::unordered_map< PathEntryKey, PathEntry, boost::hash< PathEntryKey > > MapType;
    //typedef std::map< PathEntryKey, PathEntry > MapType;
    typedef typename MapType::iterator MapTypeIterator;
    typedef typename MapType::const_iterator MapTypeConstIterator;
    
    struct PathEntry
    {
        NodeId id;
        
        bool has_hash_child : 1;
        bool has_plus_child : 1;
        uint32_t count : 30;
        
        std::vector<Value> values;
        
        PathEntry(NodeId _id)
            : id(_id), has_hash_child(false), has_plus_child(false), count(1)
        { }
    };
    
    
    MapType map;
    MapTypeIterator root;
    NodeId next_node_id;
    
public:
    SubscriptionMap()
        : next_node_id(RootNodeId)
    {  
        // Create the root node
        root = map.insert({ PathEntryKey(std::numeric_limits<NodeId>::max(), ""), PathEntry(RootNodeId) }).first;
        ++next_node_id;
    }
    
    // Insert a value at the specified subscription path
    void insert(std::string const &topic, Value const &value)
    {
        boost::char_separator<char> sep("/");
        boost::tokenizer< boost::char_separator<char> > tokens(topic, sep);
            
        MapTypeIterator parent = root;
        for (auto const  &t : tokens) {
            NodeId parent_id = parent->second.id;
            MapTypeIterator entry = map.find(PathEntryKey(parent_id, t));
            
            if(entry == map.end())  { 
                entry = map.insert({ PathEntryKey(parent_id, t), PathEntry(next_node_id++) }).first;
                if(t == "+")
                    parent->second.has_plus_child = true;
                if(t == "#")
                    parent->second.has_hash_child = true;
            } else {
                entry->second.count++;
            }
               
            parent = entry;
        }     
        
        parent->second.values.push_back(value);
    }
    
    // Remove a value at the specified subscription path
    bool remove(std::string const &topic, Value const &value)
    {
        boost::char_separator<char> sep("/");
        boost::tokenizer< boost::char_separator<char> > tokens(topic, sep);
            
        MapTypeIterator parent = root;
        NodeId parent_id = parent->second.id;
            
        for (auto const  &t : tokens) {
            MapTypeIterator entry = map.find(PathEntryKey(parent_id, t));
            
            if(entry == map.end())
                return false;
                
            --entry->second.count;
            parent_id = entry->second.id;
            
            if(entry->second.count == 0) {
                if(parent != map.end())
                {
                    if(t == "+")
                        parent->second.has_plus_child = false;
                    if(t == "#")
                        parent->second.has_hash_child = false;
                }
                
                map.erase(entry);
                parent = map.end();
            } else {
                parent = entry;
            }
        }     
        
        if(parent != map.end()) {
            typename std::vector<Value>::iterator i = std::find(parent->second.values.begin(), parent->second.values.end(), value);
            if(i == parent->second.values.end())
                return false;
            parent->second.values.erase(i);
        }
    }
    
    // Find all values that math the specified path 
    void find(std::string const &topic, boost::function< void (Value const &) > const &callback) const 
    {
        boost::char_separator<char> sep("/");
        boost::tokenizer< boost::char_separator<char> > tokens(topic, sep);
        
        std::deque<MapTypeConstIterator> entries;
        entries.push_back(root);
        
        std::deque<typename MapType::const_iterator> new_entries;
            
        for (auto const  &t : tokens) {
            new_entries.resize(0);
            
            for(auto const &entry: entries) {
                NodeId parent = entry->second.id; 
                MapTypeConstIterator i = map.find(PathEntryKey(parent, t));
                if(i != map.end())
                    new_entries.push_back(i);
                
                if(entry->second.has_plus_child)
                {
                    i = map.find(PathEntryKey(parent, "+"));
                    if(i != map.end())
                        new_entries.push_back(i);
                }
                
                if(entry->second.has_hash_child)
                {
                    i = map.find(PathEntryKey(parent, "#"));
                    if(i != map.end())
                    {
                        for(auto const &j: i->second.values)
                            callback(j);
                    }
                }
            }
            
            if(new_entries.empty())
                return;
            entries = new_entries;
        }
     
        for(auto const &entry: entries) {
            for(auto const &i: entry->second.values)
                callback(i);
        }
    }
    
    // Return the number of elements in the tree
    size_t size() const { return map.size(); }
};

int main(int, char**)
{
    std::string text = "example/test/A";

    SubscriptionMap<std::string> map;
    map.insert("example/test/A", "example/test/A: Subscriber 1");
    map.insert("example/test/A", "example/test/A: Subscriber 2");
    map.insert("example/test/B", "example/test/B");
    map.insert("example/+/A", "example/+/A: Plus");
    map.insert("example/#", "example/#");
    
    std::cout << "Test with hash, plus and full path" << std::endl;
    map.find("example/test/A", [](std::string const &a) { 
        std::cout << a << std::endl;
    }); 
    
    map.remove("example/+/A", "example/+/A: Plus");
    
    std::cout << "Test with hash, full path" << std::endl;
    map.find("example/test/A", [](std::string const &a) { 
        std::cout << a << std::endl;
    }); 
    
    map.remove("example/#", "example/#");
    
    std::cout << "Test with full path only" << std::endl;
    map.find("example/test/A", [](std::string const &a) { 
        std::cout << a << std::endl;
    });
    
    map.remove("example/test/A", "example/test/A: Subscriber 1");
    map.remove("example/test/A", "example/test/A: Subscriber 2");
    map.remove("example/test/B", "example/test/B");
    
    std::cout << "No entries exist anymore" << std::endl;
    map.find("example/test/A", [](std::string const &a) { 
        std::cout << a << std::endl;
    });
    
    std::cout << "Remaining size should be 1 (root element only)" << std::endl;
    std::cout << "Remaining size: " << map.size() << std::endl;
}
```

You can compile and run the code also here: [https://ide.geeksforgeeks.org/J2DY3D0gC2](url)

**Comment by jonesmz** [comment]
@kleunen 

Are you still interested in support for this?

I've made many improvements to test_broker.hpp, and would love to include this.

Are you interested in making a pull request?

**Comment by kleunen** [comment]
@jonesmz : You can include this. How do you want me to make a pull request ? Should I make an example out of it, and you integrate it with the test_broker.hpp yourself ?

**Comment by kleunen** [comment]
I am interested in doing this, please give me some time to look at the test code and see how it should be integrated.

**Comment by jonesmz** [comment]
The way I thought about the problem is that the ideal implementation is a trie data structure.

Unfortunately, there is no an existing trie data structure in boost, which would have been perfect to use.

You've implemented something very similar to a trie data structure.

I wonder if it makes sense to define a mostly (but perhaps not completely) generic trie data structure, and then have mqtt_cpp::test_broker use it, instead of baking the test_broker logic directly into the data structure?

Furthermore, it would be really great if we could also support the same concept on the client end as well.

I find myself, on a regular basis, subscribing to topics dynamically based on runtime events, wanting a specific handler function to be called (typically a lambda function), and then unsubscribing from that topic as soon as the lambda is called.

The way I'm handling this now is doing a full string comparison of the topic that i've registered each handler for, in a for-each loop, but that's much less efficient than using a trie. So if we could make the implementation generic enough to fit both the server-side and also the client side, that would be really super.

**Comment by kleunen** [comment]
@jonesmz Indeed the data structure is similar to a trie data structure. Although a trie data structure is more generic and in this approach we use the application specific knowledge that the common parts in the strings are seperated by a forward slash (the paths). And also we need to do wildcard handling when matching the strings, the string comparison is not a straight forward character comparison. 

I looked the test broker, and I guess the subscriptions are commonly used in a map structure, i.e: subscription => value. This can be easily implemented in a generic way using templates. 

However, I guess in many scenarios it is also required to lookup based on the value. In the test code I see a lot of multi-indexed data structures. I guess the best way to use the subscription lookup in the most generic way is allowing the trie/wildcard lookup to be used as another index in a boost multi-indexed datastructure.

**Comment by jonesmz** [comment]
> I guess the best way to use the subscription lookup in the most generic way is allowing the trie/wildcard lookup to be used as another index in a boost multi-indexed datastructure.

That would certainly be extremely generic, and minimally invasive.

Do you consider it doable?

Can I help with implementation in any way?

**Comment by jonesmz** [comment]
@kleunen 

Did you end up having any luck on this front?

**Comment by kleunen** [comment]
@jonesmz 

I updated the code a bit for you. You can now add a subscription only once, the path should be unique, this allows the remove to be used without specifying the value. You could already use a std::function as the value of the SubscriptionMap. This allows you to add a lambda function to be called on a match. Please see the following example:

#include <iostream>
#include <string>

#include <unordered_map>
#include <boost/tokenizer.hpp>
#include <boost/functional/hash.hpp>
#include <boost/function.hpp>

template<typename Value>
class SubscriptionMap
{
    typedef size_t NodeId;
    typedef std::pair< NodeId, std::string> PathEntryKey;
    
    enum { RootNodeId = 0 };

    struct PathEntry;
    
    typedef std::unordered_map< PathEntryKey, PathEntry, boost::hash< PathEntryKey > > MapType;
    //typedef std::map< PathEntryKey, PathEntry > MapType;
    typedef typename MapType::iterator MapTypeIterator;
    typedef typename MapType::const_iterator MapTypeConstIterator;
    
    struct PathEntry
    {
        NodeId id;
        
        bool has_hash_child : 1;
        bool has_plus_child : 1;
        uint32_t count : 30;
        
        Value value;
        
        PathEntry(NodeId _id)
            : id(_id), has_hash_child(false), has_plus_child(false), count(1)
        { }
    };
    
    
    MapType map;
    MapTypeIterator root;
    NodeId next_node_id;
    
public:
    SubscriptionMap()
        : next_node_id(RootNodeId)
    {  
        // Create the root node
        root = map.insert({ PathEntryKey(std::numeric_limits<NodeId>::max(), ""), PathEntry(RootNodeId) }).first;
        ++next_node_id;
    }
    
    // Insert a value at the specified subscription path
    void insert(std::string const &topic, Value const &value)
    {
        boost::char_separator<char> sep("/");
        boost::tokenizer< boost::char_separator<char> > tokens(topic, sep);
            
        MapTypeIterator parent = root;
        for(boost::tokenizer< boost::char_separator<char> >::const_iterator t = tokens.begin(); t != tokens.end(); ++t) {
            NodeId parent_id = parent->second.id;
            MapTypeIterator entry = map.find(PathEntryKey(parent_id, *t));
            
            if(entry == map.end())  { 
                entry = map.insert({ PathEntryKey(parent_id, *t), PathEntry(next_node_id++) }).first;
                if(*t == "+")
                    parent->second.has_plus_child = true;
                if(*t == "#")
                    parent->second.has_hash_child = true;
            } else {
                boost::tokenizer< boost::char_separator<char> >::const_iterator next_t = t;
                ++next_t;
                if(next_t == tokens.end())
                    throw std::runtime_error("Subscription already exists in map: " + topic);
                entry->second.count++;
            }
               
            parent = entry;
        }     
        
        parent->second.value = value;
    }
    
    // Remove a value at the specified subscription path
    bool remove(std::string const &topic)
    {
        boost::char_separator<char> sep("/");
        boost::tokenizer< boost::char_separator<char> > tokens(topic, sep);
            
        MapTypeIterator parent = root;
        NodeId parent_id = parent->second.id;
            
        for (auto const  &t : tokens) {
            MapTypeIterator entry = map.find(PathEntryKey(parent_id, t));
            
            if(entry == map.end())
                return false;
                
            --entry->second.count;
            parent_id = entry->second.id;
            
            if(entry->second.count == 0) {
                if(parent != map.end())
                {
                    if(t == "+")
                        parent->second.has_plus_child = false;
                    if(t == "#")
                        parent->second.has_hash_child = false;
                }
                
                map.erase(entry);
                parent = map.end();
            } else {
                parent = entry;
            }
        }   
    }
    
    // Find all values that math the specified path 
    void find(std::string const &topic, boost::function< void (Value const &) > const &callback) const 
    {
        boost::char_separator<char> sep("/");
        boost::tokenizer< boost::char_separator<char> > tokens(topic, sep);
        
        std::deque<MapTypeConstIterator> entries;
        entries.push_back(root);
        
        std::deque<typename MapType::const_iterator> new_entries;
            
        for (auto const  &t : tokens) {
            new_entries.resize(0);
            
            for(auto const &entry: entries) {
                NodeId parent = entry->second.id; 
                MapTypeConstIterator i = map.find(PathEntryKey(parent, t));
                if(i != map.end())
                    new_entries.push_back(i);
                
                if(entry->second.has_plus_child)
                {
                    i = map.find(PathEntryKey(parent, "+"));
                    if(i != map.end())
                        new_entries.push_back(i);
                }
                
                if(entry->second.has_hash_child)
                {
                    i = map.find(PathEntryKey(parent, "#"));
                    if(i != map.end())
                    {
                        callback(i->second.value);
                    }
                }
            }
            
            if(new_entries.empty())
                return;
            entries = new_entries;
        }
     
        for(auto const &entry: entries) {
            callback(entry->second.value);
        }
    }
    
    // Return the number of elements in the tree
    size_t size() const { return map.size(); }
};

int main(int, char**)
{
    
    std::string text = "example/test/A";

    SubscriptionMap< std::function< void() > > map;
    map.insert("example/test/A", [] { std::cout << "example/test/A: Subscriber 1" << std::endl; } );
    
    try { 
        map.insert("example/test/A", [] { std::cout << "example/test/A: Subscriber 2" << std::endl; } );
    } catch(std::exception &e)
    {
        // Should fail due to duplicate subscription
        std::cout << e.what() << std::endl;
    }
    
    map.insert("example/test/B", [] { std::cout << "example/test/B" << std::endl; } );
    map.insert("example/+/A", [] { std::cout << "example/+/A: Plus" << std::endl; } );
    map.insert("example/#", [] { std::cout << "example/#" << std::endl; } );
    
    std::cout << "Test with hash, plus and full path" << std::endl;
    map.find("example/test/A", [](std::function< void() >  const &a) { 
        a();
    }); 
    
    map.remove("example/+/A");
    
    std::cout << "Test with hash, full path" << std::endl;
    map.find("example/test/A", [](std::function< void() > const &a) { 
        a();
    }); 
    
    map.remove("example/#");
    
    std::cout << "Test with full path only" << std::endl;
    map.find("example/test/A", [](std::function< void() >  const &a) { 
        a();
    });
    
    map.remove("example/test/A");
    map.remove("example/test/A");
    map.remove("example/test/B");
    
    std::cout << "No entries exist anymore" << std::endl;
    map.find("example/test/A", [](std::function< void() >  const &a) { 
        a();
    });
    
    std::cout << "Remaining size should be 1 (root element only)" << std::endl;
    std::cout << "Remaining size: " << map.size() << std::endl;
}

**Comment by jonesmz** [comment]
> You can now add a subscription only once, the path should be unique, this allows the remove to be used without specifying the value. 

Unfortunately, I don't think this would comply with the specification.

On the client side, of course, only one subscription for a given topic string is allowed. But overlapping topic strings can happen.

On the server side, however, multiple clients can subscribe to the same topic, and we would want a single global subscription map, so that each subscribed topic could be mapped to the multitude of clients that are subscribed.

**Comment by kleunen** [comment]
```C++
#include <iostream>
#include <string>

#include <unordered_map>
#include <boost/tokenizer.hpp>
#include <boost/functional/hash.hpp>
#include <boost/function.hpp>

template<typename Value>
class SubscriptionMapBase
{
    typedef size_t NodeId;
    typedef std::pair< NodeId, std::string> PathEntryKey;
    
    enum { RootNodeId = 0 };

    struct PathEntry;
    
    typedef std::unordered_map< PathEntryKey, PathEntry, boost::hash< PathEntryKey > > MapType;
    //typedef std::map< PathEntryKey, PathEntry > MapType;
    typedef typename MapType::iterator MapTypeIterator;
    typedef typename MapType::const_iterator MapTypeConstIterator;
    
    struct PathEntry
    {
        NodeId id;
        
        bool has_hash_child : 1;
        bool has_plus_child : 1;
        uint32_t count : 30;
        
        Value value;
        
        PathEntry(NodeId _id)
            : id(_id), has_hash_child(false), has_plus_child(false), count(1)
        { }
    };
    
    
    MapType map;
    MapTypeIterator root;
    NodeId next_node_id;

protected:    
    MapTypeIterator create_topic(std::string const &topic, bool allow_duplicate = false)
    {
        boost::char_separator<char> sep("/");
        boost::tokenizer< boost::char_separator<char> > tokens(topic, sep);
            
        MapTypeIterator parent = root;
        for(boost::tokenizer< boost::char_separator<char> >::const_iterator t = tokens.begin(); t != tokens.end(); ++t) {
            NodeId parent_id = parent->second.id;
            MapTypeIterator entry = map.find(PathEntryKey(parent_id, *t));
            
            if(entry == map.end())  { 
                entry = map.insert({ PathEntryKey(parent_id, *t), PathEntry(next_node_id++) }).first;
                if(*t == "+")
                    parent->second.has_plus_child = true;
                if(*t == "#")
                    parent->second.has_hash_child = true;
            } else {
                boost::tokenizer< boost::char_separator<char> >::const_iterator next_t = t;
                ++next_t;
                if(next_t == tokens.end() && !allow_duplicate)
                    throw std::runtime_error("Subscription already exists in map: " + topic);
                entry->second.count++;
            }
               
            parent = entry;
        }     
        
        return parent;
    }
    
    // Remove a value at the specified subscription path
    MapTypeIterator remove_topic(std::string const &topic)
    {
        boost::char_separator<char> sep("/");
        boost::tokenizer< boost::char_separator<char> > tokens(topic, sep);
            
        MapTypeIterator parent = root;
        NodeId parent_id = parent->second.id;
            
        for (auto const  &t : tokens) {
            MapTypeIterator entry = map.find(PathEntryKey(parent_id, t));
            
            if(entry == map.end())
                return entry;
                
            --entry->second.count;
            parent_id = entry->second.id;
            
            if(entry->second.count == 0) {
                if(parent != map.end())
                {
                    if(t == "+")
                        parent->second.has_plus_child = false;
                    if(t == "#")
                        parent->second.has_hash_child = false;
                }
                
                map.erase(entry);
                parent = map.end();
            } else {
                parent = entry;
            }
        }   
        
        return parent;
    }
    
    // Find all values that math the specified path 
    void find_topic(std::string const &topic, boost::function< void (Value const &) > const &callback) const 
    {
        boost::char_separator<char> sep("/");
        boost::tokenizer< boost::char_separator<char> > tokens(topic, sep);
        
        std::deque<MapTypeConstIterator> entries;
        entries.push_back(root);
        
        std::deque<typename MapType::const_iterator> new_entries;
            
        for (auto const  &t : tokens) {
            new_entries.resize(0);
            
            for(auto const &entry: entries) {
                NodeId parent = entry->second.id; 
                MapTypeConstIterator i = map.find(PathEntryKey(parent, t));
                if(i != map.end())
                    new_entries.push_back(i);
                
                if(entry->second.has_plus_child)
                {
                    i = map.find(PathEntryKey(parent, "+"));
                    if(i != map.end())
                        new_entries.push_back(i);
                }
                
                if(entry->second.has_hash_child)
                {
                    i = map.find(PathEntryKey(parent, "#"));
                    if(i != map.end())
                    {
                        callback(i->second.value);
                    }
                }
            }
            
            if(new_entries.empty())
                return;
            entries = new_entries;
        }
     
        for(auto const &entry: entries) {
            callback(entry->second.value);
        }
    }
    
    MapTypeIterator end() { return map.end(); }
    
    SubscriptionMapBase()
        : next_node_id(RootNodeId)
    {  
        // Create the root node
        root = map.insert({ PathEntryKey(std::numeric_limits<NodeId>::max(), ""), PathEntry(RootNodeId) }).first;
        ++next_node_id;
    }
    
public:
    // Return the number of elements in the tree
    size_t size() const { return map.size(); }
};

template<typename Value>
class SingleSubscriptionMap
    : public SubscriptionMapBase<Value>
{
    
public:

    SingleSubscriptionMap()
    { }
    
    // Insert a value at the specified subscription path
    void insert(std::string const &topic, Value const &value)
    {
        this->create_topic(topic, false)->second.value = value;
    }
    
    // Remove a value at the specified subscription path
    bool remove(std::string const &topic)
    {
        auto i = this->remove_topic(topic);
    }
    
    // Find all values that math the specified path 
    void find(std::string const &topic, boost::function< void (Value const &) > const &callback) const 
    {
        this->find_topic(topic, callback);
    }
};


template<typename Value>
class MultipleSubscriptionMap
    : public SubscriptionMapBase< std::vector<Value> >
{
    
public:

    MultipleSubscriptionMap()
    { }
    
    // Insert a value at the specified subscription path
    void insert(std::string const &topic, Value const &value)
    {
        this->create_topic(topic, true)->second.value.push_back(value);
    }
    
    // Remove a value at the specified subscription path
    bool remove(std::string const &topic, Value const &value)
    {
        auto i = this->remove_topic(topic);
        if(i != this->end())
            i->second.value.erase(std::find(i->second.value.begin(), i->second.value.end(), value));
    }
    
    // Find all values that math the specified path 
    void find(std::string const &topic, boost::function< void (Value const &) > const &callback) const 
    {
        this->find_topic(topic, [&callback]( std::vector<Value> const &values ) { 
            for(Value const &i: values)
                callback(i);
        });
    }
};

void TestSingleSubscription()
{
    std::string text = "example/test/A";

    SingleSubscriptionMap< std::function< void() > > map;
    map.insert("example/test/A", [] { std::cout << "example/test/A: Subscriber 1" << std::endl; } );
    
    try { 
        map.insert("example/test/A", [] { std::cout << "example/test/A: Subscriber 2" << std::endl; } );
    } catch(std::exception &e)
    {
        // Should fail due to duplicate subscription
        std::cout << e.what() << std::endl;
    }
    
    map.insert("example/test/B", [] { std::cout << "example/test/B" << std::endl; } );
    map.insert("example/+/A", [] { std::cout << "example/+/A: Plus" << std::endl; } );
    map.insert("example/#", [] { std::cout << "example/#" << std::endl; } );
    
    std::cout << "Test with hash, plus and full path" << std::endl;
    map.find("example/test/A", [](std::function< void() >  const &a) { 
        a();
    }); 
    
    map.remove("example/+/A");
    
    std::cout << "Test with hash, full path" << std::endl;
    map.find("example/test/A", [](std::function< void() > const &a) { 
        a();
    }); 
    
    map.remove("example/#");
    
    std::cout << "Test with full path only" << std::endl;
    map.find("example/test/A", [](std::function< void() >  const &a) { 
        a();
    });
    
    map.remove("example/test/A");
    map.remove("example/test/A");
    map.remove("example/test/B");
    
    std::cout << "No entries exist anymore" << std::endl;
    map.find("example/test/A", [](std::function< void() >  const &a) { 
        a();
    });
    
    std::cout << "Remaining size should be 1 (root element only)" << std::endl;
    std::cout << "Remaining size: " << map.size() << std::endl;
}

void TestMultipleSubscription()
{
    std::string text = "example/test/A";

    MultipleSubscriptionMap<std::string> map;
    map.insert("example/test/A", "example/test/A: Subscriber 1");
    map.insert("example/test/A", "example/test/A: Subscriber 2");
    map.insert("example/test/B", "example/test/B");
    map.insert("example/+/A", "example/+/A: Plus");
    map.insert("example/#", "example/#");
    
    std::cout << "Test with hash, plus and full path" << std::endl;
    map.find("example/test/A", [](std::string const &a) { 
        std::cout << a << std::endl;
    }); 
    
    map.remove("example/+/A", "example/+/A: Plus");
    
    std::cout << "Test with hash, full path" << std::endl;
    map.find("example/test/A", [](std::string const &a) { 
        std::cout << a << std::endl;
    }); 
    
    map.remove("example/#", "example/#");
    
    std::cout << "Test with full path only" << std::endl;
    map.find("example/test/A", [](std::string const &a) { 
        std::cout << a << std::endl;
    });
    
    map.remove("example/test/A", "example/test/A: Subscriber 1");
    map.remove("example/test/A", "example/test/A: Subscriber 2");
    map.remove("example/test/B", "example/test/B");
    
    std::cout << "No entries exist anymore" << std::endl;
    map.find("example/test/A", [](std::string const &a) { 
        std::cout << a << std::endl;
    });
    
    std::cout << "Remaining size should be 1 (root element only)" << std::endl;
    std::cout << "Remaining size: " << map.size() << std::endl;
}

int main(int, char**)
{
    TestSingleSubscription();
    TestMultipleSubscription();
}
```

**Comment by kleunen** [comment]
It allows for single and multiple subscribers. Also, i fixed adding a path which already exists in the map, or removing a path which does not exist. Both left the map in an undefined state in earlier version. 

One thing I do not like is that the multiple subscription data structure uses a separate vector, it would be more efficient to store this in a single unordered_multimap.

**Comment by jonesmz** [comment]
Thanks for the improvements!

Do you think you'd be up for making a pull request that adds this to the test-broker?

**Comment by kleunen** [comment]
The test broker uses the multiindex now. This makes sense, because you need not only lookup the connnection based on the topic. When a client disconnects, you want to lookup all subscriptions which are belong to the connection and remove those subscriptions. So I guess a multiindex compatible index is needed, but at the moment I have no idea how to do this.

**Comment by kleunen** [comment]
I created a small server based on the SubscriptionMap, you can find it here: 
https://github.com/kleunen/mqtt_cpp_server

It is tcp only now, and only qos 0 message. Also, no exception handling for errors in the path yet, so, it will crash if you send the wrong both. I compiled it using mingw, i have not been able to build it on linux yet, because it seems you need a very very recent g++ compiler to build mqtt_cpp nowadays.

**Comment by kleunen** [comment]
I also updated the test broker to use the subscription map. For the retained messages, i also have a retained message map, but this still need to be integrated with the test broker. 

I do feel the test broker is a bit over using the multiindex, and this complicates things, because updating the elements in a multiindex is rather cumbersome.

**Comment by jonesmz** [comment]
Updating elements can be a bit cumbersome, yea.

I'm open to suggestions?

**Comment by kleunen** [comment]
Have a look at the pull request first and see if it is something you would consider adding. Should i send the request to a different fork?

From there some cleanups are possible.

**Comment by kleunen** [comment]
The retained messages are only indexed by the topic, so this can be quite easily replaced with my retained_map, giving you a full mqtt with wildcard handling.

**Comment by kleunen** [comment]
One thing I noticed in the test broker is that you make a distinction between active and inactive sessions. I think they are actually the same session. So you have a table or multi-index list of sessions, and a session is active if it has an endpoint and it is inactive when it does not have an endpoint. If the endpoint goes offline, it depends on the 'clean' setting whether you would remove the session from the list of all sessions or not. If you should not clean the session, you keep it, but you remove the endpoint from the session. This way, when you publish to an inactive session, you know you have to cache the messages, everything can be arranged from within the session class.

**Comment by kleunen** [comment]
Also, in my commit, i map the subscription map point from topic -> connection, but actually, it should point from topic -> session. That way, if the session is offline, the published messages can be queued in the session. 

You can use shared pointers to share the pointer between the subscription map (topic -> session) and the multi index for the list of all sessions (which should be indexed based on client_id and the expiration timestamp). 

You now also have a lookup from connection -> session in the mi_active_sessions, but I think it is more convenient to bind a session pointer to the callback functions of an endpoint. That way, when a callback occurs on a connection, you immediatly have the pointer to the relevant session. Before the user has performed the connect however, you do not know the client id. So you create an empty/anonymous session when the user connects, and once the connect is performed, you lookup if a cached session is available. If it is, you can copy the data from the old session (all subscriptions) and discards the old session and add the new session to mi_active_sessions.
