### ISSUE TITLE
Mismatched string_view implementations

### ISSUE THREAD

**Issue by dylanhart** [redboltz/mqtt_cpp#145]
There are mismatched `string_view` implementations between provided beast library (`external/beast` @ tag `v124`) and this library when using `-std=c++14` and Boost versions between 1.61 and 1.64

#### Definition in mqtt_cpp
https://github.com/redboltz/mqtt_cpp/blob/2697dca326a498eddd49147a255f1df5cd8eedb0/include/mqtt/utility.hpp#L39-L54

#### Definition in beast
https://github.com/boostorg/beast/blob/9dc9ca13b9c08c1597d05bcf6c19be357e426041/include/boost/beast/core/string.hpp#L14-L50

I think it would be best to use the definition from beast to maintain compatibility

**Comment by redboltz** [comment]
@dylanhart , thank you for reporting the issue. I just sent the #146 to fix it.
Could you check it ?
