### ISSUE TITLE
MQTTv5 support?

### ISSUE THREAD

**Issue by jonesmz** [redboltz/mqtt_cpp#175]
Simply curious if this is planned in any way.

**Comment by redboltz** [comment]
I'm developing to add MQTT v5 support.
Here is the branch.
https://github.com/redboltz/mqtt_cpp/tree/support_v5

NOTE: 
It's a kind of private working branch, so far. So I sometimes do **force update**  the branch.

**Comment by jonesmz** [comment]
Great! I appreciate the information.
