### ISSUE TITLE
Support multiple handler objects instead of just one per type.

### ISSUE THREAD

**Issue by jonesmz** [redboltz/mqtt_cpp#187]
I find myself wanting to have multiple handlers of various types. For example, I want to have two connack handlers in an mqtt client. I've made a class that inherits from mqtt::client, and internally to the class's implementation it registers a connack handler. Then, the code that creates an instance of my client object wants to register it's own connack handler that triggers some application specific behavior.

Right now, the only way to support this situation is to have my own code accept a connack handler, which is called by the connack handler that i register with mqtt::client / mqtt::endpoint.  That's awkward.

What I'd rather see if that each of the handler types that mqtt::endpoint accept be added to an std::vector (or maybe make the type of collection be a template parameter), and then when the handlers need to be called, each of the handlers that was added to the vector is called in turn.

Of course, the semantics of having a bunch of callbacks that change the behavior of things based on their return value means that we can't have the handler functions just return true or false.

Instead we would need them to return an enum, which would need to have at least the following, or some variation of them.

```
enum class HandlerActions : std::uint8_t
{
    ContinueProcessing, // Call the next handler, if exists, otherwise proceed as normal.
    ContinueProcessingGreedy, // Don't call the next handler, but proceed as normal (The name of this one could be better)
    StopProcessing // Don't call the next handler, stop processing, an error happened
};
```

Another option would be to have the handlers return a bitfield which represents multiple orthogonal values.
```

enum class HandlerOutcome : std::uint8_t
{
    Success = 0b00000001, Fail = 0b00000000;
};

enum class ProcessingInstructions : std::uint8_t
{
    CallNext = 0b00010000, DontCallNext = 0b00000000;
};

```
Which would allow for each concept to have other meanings added if anyone thinks of new ones.

**Comment by jonesmz** [comment]
You can see a work in progress implementation of this here: https://github.com/jonesmz/mqtt_cpp/tree/multiple-handlers-support

**Comment by redboltz** [comment]
Please wait implementing.

When I merged #181, I didn't think deeply what you want to do. 

mqtt_cpp can work with multiple application classes without inheriting.

Here is the concept code:

```cpp
template <typename MqttClient>
class your_app {
    app(MqttClient const& cli):cli_(cli) {
        cli_.set_connack_handler(
            [this]
            (bool session_present, std::uint8_t return_code) {
                // access `this`.
                // you can call multiple handlers that you want to call.
            }
    }
    void connect() {
    }

private:
    MqttClient cli_;
};

auto make_your_app(
    as::io_service& ios,
    std::string host,
    std::uint16_t port) {
    return 
        your_app<decltype(mqtt::make_client(ios, std::move(host), port))> 
        (mqtt::make_client(ios, std::move(host), port));
}
```

I think that it is enough.

**Comment by jonesmz** [comment]
Well, this isn't really about inheriting, it's about providing better support for composing complex operations.

**Comment by redboltz** [comment]
Could you show me some usecase? I cannot image why this feature is useful.
I think that multiple handler support should be added by application side not mqtt_cpp, so far.
Is there any reasons that mqtt_cpp needs to change.

**Comment by redboltz** [comment]
Why I think multiple handers support should be implemented by application side, continue or not continue decision is application specific. 

Here is (little trick) example:

```cpp
        int fail_count = 0;
        cli->set_connack_handler(
            [&]
            (bool session_present, std::uint8_t return_code) {
                for (auto const& h : handlers) {
                    auto ret = h();
                    if (!ret) {
                        if (++fail_count == 3) return false;
                    }
                }
                return true;
            }
        );
```

Other reason is the type of handlers collection. You choose `std::vector`. But application would want to use other container such as `std::map`. User might want to change the handlers calling order dynamically.

So I think that implementing `std::vector` handlers to mqtt_cpp is too much.

**Comment by jonesmz** [comment]
You're right that the user of the library might want to be able to change the order of handlers dynamically, and a whole host of other possibilities.

Typically the way that I handle this situation is by using virtual methods and inheritance, in large part because the compiler can frequently manage to perform devirtualization, and inline the derived classes implementation of the function.

With std::function, we're already incurring some costs because of the type erasure, and std::function having to do some pointer dereferencing. What I want to avoid is needing to have an std::function that exists basically to call a list/vector of other std::functions.

Anyway, to provide an example of why having multiple callbacks could be useful:

I'm using the test_broker.hpp implementation, with some additions, so that the MQTT broker itself can perform actions when certain messages are received. So in addition to the normal handling for published messages going out to clients, my internal handler gets called. Instead of being able to simply add another handler to the list of handlers for "publish" messages, I needed to go into the broker code and add this custom behavior.

Anyway, if you don't want to support this kind of behavior, I understand.

**Comment by redboltz** [comment]
Thank you for understanding. I don't add multiple handler support.

I have some comments that about inheritance model. `mqtt_cpp` doesn't support classic ObjectOritented style design. Destructors are not virtual. After #181 merged, user can create inherited class, but it should be used as concrete class. It shouldn't be accessed via base class `mqtt::client`.

That is my design decision.

As you mentioned, OO style polymorphism might be efficient thank to compiler support. Similarly, `std::function` also could be efficient by optimization.

Here are examples:

https://godbolt.org/z/5DUzVK

https://godbolt.org/z/wBArSn

**Comment by jonesmz** [comment]
Thanks for explaining your position.

I'm going to use mqtt_cpp by using the classic ObjectOriented style design by inheriting from mqtt::client, so I'll be maintaining my own copy of the mqtt_cpp code that I modified to support doing this.

I'll try to send you as many improvements as I can.
