### ISSUE TITLE
topic and contents should be created as string_view

### ISSUE THREAD

**Issue by redboltz** [redboltz/mqtt_cpp#191]
After merged #188, the following line can implement as string_view.

https://github.com/redboltz/mqtt_cpp/blob/master/include/mqtt/endpoint.hpp#L5105
https://github.com/redboltz/mqtt_cpp/blob/master/include/mqtt/endpoint.hpp#L5124
https://github.com/redboltz/mqtt_cpp/blob/master/include/mqtt/endpoint.hpp#L5149
https://github.com/redboltz/mqtt_cpp/blob/master/include/mqtt/endpoint.hpp#L5181

**Comment by redboltz** [comment]
It requires pretty big breaking change. I'm working on this.

NOTE:
The current master is for version 4.x.

**Comment by jonesmz** [comment]
This should be fixed now

**Comment by jonesmz** [comment]
I believe this issue should be closed.
