### ISSUE TITLE
Send multiple messages in a single async_write

### ISSUE THREAD

**Issue by jonesmz** [redboltz/mqtt_cpp#194]
For endpoint.hpp, do_async_write is as written below:

```
    void do_async_write() {
        auto const& elem = queue_.front();
        auto const& mv = elem.message();
        auto const& func = elem.handler();
        auto self = this->shared_from_this();
        if (h_pre_send_) h_pre_send_();
        async_write(
            *socket_,
            const_buffer_sequence(mv),
            write_completion_handler(
                this->shared_from_this(),
                func,
                mqtt::size<PacketIdBytes>(mv)
            )
        );
    }
```

We should be able to write all of the data that's in the queue all at once.

Something like:

```
    void do_async_write() {
        some_type bufferSequence;
        some_type callbacks;
        for(auto const& elem : queue_)
        {
            bufferSequence.push_back(elem.message());
            callbacks.push_back(elem.handler());
        }
        auto self = this->shared_from_this();
        if (h_pre_send_) h_pre_send_();
        async_write(
            *socket_,
            bufferSequence,
            write_completion_handler(
                self,
                [callbacks](void){ for(auto const& func : callbacks) { func(); } },
                mqtt::size<PacketIdBytes>(mv)
            )
        );
    }
```

This will allow the TCP protocol to achieve better framing, since it'll have access to more outgoing data at a time.

**Comment by redboltz** [comment]
I think that it's a great improvement.
But I'd like to confirm the following topics before updating.

1. If queued elements contains the message like ` (head ) small, small, small, huge (tail)`, the timing of first three small messages finish handler calling would be delayed until huge message is written to the communication drivers memory. 

2. If 1 is true, what kinds of side effects would happen. I guess that the advantage is bigger than the disadvantage. But should be confirmed.

3. When boost asio actually starts to send the chunk of message? In the case ` (head ) small, small, small, huge (tail)` and ` (head ) small, small, small (tail)`, the first three messages sending timing is the same ?

I think 1 is true, and just started confirming 2. Do you know anything about 3?

**Comment by jonesmz** [comment]
> 1. If queued elements contains the message like (head ) small, small, small, huge (tail), the timing of first three small messages finish handler calling would be delayed until huge message is written to the communication drivers memory.

I believe this is what would happen.

> If 1 is true, what kinds of side effects would happen. I guess that the advantage is bigger than the disadvantage. But should be confirmed.

I suppose you could put in a limit. E.g. only X messages, and only if none of them are larger than Y.

> When boost asio actually starts to send the chunk of message? In the case (head ) small, small, small, huge (tail) and (head ) small, small, small (tail), the first three messages sending timing is the same ?

If you mean "when does boost asio send the messages to the underlying operating system or device", then I believe that both of the situations you described would be the same.

If you mean "when do the messages enter the network physical layer", then it's entirely up to the operating system / network device, and I don't think we can really influence that.

**Comment by jonesmz** [comment]
cant this be closed now?

**Comment by redboltz** [comment]
Yes. Thank you for your cooperation.
Now, we got the new tuning parameters. The default setting is keeping the original behavior without any observable overhead. Unfortunately, I don't get significant performance improvement with setting the parameter on my testing environment, so far. But users have various environment, I believe the extension is worth to have.
