### ISSUE TITLE
test_broker.hpp, the way pending_ is used causes an infinite loop

### ISSUE THREAD

**Issue by jonesmz** [redboltz/mqtt_cpp#205]
The pending_ variable of test_broker.hpp's Broker class is defined as:

 ```
struct pending {
        pending(
            bool clean_session,
            con_sp_t const& spep,
            std::string const& client_id,
            mqtt::optional<mqtt::will> will)
            : clean_session(clean_session), spep(spep), client_id(client_id), will(std::move(will)) {}
        bool clean_session;
        con_sp_t spep;
        std::string const& client_id;
        mqtt::optional<mqtt::will> will;
    };
    using mi_pending = mi::multi_index_container<
        pending,
        mi::indexed_by<
            mi::sequenced<>
        >
    >;
    mi_pending pending_;
```

And then used in the following two functions:

```
    bool try_connect(
        bool clean_session,
        con_sp_t const& spep,
        std::string const& client_id,
        mqtt::optional<mqtt::will> will) {
        auto it_ret = cons_.emplace(client_id, spep);
        if (!std::get<1>(it_ret)) {
            pending_.emplace_back(clean_session, spep, client_id, std::move(will));
            return false;
        }
        connect_proc(clean_session, spep, client_id, std::move(will));
        return true;
    }
```
and then

```
    template <typename Endpoint>
    void close_proc(Endpoint& con, bool send_will) { 
        // Some code removed here
        auto it = pending_.begin();
        auto end = pending_.end();
        while (it != end) {
            if (try_connect(it->clean_session, it->spep, it->client_id, it->will)) {
                it = pending_.erase(it);
            }
            else {
                ++it;
            }
        }
    }
```

It's unclear to me what this code is supposed to do in the test broker.

Based on reading the code, I think it does this:

1. When a new connection is started, check to see if there is already an existing connection that is associated with the clientID.
2. If the desired clientID is already associated with a connection, put the new connection in the pending_ map.
3. When a connection is closed, check to see if any of the pending connections match the clientID that just disconnected.
4. If any pending connections match, then finish the connection for that connection.

Is this right?

The reason that I ask about this is that I see frequent infinite loops, and infinite growth of memory whenever close_proc() is called when there are items in pending_.

Since mi_pending is not configured to allow only one item per connection or clientid, each call to try_connect will put another copy of the pending connection into the set. As a result, the close_proc function will loop forever.

Possible fix:

Change the multiindex container to allow multiple items to have the same clientID, but require that the connection be unique across the container.

Then in close_proc() instead of iterating through the entire list of pending connections, only iterate through the list of connections that match the clientID of the connection that just exited.

Instead of calling try_connect(), do the appropriate bookkeeping in the close_proc(), and call connect_proc directly.

**Comment by redboltz** [comment]
To be honest, pending_ is from other project. And most part of pending_ related features are removed. So, it is not well considered for the class test_broker.

I will take a look pending_ process. Apparently  `close_proc() -> try_connect() -> pending_.emplace_back()` logic is a bug.
