### ISSUE TITLE
Use boost::any (and std::any when compiling for C++17) instead of std::function<void(void)> for "life_keeper_t"

### ISSUE THREAD

**Issue by jonesmz** [redboltz/mqtt_cpp#218]
`std::function<void(void)>` is used as a type-erasing storage mechanism to support preserving the lifetime of various things until after the end of various asynchronous calls.  `std::function` brings a lot of baggage with it, with regards to the operator() functionality that it provides, though that's obviously not that much extra stuff.

There's boost::any, which offers a slightly reduced surface area for this same concept, without the operator() functionality that std::function brings with it.

c++17 standardized boost::any as std::any, and we can support this using mqtt::any like we do with varient and string_view.

**Comment by redboltz** [comment]
@jonesmz , thank you for the proposal. Think that your approach is very good.

At first, I use `std::shared_ptr<void>` to keep the life of object. But I need to have multiple objects support. Apparently,  `std::shared_ptr<void>, std::shared_ptr<void>, ...` is bad. So I use lambda capture `[obj1, obj2 ...]{}`. I didn't consider well at that time. Simply lambda expression is corresponding to `std::function`.

Could you send the PR to fix it?
