### ISSUE TITLE
endpoint.hpp : Parameters for lifetime extending functions

### ISSUE THREAD

**Issue by jonesmz** [redboltz/mqtt_cpp#224]
For the functions of endpoint.hpp that are known to always require extending the lifetime of the buffers used to send/receive data on the network, we can improve the API for these by exposing that fact to the application using the API.

Right now, these API calls offer 

1) A version that accepts (one or more) boost::asio::const_buffer, and a lifetime_keeper_t object
2) A version that accepts a string (or string_view after #186, #191)

The fundamental operation that endpoint.hpp does is purely based on boost::asio::const_buffer and the "unspecified" lifetime_keeper_t object, but the practical way that this API will be used by most application is by passing strings.

I'd like to see version 2) either replaced, or augmented with a version of the API that takes an mqtt::shared_string_t type (which can be either std::shared_ptr<const std::string> or something else.

This will allow implementations that already work with std::shared_ptr<const std::string> to pass those directly to the API, without needing to allocate and copy a new std::string to the function, or allow the function to allocate-and-copy one directly, without the end user needing to understand how to use boost::asio::buffer.

As an alternative: I'd also think that removing all of the APIs except for the as::const_buffer version would be an improvement, simply because of the reduction in code. It's not *that* complicated to use boost::asio::const_buffer, after all.

**Comment by redboltz** [comment]
I think that this issue is solved by introducing `mqtt::buffer`.
