### ISSUE TITLE
Consider removing some branches

### ISSUE THREAD

**Issue by jonesmz** [redboltz/mqtt_cpp#225]
It appears to be the case (please correct me if I'm mistaken) that there are several branches that are still in git, but have been merged into master.

I think it would help keep things organized if some of these branches were to be removed.

**Comment by redboltz** [comment]
I removed merged branches and some old ones.

One of the reason I push my temporary branch is start CI processes (travis-ci and appveyor).
And I forget removing it.

I create an organization https://github.com/mqtt-cpp ago.

If I transfer repository, I guess I can do the following  things
* I can do above trial CI  process on `redboltz/mqtt_cpp`
* Pull request is managed on `mqtt-cpp/mqtt_cpp`. Branches can be kept clean.

But I need to study **transfer** 's side effect. I don't have much time to do that .

**Comment by jonesmz** [comment]
Looks good so far!
