### ISSUE TITLE
Don't store clientid, username, password, clean_session, or will in endpoint.hpp

### ISSUE THREAD

**Issue by jonesmz** [redboltz/mqtt_cpp#232]
These items are only ever used (by endpoint.hpp, anyway) when sending / receiving the connect message. 

They should be parameters to the connect message functions / callbacks, and not stored in endpoint.hpp. Classes that derive from endpoint.hpp can store them if they want by providing their own handler for the connect message.

Related to that, endpoint.hpp has host_ and port_, which are never used in endpoint.hpp. client.hpp has it's own host_ and port_ variables.

**Comment by redboltz** [comment]
I think that it is a good improvement :)
