### ISSUE TITLE
Unifying life-handlers and callbacks for operations completing.

### ISSUE THREAD

**Issue by jonesmz** [redboltz/mqtt_cpp#247]
Several functions to endpoint.hpp allow for the user to provide an optional mqtt::any to extend the lifetime of buffers, and some functions allow the user to provide an instance of async_handler_t that is called when the operation completes.

In many cases, the async_handler_t is provided as the last argument to the function, and some of the functions where this is allowed are variadic functions, which require some complex handling.

I'd like to propose the following changes:

1) For functions that both need lifetime extension (async functions, some of the publish functions), make `mqtt::any life_keeper` the first argument to the function. This ensures that the caller of the function has no choice but to consider whether they need to preserve the lifetime of whatever is being passed as parameters to the function call, and also makes it slightly easier to manage the internal handling of everything.

This wouldn't be done to functions that take their parameters as std::string, or the like, as the lifetime management of those is already handled properly.

2) Remove the functions that allow variadic number of topics to subscribe / unsubscribe to. Instead, take std::vectors of topics.

If you want to keep these, I propose that they be moved from endpoint.hpp to client.hpp.

3) Change async_handler_t to "completion_handler_t"

4) Add completion handler as an optional parameter to all functions, including the synchronous functions, that don't currently have it.

**Comment by redboltz** [comment]
I think that 3, 4 approach is good. In addition, add `[[deprecated]]` attribute. It is introduced since C++14. We can remove them from client.hpp in future release.

**Comment by redboltz** [comment]
I misunderstood the comment. Please ignore above. I will update later.

**Comment by redboltz** [comment]
> Several functions to endpoint.hpp allow for the user to provide an optional mqtt::any to extend the lifetime of buffers, and some functions allow the user to provide an instance of async_handler_t that is called when the operation completes.
> 
> In many cases, the async_handler_t is provided as the last argument to the function, and some of the functions where this is allowed are variadic functions, which require some complex handling.
> 
> I'd like to propose the following changes:
> 
> 1. For functions that both need lifetime extension (async functions, some of the publish functions), make `mqtt::any life_keeper` the first argument to the function. This ensures that the caller of the function has no choice but to consider whether they need to preserve the lifetime of whatever is being passed as parameters to the function call, and also makes it slightly easier to manage the internal handling of everything.
> 
> This wouldn't be done to functions that take their parameters as std::string, or the like, as the lifetime management of those is already handled properly.
> 
> 2. Remove the functions that allow variadic number of topics to subscribe / unsubscribe to. Instead, take std::vectors of topics.
> 
> If you want to keep these, I propose that they be moved from endpoint.hpp to client.hpp.

I think that 1 and 2 are good. 
I want to keep the original functions. So move to client.hpp is fine.  In addition, add [[deprecated]] attribute. It is introduced since C++14. We can remove them from client.hpp in future release.

> 3. Change async_handler_t to "completion_handler_t"

What does it mean? Just rename?

> 4. Add completion handler as an optional parameter to all functions, including the synchronous functions, that don't currently have it.

Why is it needed? When is synchronous function completion handler called? In synchronous function? If it does, return value is not determind, it is confusing.

**Comment by redboltz** [comment]
> If it does, return value is not determind, it is confusing.

Let me add more description about this.

I think that there are two types of callback function. One is called from the function. For example, `std::sort()`'s comparison function. If is called from `std::sort()` several times. The other is called somewhere **after** the function is returned.
`complietion_handler_t` indicates the latter.

So user might wrote the following logic.

```cpp
container. emplace(
    client.publish(  // returns packet_id
       ...
       [&]  { // completion handler
            container.erase(...); // assume already emplaced
       }
    )
)
````

**Comment by redboltz** [comment]
mqtt_cpp has many updates now. It the issue still required?
