### ISSUE TITLE
Create new classes: properties_view, will_view

### ISSUE THREAD

**Issue by jonesmz** [redboltz/mqtt_cpp#248]
When dealing with wills and mqttv5 properties, currently mqtt_cpp takes the approach of copying the data into either a std::vector of properties, or into the mqtt::will object.

I'd like to instead have mqtt_cpp have two new classes, a properties_view, which provides both an iterator interface, as well as appropriate (but minimal) member functions. The properties_view will internally point to either the raw message received from the network, or some mqtt::properties_collection object which the user of the mqtt_cpp api creates. 

Similarly, the mqtt::will_view object will provide a non-owning view into the notion of an mqtt::will, allowing for data received from the network to be referenced directly instead of copied.

Both mqtt::properties_collection and mqtt::will would have member functions to get the "view" version of themselves. Possibly we can make this an explicit conversion operator. (Or implicit, I suppose).

An example of where this would be useful:

There are multiple places in the broker code, where the std::vector of properties is copied to multiple places. do_publish, for example, always involves a copy of the properties that were received in the message being published to each subscriber.

If this were, instead, some kind of mqtt::properties_collection, the publish function could take 1) A mqtt::properties_view, and 2) The shared_ptr<mqtt::properties_collection>, instead. Saving an allocate and copy on each subscriber.

Retained messages are another example. Each new subscriber gets a full copy of the properties from the message, instead of simply a view to the retained message.

When a will is sent to all subscribers is a third example, not only are the properties copied, but so are the other strings for the message.

**Comment by redboltz** [comment]
I think that MQTT v5 properties can be categorized two types. One is string like type, the other is fixed length type. variable_length could be an exception but I think that it is a kind of fixed one. https://github.com/redboltz/mqtt_cpp/blob/master/include/mqtt/property.hpp#L226

I prepared reference type (view_type) for string like properties. e.g.) https://github.com/redboltz/mqtt_cpp/blob/master/include/mqtt/property.hpp#L152

It can avoid copies. And when `mqtt_cpp` receives packets, ref types are used. So we need to use ref version to match visitor. See https://github.com/redboltz/mqtt_cpp/blob/master/test/pubsub.cpp#L2564

User can set both ref types or non ref types when API such as publish calling. If user choose ref types, then user need to manage its lifetime using like_keeper mechanism.

I think that we already have view (ref) version of properties.
What do you think?

**Comment by jonesmz** [comment]
Looks like the various _ref  versions of the Properties work great.

Could you remind me if there's any code for something like "will_view" or "will_ref" ?

**Comment by jonesmz** [comment]
This need is being satisfied by #320
