### ISSUE TITLE
Release plan of v4 and v5

### ISSUE THREAD

**Issue by redboltz** [redboltz/mqtt_cpp#255]
The current master has many updates and bug fixes.
Now, the master has small breaking changes from v3.1.0.

For example, the following code is a breaking change.
https://github.com/redboltz/mqtt_cpp/compare/v3.1.0..master#diff-3f124c037f502faf47089ae3684fec4bL31

I will release the current master as v4.0.0. At first, I thought that I could release is as v3.2.0 but due to the breaking changes, I noticed that it should be v4.0.0.

Now, mqtt_cpp has plan to refine the core architecture. The plan might have breaking change and add **deprecated** attribute to some APIs. If it does, the refined architecture version will be released as v5.0.0.

**Comment by jonesmz** [comment]
Seems reasonable

**Comment by redboltz** [comment]
I will release v5.0 without #320.
It already has minor API breaking changes and fixed serious bugs.

#320 seems to be very big API change. So I scheduled it as v6.0.
