### ISSUE TITLE
connecting to host with path

### ISSUE THREAD

**Issue by ephlodur2** [redboltz/mqtt_cpp#262]

**Comment by ephlodur2** [comment]
Hello how do I connect to a host using and address in the form "wss://host_ip:port/ws"
for now I notice  mqtt::make_tls_sync_client_ws( m_ioService, "host_ip", soaPort );
the prefix "wss" is added by the lib but I can't add the "/ws"

Thanks for any help

**Comment by redboltz** [comment]
mqtt_cpp doesn't provide URL parse functionality.
So, you need to parse by yourself.

And then, you can pass the arguments as follows:

```cpp
auto client = make_tls_client_ws(ios, "host_ip", port, "/ws");
```

**Comment by ephlodur2** [comment]
Thanks for your reply redboltz  but for now I don't need to parse the URL but it seem if I pass these arguments to like "auto client = make_tls_client_ws(ios, "host_ip", port, "/ws");"
I would be connecting to something like ws://host_ip:port
But I would like to connect to something like ws://host_ip:port/mosquitto/ws
since I'm connecting to a reverse-proxy how to I set " /mosquitto/ws" part
thanks for any comments.

**Comment by redboltz** [comment]
```cpp
auto client = make_client_ws(ios, "host_ip", port, "/mosquitto/ws");
```

**Comment by ephlodur2** [comment]
Great! thanks.
