### ISSUE TITLE
Visual Staudio Compiler Error: fatal error C1060: compiler is out of heap space

### ISSUE THREAD

**Issue by ephlodur2** [redboltz/mqtt_cpp#264]
Hello need help conpiling mqtt_v4.0.0 
the below is what I get when I try to compile V4 using Visual 2017

2>------ Rebuild All started: Project: SOAMQTTClient, Configuration: Debug x64 ------
2>SOAMQTTClient.cpp
2>c:\program files (x86)\microsoft visual studio\2017\community\vc\tools\msvc\14.16.27023\include\numeric(26): warning C4267: '=': conversion from 'size_t' to '_Ty', possible loss of data
2>        with
2>        [
2>            _Ty=unsigned int
2>        ]
2>c:\dev\project\tools\mqtt\v5_message.hpp(131): note: see reference to function template instantiation '_Ty std::accumulate<std::_Vector_const_iterator<std::_Vector_val<std::_Simple_types<boost::variant<mqtt::v5::property::payload_format_indicator,mqtt::v5::property::message_expiry_interval,mqtt::v5::property::content_type,mqtt::v5::property::content_type_ref,mqtt::v5::property::response_topic,mqtt::v5::property::response_topic_ref,mqtt::v5::property::correlation_data,mqtt::v5::property::correlation_data_ref,mqtt::v5::property::subscription_identifier,mqtt::v5::property::session_expiry_interval,mqtt::v5::property::assigned_client_identifier,mqtt::v5::property::assigned_client_identifier_ref,mqtt::v5::property::server_keep_alive,mqtt::v5::property::authentication_method,mqtt::v5::property::authentication_method_ref,mqtt::v5::property::authentication_data,mqtt::v5::property::authentication_data_ref,mqtt::v5::property::request_problem_information,mqtt::v5::property::will_delay_interval,mqtt::v5::property::request_response_information,mqtt::v5::property::response_information,mqtt::v5::property::response_information_ref,mqtt::v5::property::server_reference,mqtt::v5::property::server_reference_ref,mqtt::v5::property::reason_string,mqtt::v5::property::reason_string_ref,mqtt::v5::property::receive_maximum,mqtt::v5::property::topic_alias_maximum,mqtt::v5::property::topic_alias,mqtt::v5::property::maximum_qos,mqtt::v5::property::retain_available,mqtt::v5::property::user_property,mqtt::v5::property::user_property_ref,mqtt::v5::property::maximum_packet_size,mqtt::v5::property::wildcard_subscription_available,mqtt::v5::property::subscription_identifier_available,mqtt::v5::property::shared_subscription_available>>>>,unsigned int,mqtt::v5::connect_message::<lambda_5a44d75aae43f8bbf9fd8d124f6403d4>>(const _InIt,const _InIt,_Ty,_Fn)' being compiled
2>        with
2>        [
2>            _Ty=unsigned int,
2>            _InIt=std::_Vector_const_iterator<std::_Vector_val<std::_Simple_types<mqtt::v5::property_variant>>>,
2>            _Fn=mqtt::v5::connect_message::<lambda_5a44d75aae43f8bbf9fd8d124f6403d4>
2>        ]
2>c:\dev\project\tools\boost_1_69_0\boost\bind\placeholders.hpp(54): note: see reference to class template instantiation 'boost::arg<9>' being compiled
2>c:\dev\project\tools\boost_1_69_0\boost\bind\placeholders.hpp(53): note: see reference to class template instantiation 'boost::arg<8>' being compiled
2>c:\dev\project\tools\boost_1_69_0\boost\bind\placeholders.hpp(52): note: see reference to class template instantiation 'boost::arg<7>' being compiled
2>c:\dev\project\tools\boost_1_69_0\boost\bind\placeholders.hpp(51): note: see reference to class template instantiation 'boost::arg<6>' being compiled
2>c:\dev\project\tools\boost_1_69_0\boost\bind\placeholders.hpp(50): note: see reference to class template instantiation 'boost::arg<5>' being compiled
2>c:\dev\project\tools\boost_1_69_0\boost\bind\placeholders.hpp(49): note: see reference to class template instantiation 'boost::arg<4>' being compiled
2>c:\dev\project\tools\boost_1_69_0\boost\bind\placeholders.hpp(48): note: see reference to class template instantiation 'boost::arg<3>' being compiled
2>c:\dev\project\tools\boost_1_69_0\boost\bind\placeholders.hpp(47): note: see reference to class template instantiation 'boost::arg<2>' being compiled
2>c:\dev\project\tools\boost_1_69_0\boost\bind\placeholders.hpp(46): note: see reference to class template instantiation 'boost::arg<1>' being compiled
2>c:\dev\project\tools\boost_1_69_0\boost\beast\core\string.hpp(61): note: see reference to class template instantiation 'boost::basic_string_view<char,std::char_traits<char>>' being compiled
2>c:\dev\project\tools\boost_1_69_0\boost\asio\use_future.hpp(139): note: see reference to class template instantiation 'boost::asio::use_future_t<std::allocator<void>>::std_allocator_void' being compiled
2>c:\dev\project\tools\boost_1_69_0\boost\asio\use_future.hpp(147): note: see reference to class template instantiation 'boost::asio::use_future_t<std::allocator<void>>' being compiled
2>c:\dev\project\soa_mqtt_client\soamqttclient\src\soamqttclient.cpp(641): fatal error C1060: compiler is out of heap space
2>dllmain.cpp
2>Generating Code...
2>Done building project "MQTTClient.vcxproj" -- FAILED.

Thanks for any help

**Comment by redboltz** [comment]
See https://stackoverflow.com/help/how-to-ask

The error message indicates that you need to install more memory.

**Comment by ephlodur2** [comment]
thanks ! I guess I need to try to see if 32 Gig is sufficient to compile the code in Debug using Visual Studio 2017. for now 16 Gig in not enough.
