### ISSUE TITLE
Support for the Networking TS

### ISSUE THREAD

**Issue by jonesmz** [redboltz/mqtt_cpp#268]
When compiling with Gcc 9, it's possible to use the Networking TS instead of Boost asio to provide asynchronous IO.

Boost::asio and the Networking TS are very similar to each other (Some say, Networking TS is basically a copy-paste of the Boost::asio API).

Mqtt_cpp could provide a compile-time switch to specify which implementation of this API is used.

**Comment by redboltz** [comment]
Does Boost.Beast for Web Sockets work well?

**Comment by jonesmz** [comment]
I believe it is supposed to, yes. But I have not verified that.

**Comment by redboltz** [comment]
In version 5.0.0. we need to consider the minimux Boost.Asio requiremet.
Due to networkTS, recent Boost.Asio updates frequently.

https://www.boost.org/doc/libs/1_70_0/doc/html/boost_asio/history.html

If we support wider version, we need to design adaptor layer carefully.

**Comment by jonesmz** [comment]
Personally I don't think it's worth the trouble to provide an adapter layer.

I believe that mqtt_cpp should either support the pre-Networking TS way of doing things, or the Network TS way, but not both.

It appears to be the case that Boost 1.66 is the version that added support for Networking TS.

Asio 1.12.0 / Boost 1.66
Implemented interface changes to reflect the Networking TS (N4656).

Perhaps the last release of mqtt_cpp 4.0.0 should say that it supports Boost up to version 1.65, but not later, and mqtt_cpp 5.0.0 supports Boost 1.66 or newer.

**Comment by redboltz** [comment]
Now mqtt_cpp minimum boost requirement is 1.67.0
