### ISSUE TITLE
MQTT_16BITNUM_TO_BYTE_SEQ should assert that the value of the size_t fits into uint16_t

### ISSUE THREAD

**Issue by jonesmz** [redboltz/mqtt_cpp#280]
Used in this situation.

```
struct binary_property_ref {
    binary_property_ref(property::id id, string_view sv)
        :id_(id),
         length_{MQTT_16BITNUM_TO_BYTE_SEQ(sv.size())},
         buf_(sv.data(), sv.size()) {
             if (sv.size() > 0xffff) throw property_length_error();
         }
```

The macro should provide some confirmation that the size is compatible.

Then all of the other places where this is manually verified can be removed in favor of the check provided by the macro.

One way to handle this is to have a generic "safe_cast<T>" function that automatically does the appropriate size checks based on the template parameter.

Then the use of the macro can be re-written as MQTT_16BITNUM_TO_BYTE_SEQ(mqtt::safe_cast<std::uint16_t>(sv.size()))

-------------------------------------------

For what it's worth, I'd also recommend making MQTT_16BITNUM_TO_BYTE_SEQ into a normal function that returns an std::array<std::uint8_t, 2>, but that's not really directly related to this issue.

**Comment by redboltz** [comment]
> For what it's worth, I'd also recommend making MQTT_16BITNUM_TO_BYTE_SEQ into a normal function that returns an std::array<std::uint8_t, 2>, but that's not really directly related to this issue.

It was for the following code:

```cpp
std::string s { 1, 2, 3, MQTT_16BITNUM_TO_BYTE_SEQ(9876), 5, 6, };
```
I needed to the way to get a flatten sequence but C++ container doesn't fit to the purpose.

Now, I grep-ed all MQTT_16BITNUM_TO_BYTE_SEQ. And I noticed that all targets are `boost::container::static_vector<char, 2>`.
I also grep-ed all MQTT_32BITNUM_TO_BYTE_SEQ. And I noticed that all targets are `boost::container::static_vector<char, 4>`.

https://wandbox.org/permlink/o1xzCkImqbKHLdez

```cpp
#include <boost/container/static_vector.hpp>

namespace mqtt {

inline boost::container::static_vector<char, 2> num_to_2bytes(std::uint16_t val) {
    return {
        static_cast<char>(static_cast<std::uint16_t>(val) >> 8),
        static_cast<char>((val) & 0xff)
    };
}

inline boost::container::static_vector<char, 4> num_to_4bytes(std::uint32_t val) {
    return {
        static_cast<char>(static_cast<std::uint32_t>(val) >> 24),          
        static_cast<char>(static_cast<std::uint32_t>(val) >> 16),          
        static_cast<char>(static_cast<std::uint32_t>(val) >>  8),          
        static_cast<char>((val) & 0xff)
    };
}
    
} // namespace mqtt
    
int main() {
    boost::container::static_vector<char, 2> length1(mqtt::num_to_2bytes(1234));
    boost::container::static_vector<char, 4> length2(mqtt::num_to_4bytes(1234));
}
```

So we can replace it as above. 
In this approach, parameter type and static_vector's size work for checking automatically on compile time.

What do you think?

**Comment by jonesmz** [comment]
I like this approach.

I have a question about num_to_2_bytes:

```
        static_cast<char>(static_cast<std::uint16_t>(val) >> 8),
        static_cast<char>((val) & 0xff)
```

Why the static cast to std::uint16_t ?

**Comment by redboltz** [comment]
> Why the static cast to std::uint16_t ?
Ah, cast to the same type. It is meaningless.

So the code should be updated as follows:

https://wandbox.org/permlink/zofTQwV02AtTlGVL

````cpp
#include <boost/container/static_vector.hpp>

namespace mqtt {

inline boost::container::static_vector<char, 2> num_to_2bytes(std::uint16_t val) {
    return {
        static_cast<char>(val >> 8),
        static_cast<char>(val & 0xff)
    };
}

inline boost::container::static_vector<char, 4> num_to_4bytes(std::uint32_t val) {
    return {
        static_cast<char>(val >> 24),          
        static_cast<char>(val >> 16),          
        static_cast<char>(val >>  8),          
        static_cast<char>(val & 0xff)
    };
}
    
} // namespace mqtt
    
int main() {
    boost::container::static_vector<char, 2> length1(mqtt::num_to_2bytes(1234));
    boost::container::static_vector<char, 4> length2(mqtt::num_to_4bytes(1234));
}
````
