### ISSUE TITLE
Want to be able to use operator<< (or similar) with correlation_data_ref and friends.

### ISSUE THREAD

**Issue by jonesmz** [redboltz/mqtt_cpp#281]
I want to be able to use the properties with std::ostream.

An easy way to provide this is to have a template function:

```
template<typename T>
T & operator<<(T& ostr, correlation_data)
{
    ostr << correlation_data.val();
    return ostr;
}
```

**Comment by redboltz** [comment]
Hmm...
My first impression is that is users responsibility. 

But let's think about an implementation.
I intentionally named `val()` for the value getter for generic programming frendly.
However, there is one exception. It is `user_property` (and `user_property_ref`).
That has `key()` and `val()`.
I can't decide output format. 

```
key,val
key:val
"key":val
"key":"val"
```

I think it is depends on users.

**Comment by jonesmz** [comment]
I think that providing some default value is better than nothing.

E.g.

```
template<typename Stream, typename Property>
inline 
std::enable_if<std::is_same_v<Property, user_property>, Stream&> 
operatpr<<(Stream& s, Property&& p) {
    s << std::forward<Property>(p).key() << ": " << std::forward<Property>(p).val();
    return s;
}
```

Would be perfectly adequate.

If a user of mqtt_cpp wanted something more robust, they can write their own code, like you said.

My intention with this issue was to improve mqtt_cpp enough that it was immediately usable for 90% of the situations. Perfect formatting isn't always important, but being able to easily get some data out of the data structure is.


Another improvement to consider is 

```
template<typename Stream, typename Property>
inline Stream operator<<(Stream& s, property_varient&& p) {
    // Determine which type of property this is, and print out the property name, and the value (or the key and value)
    return s;
}
```
