### ISSUE TITLE
lifetime of _ref properties and stored messages

### ISSUE THREAD

**Issue by jonesmz** [redboltz/mqtt_cpp#301]
Take this code, for example:

```
    void send_pubrel(
        packet_id_t packet_id,
        mqtt::optional<std::uint8_t> reason = mqtt::nullopt,
        std::vector<v5::property_variant> props = {}
    ) {

        auto impl =
            [&](auto&& msg, auto const& serialize) {
                {
                    LockGuard<Mutex> lck (store_mtx_);

                    // insert if not registerd (start from pubrel sending case)
                    packet_id_.insert(packet_id);

                    auto ret = store_.emplace(
                        packet_id,
                        control_packet_type::pubcomp,
                        msg
                    );
                    BOOST_ASSERT(ret.second);
                }

                if (serialize) {
                    serialize(msg);
                }
                do_sync_write(msg);
            };

        switch (version_) {
        case protocol_version::v3_1_1:
            impl(
                v3_1_1::basic_pubrel_message<PacketIdBytes>(packet_id),
                h_serialize_pubrel_
            );
            break;
        case protocol_version::v5:
            impl(
                v5::basic_pubrel_message<PacketIdBytes>(packet_id, reason, std::move(props)),
                h_serialize_v5_pubrel_
            );
            break;
        default:
            BOOST_ASSERT(false);
            break;
        }
    }
```

Imagine passing function a mqtt::v5::property_variant that has a _ref property type. 

When the function exits, the data that the _ref property type points to may no longer exist.

Two ways to solve this:

1) Always convert _ref properties into their real type before storing them for later access.
2) Any place where a _ref property may be involved can have an optional lifetime keeper parameter provided that preserves the lifetime of the property's data.

I prefer 2, but 1 is much easier to implement. Though it's entirely possible to support both versions of the concept.

It should be noted that it's perfectly fine for mqtt_cpp to send messages to user provided callbacks that are 100% _ref properties, and not provide any kind of lifetime keeper object. The _ref properties in that situation would be backed by the data received from the network, and user code should always assume that as soon as the current function exits, the data will disappear. That puts the responsibility onto user code to manage the lifetime of property data that it receives.

Specifically, mqtt_cpp shouldn't copy that data into some shared pointer owned object, because mqtt_cpp can't predict what the user's code wants to do with the data. If the user wants to keep the data, they can make their own shared pointer. But if there is no method for the user to provide a handle to that shared pointer when providing mqtt_cpp with their vector of property_variants, then mqtt_cpp MUST create a copy of the provided vector that has non-ref properties, so that the lifetime of the data is known.

This all ties together with: #247 and various other issues that I've opened.

**Comment by redboltz** [comment]
I'm not sure I understand perfectly what you mean.

Storing message are only `publish` and `pubrel`.

`publish` already has `life_keeper`. Similarly, `pubrel` should have `like_keeper`.
https://github.com/redboltz/mqtt_cpp/blob/master/include/mqtt/endpoint.hpp#L9515
I think that it is 2nd approach you mentioned.

For storing, it is good enough.

**Comment by redboltz** [comment]
I implement 2nd approach.
If you think there is still problems, please post a new issue.
