### ISSUE TITLE
Convenience typedef for properties

### ISSUE THREAD

**Issue by jonesmz** [redboltz/mqtt_cpp#302]
I'd like to see a "stor" typedef (or whatever name) for the mqtt:v5::property types, to work with the "recv" type.

Imagine a situation where user code want's to convert from the pointer/reference semantics that the _ref property types have, to the value semantics that the non _ref property types have.

Right now, doing so with a property_variant vector requires a visitor that knows about every property type.

If there were a "stor" typedef, instead the visitor would look like (C++17)

`std::visit([destination](auto& val) { destination.emplace_back(typename decltype(auto)::stor(std::move(val)); }, property_variant);`

**Comment by redboltz** [comment]
Let me clarify the issue.

`stor` is a typedef of value type? The opposite concept of `recv`?

For example:

```cpp
class reason_string;

class reason_string_ref : public detail::string_property_ref {
public:
    using recv = reason_string_ref;
    using store = reason_string; // stor
    reason_string_ref(string_view type)
        : detail::string_property_ref(id::reason_string, type) {}
    reason_string_ref(reason_string const& v);
};

class reason_string : public detail::string_property {
public:
    using recv = reason_string_ref;
    using store = reason_string; // stor
    reason_string(string_view type)
        : detail::string_property(id::reason_string, type) {}
    reason_string(reason_string_ref const& v);
};
```

**Comment by redboltz** [comment]
> I'd like to see a "stor" typedef (or whatever name) f

`recv` is from `receive`. `receive` is a little long for me so I use `recv`. (And I usually confused receive/recieve ;)

`stor` is new term to me. Is `stor` from `store`? I guess so.
If it does, I prefer `store`. It is still short.

**Comment by jonesmz** [comment]
Yes. I meant "stor" == "store".

You understood correctly
