### ISSUE TITLE
server_tls and async ssl, conflicting with sync member functions?

### ISSUE THREAD

**Issue by jonesmz** [redboltz/mqtt_cpp#303]
I've been trying to track down why i'm getting buggy behavior out of my fork of test_broker.h, and i'm wondering if the use of async handshake could conflict with the use of sync functions like publish on the endpoints.

I'm not sure that there is a problem. Honestly, just asking for a second opinion.

```
    void do_accept() {
        if (close_request_) return;
        auto socket = std::make_shared<socket_t>(ios_con_, ctx_);
        acceptor_.value().async_accept(
            socket->lowest_layer(),
            [this, socket]
            (boost::system::error_code const& ec) {
                if (ec) {
                    acceptor_.reset();
                    if (h_error_) h_error_(ec);
                    return;
                }
                auto underlying_finished = std::make_shared<bool>(false);
                auto tim = std::make_shared<as::deadline_timer>(ios_con_);
                tim->expires_from_now(underlying_connect_timeout_);
                tim->async_wait(
                    [socket, tim, underlying_finished]
                    (boost::system::error_code ec) {
                        if (*underlying_finished) return;
                        if (ec) return;
                        boost::system::error_code close_ec;
                        socket->lowest_layer().close(close_ec);
                    }
                );
                socket->async_handshake(
                    as::ssl::stream_base::server,
                    [this, socket, tim, underlying_finished]
                    (boost::system::error_code ec) {
                        *underlying_finished = true;
                        tim->cancel();
                        if (ec) {
                            return;
                        }
                        auto sp = std::make_shared<endpoint_t>(std::move(socket), version_);
                        if (h_accept_) h_accept_(*sp);
                    }
                );
                do_accept();
            }
        );
    }
```

**Comment by redboltz** [comment]
> I've been trying to track down why i'm getting buggy behavior out of my fork of test_broker.h, and i'm wondering if the use of async handshake could conflict with the use of sync functions like publish on the endpoints.

Conflicting sync and async operation is bad on **one socket**. If the socket is different, there is no problem.

Consider `async_handshake()`, it happens always before `sync_publish`. Because if `sync_publish` is invoked by the user, then user received `connack`. `connack`is send **after** `async_handshake` process is finished. If `sync_publish` is invoked by `handle_connack`, that means automatic stored message sending, also `async_handshake` process is finished.

So, there is no problem.

**Comment by jonesmz** [comment]
Ok, thanks for the explaination.
