### ISSUE TITLE
BOOST_MPL_LIMIT_LIST_SIZE need to greator or equal to 40

### ISSUE THREAD

**Issue by wcy168** [redboltz/mqtt_cpp#316]
broke.cpp can't compile successfully using visual studio 2017, 
BOOST_MPL_LIMIT_LIST_SIZE need to greator or equal to 40

**Comment by redboltz** [comment]
`boost::variant` requires `BOOST_MPL_LIMIT_LIST_SIZE`.
If you can use C++17, define `MQTT_STD_VARIANT`. See https://github.com/redboltz/mqtt_cpp/wiki/Config#mqtt_std_variant.

If you define `BOOST_MPL_LIMIT_LIST_SIZE` less than 40, set it to 40.

If you don't define `BOOST_MPL_LIMIT_LIST_SIZE` but got error, then some of boost library define it internally. For example Boost.Optional.

You can avoid it changing include order.

In your transration unit (cpp file), move `#include <mqtt_client_cpp.hpp>` to top of the file.

**Comment by redboltz** [comment]
I noticed that the default value of macro is defied at https://github.com/boostorg/mpl/blob/41d036aea2f716e6b6069fb2efa884c7eb86d5a8/include/boost/mpl/limits/list.hpp#L18

I think that 
https://github.com/redboltz/mqtt_cpp/blob/master/include/mqtt/variant.hpp#L17
should be refined.

I will write a PR.

**Comment by redboltz** [comment]
I sent the #316. It is under CI processing, but you can try it.

**Comment by wcy168** [comment]
thank you, but i cant make it work. I pack my program into rar file and send it to you by attachment. Please help me to see it.




------------------ 原始邮件 ------------------
发件人: "Takatoshi Kondo"<notifications@github.com>;
发送时间: 2019年7月3日(星期三) 晚上8:36
收件人: "redboltz/mqtt_cpp"<mqtt_cpp@noreply.github.com>;
抄送: "Xman"<38368423@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [redboltz/mqtt_cpp] BOOST_MPL_LIMIT_LIST_SIZE need to greator orequal to 40 (#316)




boost::variant requires BOOST_MPL_LIMIT_LIST_SIZE.
 If you can use C++17, define MQTT_STD_VARIANT. See https://github.com/redboltz/mqtt_cpp/wiki/Config#mqtt_std_variant.
 
If you define BOOST_MPL_LIMIT_LIST_SIZE less than 40, set it to 40.
 
If you don't define BOOST_MPL_LIMIT_LIST_SIZE but got error, then some of boost library define it internally. For example Boost.Optional.
 
You can avoid it changing include order.
 
In your transration unit (cpp file), move #include <mqtt_client_cpp.hpp> to top of the file.

**Comment by wcy168** [comment]
it works well, thank you.
 

  

 ------------------ 原始邮件 ------------------
  发件人: "Takatoshi Kondo"<notifications@github.com>;
 发送时间: 2019年7月3日(星期三) 晚上9:02
 收件人: "redboltz/mqtt_cpp"<mqtt_cpp@noreply.github.com>;
 抄送: "Xman"<38368423@qq.com>;"Author"<author@noreply.github.com>;
 主题: Re: [redboltz/mqtt_cpp] BOOST_MPL_LIMIT_LIST_SIZE need to greator orequal to 40 (#316)

 

 
I sent the #316. It is under CI processing, but you can try it.
