### ISSUE TITLE
QOS & Protocol Version

### ISSUE THREAD

**Issue by thoism** [redboltz/mqtt_cpp#326]
Hi,

I noticed that the `qos` is consisted from 3 constants whereas the MQTT `protocol version` is an enum class. Is there a particular reason for this difference? I mean wouldn't it be more type safe to do the same for the `qos`?

```
namespace mqtt {
enum class protocol_version {
    undetermined  = 0,
    v3_1_1        = 4,
    v5            = 5,
};
```
```
namespace mqtt {
namespace qos {
  constexpr std::uint8_t const at_most_once  = 0;
  constexpr std::uint8_t const at_least_once = 1;
  constexpr std::uint8_t const exactly_once  = 2;
} // namespace qos
} // namespace mqtt
```

Thank you

**Comment by redboltz** [comment]
Hmm, I just respect the actual packet value.

See 

MQTT v5 protocol version is 5.
https://docs.oasis-open.org/mqtt/mqtt/v5.0/os/mqtt-v5.0-os.html#_Toc3901037

MQTT v3.1.1 protocol level is 4
http://docs.oasis-open.org/mqtt/mqtt/v3.1.1/errata01/os/mqtt-v3.1.1-errata01-os-complete.html#_Toc385349227

I don't recommend that but if someone want to compare the actual byte value with the protocol_cersion, they can do it as follows:
https://wandbox.org/permlink/QwRCmuVtsSJLedZV

NOTE:
MQTT v3.1 is 3 but mqtt_cpp doesn't support it.

**Comment by thoism** [comment]
Thank you for your reply! I meant why not having something like this:

```
namespace mqtt {
enum class qos {
    at_most_once  =  0,
    at_least_once  = 1,
    exactly_once = 2,
};
```

**Comment by redboltz** [comment]
I think that I've already answered.
In enum class, the actual value is not important. I just use the protocol value.

**Comment by thoism** [comment]
OK man thank you

**Comment by redboltz** [comment]
Ah, now I understand your question. You are NOT asking the value 0, 4, and 5. You are asking namespaced `constexpr std::uint8_t const at_most_once` vs `enum class`.

There is  historical reason.

See 

https://github.com/redboltz/mqtt_cpp/pull/226#discussion_r277205725

https://github.com/redboltz/mqtt_cpp/pull/226#discussion_r277207078

You might clieck `show outdated` button to understand all history.

**Comment by redboltz** [comment]
If I design mqtt_cpp from the scratch, I would use enum class for all such kinds of elements. But I choose `std::uint8_t` at first. And I released it. Then, @jonesmz  pointed out enum class is better choice. I apply it new limited part of the code. I didn't replaced all of such kinds of variables because it could make huge impacts to existing code. That is the reason.

**Comment by jonesmz** [comment]
For what it's worth, I think that the approach you've taken so far, of slowly breaking code, instead of radically changing the API all at once, is acceptable.

I think these values should be enums, personally, but there's no reason to change everything all at once.

**Comment by jonesmz** [comment]
See https://github.com/redboltz/mqtt_cpp/pull/379 for design discussion on moving toward enum class.

**Comment by jonesmz** [comment]
This is resolved

**Comment by thoism** [comment]
> If I design mqtt_cpp from the scratch, I would use enum class for all such kinds of elements. But I choose `std::uint8_t` at first. And I released it. Then, @jonesmz pointed out enum class is better choice. I apply it new limited part of the code. I didn't replaced all of such kinds of variables because it could make huge impacts to existing code. That is the reason.

@redboltz 
This answer fully covered my question. Apologies I did not see you re-answered for so long. Thank you for taking the time and also thank you for this awesome project.
