### ISSUE TITLE
Renaming the library?

### ISSUE THREAD

**Issue by jonesmz** [redboltz/mqtt_cpp#334]
I ran into an interesting problem today.

```
#include <mqtt/async_client.hpp>
namespace mynamespace
{
namespace mqtt
{

class MyClient : public mqtt::async_client<mqtt::tcp_endpoint<as::ssl::stream<as::ip::tcp::socket>, as::io_service::strand>>
{
};

}
}
```

Compile error, no member `tcp_endpoint` in namespace mqtt.

Naming the library, and it's namespace `mqtt` is really generic, and prevents applications from having their own namespace.

Some suggestions:

- Add a parent namespace. E.g. redboltz::mqtt
- Rename the library to something more creative. Such as the Eclipse Paho libraries.
- Provide a #define compatible namespace, so that end users of the library can rename the namespace.

**Comment by redboltz** [comment]
I sent #360. User can define your own MQTT_NS to avoid conflict.

mqtt_cpp's library code uses MQTT_NS.
