### ISSUE TITLE
Using client as a member of a class

### ISSUE THREAD

**Issue by Radagan** [redboltz/mqtt_cpp#342]
Though I have something that works, it seems like I must be going about it in the most difficult way. For instance, I had to define my member client as:

`std::shared_ptr<mqtt::sync_client<mqtt::tcp_endpoint<mqtt::as::ssl::stream<mqtt::as::ip::tcp::socket>, mqtt::as::io_service::strand>>> client;`

Is there an example of using this library in a class?

**Comment by jonesmz** [comment]
I don't follow what the problem is?

If you're using the mqtt::sync_client as a member of a class, you don't need to wrap it in a shared_ptr.

You can just include it as a member of the class directly. It's lifetime will be the lifetime of the object that contains it as a member variable.

**Comment by redboltz** [comment]
You can define type alias as follows:

```cpp
using sync_client_t =
    decltype(
        mqtt::make_sync_client(
            std::declval<boost::asio::io_context&>(),
            std::string(),
            std::string(),
            mqtt::protocol_version()
        )
    );

// use sync_client_t as class member variable

// check code (no required)
static_assert(
    std::is_same<
        sync_client_t,
        std::shared_ptr<
            mqtt::sync_client<
                mqtt::tcp_endpoint<
                    mqtt::as::ip::tcp::socket,
                    mqtt::as::io_service::strand
                >
            >
        >
    >::value,
    ""
);
```

**Comment by Radagan** [comment]
Thank you. What you suggested works much better than what I had. 

Also, I now have mqtt_cpp connecting with Google IoT Core. I really appreciate this library. Thank you for sharing your hard work.
