### ISSUE TITLE
Create an allocate_buffer(std::string) function

### ISSUE THREAD

**Issue by jonesmz** [redboltz/mqtt_cpp#348]
The constructor mqtt::buffer(std::string) is disabled to avoid people using mqtt::buffer thinking that it won't allocate-and-copy.

We should also provide an allocate_buffer() function for std::string, in addition to iterators.

**Comment by redboltz** [comment]
I think that

```cpp
buffer allocate_buffer(string_view)
```

is better.

That can support both string and string_view. And thanks to its name, user can understand it apparently allocates memory.

What do you think?

**Comment by jonesmz** [comment]
I agree with you

**Comment by redboltz** [comment]
I will sent a PR to add it.
I just noticed that allocate_buffer() is in literals (inline) namespace. I will move it outside of literals namespace.

**Comment by redboltz** [comment]
I noticed the comment of allocate_buffer() is bad. I will fix it too.

**Comment by redboltz** [comment]
Implemented as #349
