### ISSUE TITLE
Another new compiler error from #320

### ISSUE THREAD

**Issue by jonesmz** [redboltz/mqtt_cpp#350]
> FAILED: src/cloud-connector/CMakeFiles/cloud-connector.dir/main.cpp.o 
> /usr/bin/g++-8.3.0  -DBOOST_LOG_NO_SHORTHAND_NAMES -DBOOST_LOG_USE_STD_REGEX -DBOOST_LOG_WITHOUT_EVENT_LOG -DBOOST_LOG_WITHOUT_SYSLOG -DBOOST_LOG_WITHOUT_WCHAR_T -DMQTT_STD_ANY -DMQTT_STD_OPTIONAL -DMQTT_STD_STRING_VIEW -DMQTT_STD_VARIANT -I/home/jonesmz/meshpp_frameworks/inc -I/home/jonesmz/meshpp_frameworks/3rdparty/json/single_include -I/home/jonesmz/meshpp_frameworks/3rdparty/mqtt_cpp/include -I3rdparty/libpqxx/include -I/home/jonesmz/meshpp_frameworks/3rdparty/libpqxx/include -Wall -Wextra -fno-omit-frame-pointer  -Wno-psabi -fsanitize=address -fsanitize-address-use-after-scope -fsanitize=pointer-compare -fsanitize=pointer-subtract -fsanitize=leak -fstack-protector-all -fsanitize=bounds -fsanitize=enum -g -ggdb3 -gz -O0   -std=c++17 -MD -MT src/cloud-connector/CMakeFiles/cloud-connector.dir/main.cpp.o -MF src/cloud-connector/CMakeFiles/cloud-connector.dir/main.cpp.o.d -o src/cloud-connector/CMakeFiles/cloud-connector.dir/main.cpp.o -c /home/jonesmz/meshpp_frameworks/src/cloud-connector/main.cpp
> In file included from /usr/include/boost/asio/impl/write.hpp:23,
>                  from /usr/include/boost/asio/write.hpp:618,
>                  from /usr/include/boost/asio/buffered_write_stream.hpp:29,
>                  from /usr/include/boost/asio/buffered_stream.hpp:22,
>                  from /usr/include/boost/asio.hpp:38,
>                  from /home/jonesmz/meshpp_frameworks/3rdparty/mqtt_cpp/include/mqtt/server.hpp:10,
>                  from /home/jonesmz/meshpp_frameworks/src/cloud-connector/broker.hpp:23,
>                  from /home/jonesmz/meshpp_frameworks/src/cloud-connector/main.cpp:4:
> /usr/include/boost/asio/detail/consuming_buffers.hpp: In instantiation of ‘class boost::asio::detail::consuming_buffers<boost::asio::mutable_buffer, boost::asio::mutable_buffer>’:
> /usr/include/boost/asio/impl/read.hpp:213:46:   required from ‘class boost::asio::detail::read_op<boost::asio::ssl::stream<boost::asio::basic_stream_socket<boost::asio::ip::tcp> >, boost::asio::mutable_buffer, boost::asio::detail::transfer_all_t, boost::asio::detail::wrapped_handler<boost::asio::io_service::strand, std::function<void(const boost::system::error_code&, long unsigned int)>, boost::asio::detail::is_continuation_if_running> >’
> /usr/include/boost/asio/impl/read.hpp:558:11:   required from ‘typename boost::asio::async_result<typename boost::asio::handler_type<WriteHandler, void(boost::system::error_code, long unsigned int)>::type>::type boost::asio::async_read(AsyncReadStream&, const MutableBufferSequence&, ReadHandler&&) [with AsyncReadStream = boost::asio::ssl::stream<boost::asio::basic_stream_socket<boost::asio::ip::tcp> >; MutableBufferSequence = boost::asio::mutable_buffer; ReadHandler = boost::asio::detail::wrapped_handler<boost::asio::io_service::strand, std::function<void(const boost::system::error_code&, long unsigned int)>, boost::asio::detail::is_continuation_if_running>; typename boost::asio::async_result<typename boost::asio::handler_type<WriteHandler, void(boost::system::error_code, long unsigned int)>::type>::type = void]’
> /home/jonesmz/meshpp_frameworks/3rdparty/mqtt_cpp/include/mqtt/tcp_endpoint.hpp:68:23:   required from ‘void mqtt::tcp_endpoint<Socket, Strand>::async_read(MutableBufferSequence&&, ReadHandler&&) [with MutableBufferSequence = boost::asio::mutable_buffer; ReadHandler = std::function<void(const boost::system::error_code&, long unsigned int)>; Socket = boost::asio::ssl::stream<boost::asio::basic_stream_socket<boost::asio::ip::tcp> >; Strand = boost::asio::io_service::strand]’
> /home/jonesmz/meshpp_frameworks/3rdparty/mqtt_cpp/include/mqtt/type_erased_socket.hpp:36:1:   required from ‘static void mqtt::has_async_read<void(A ...), T>::apply(T&, A ...) [with T = mqtt::tcp_endpoint<boost::asio::ssl::stream<boost::asio::basic_stream_socket<boost::asio::ip::tcp> >, boost::asio::io_service::strand>; A = {boost::asio::mutable_buffer, std::function<void(const boost::system::error_code&, long unsigned int)>}]’
> /usr/include/boost/type_erasure/detail/instantiate.hpp:91:9:   required from ‘static void boost::type_erasure::detail::instantiate_concept7::apply(Concept*, Map*) [with Concept = boost::mpl::vector<boost::type_erasure::destructible<>, mqtt::has_async_read<void(boost::asio::mutable_buffer, std::function<void(const boost::system::error_code&, long unsigned int)>)>, mqtt::has_async_write<void(std::vector<boost::asio::const_buffer>, std::function<void(const boost::system::error_code&, long unsigned int)>)>, mqtt::has_write<long unsigned int(std::vector<boost::asio::const_buffer>, boost::system::error_code&)>, mqtt::has_post<void(std::function<void()>)>, mqtt::has_lowest_layer<boost::asio::basic_socket<boost::asio::ip::tcp, boost::asio::stream_socket_service<boost::asio::ip::tcp> >&()>, mqtt::has_close<void(boost::system::error_code&)> >; Map = boost::mpl::map1<boost::mpl::pair<boost::type_erasure::_self, mqtt::tcp_endpoint<boost::asio::ssl::stream<boost::asio::basic_stream_socket<boost::asio::ip::tcp> >, boost::asio::io_service::strand> > >]’
> /usr/include/boost/type_erasure/any.hpp:1210:13:   [ skipping 11 instantiation contexts, use -ftemplate-backtrace-limit=0 to disable ]
> /usr/lib/gcc/x86_64-pc-linux-gnu/8.3.0/include/g++-v8/bits/shared_ptr.h:359:59:   required from ‘std::shared_ptr<_Tp>::shared_ptr(std::_Sp_alloc_shared_tag<_Tp>, _Args&& ...) [with _Alloc = std::allocator<mqtt::endpoint<std::mutex, std::lock_guard, 2> >; _Args = {const std::shared_ptr<mqtt::tcp_endpoint<boost::asio::ssl::stream<boost::asio::basic_stream_socket<boost::asio::ip::tcp, boost::asio::stream_socket_service<boost::asio::ip::tcp> > >, boost::asio::io_service::strand> >, mqtt::protocol_version&}; _Tp = mqtt::endpoint<std::mutex, std::lock_guard, 2>]’
> /usr/lib/gcc/x86_64-pc-linux-gnu/8.3.0/include/g++-v8/bits/shared_ptr.h:705:14:   required from ‘std::shared_ptr<_Tp> std::allocate_shared(const _Alloc&, _Args&& ...) [with _Tp = mqtt::endpoint<std::mutex, std::lock_guard, 2>; _Alloc = std::allocator<mqtt::endpoint<std::mutex, std::lock_guard, 2> >; _Args = {const std::shared_ptr<mqtt::tcp_endpoint<boost::asio::ssl::stream<boost::asio::basic_stream_socket<boost::asio::ip::tcp, boost::asio::stream_socket_service<boost::asio::ip::tcp> > >, boost::asio::io_service::strand> >, mqtt::protocol_version&}]’
> /usr/lib/gcc/x86_64-pc-linux-gnu/8.3.0/include/g++-v8/bits/shared_ptr.h:721:39:   required from ‘std::shared_ptr<_Tp> std::make_shared(_Args&& ...) [with _Tp = mqtt::endpoint<std::mutex, std::lock_guard, 2>; _Args = {const std::shared_ptr<mqtt::tcp_endpoint<boost::asio::ssl::stream<boost::asio::basic_stream_socket<boost::asio::ip::tcp, boost::asio::stream_socket_service<boost::asio::ip::tcp> > >, boost::asio::io_service::strand> >, mqtt::protocol_version&}]’
> /home/jonesmz/meshpp_frameworks/3rdparty/mqtt_cpp/include/mqtt/server.hpp:331:63:   required from ‘void mqtt::server_tls<Strand, Mutex, LockGuard, PacketIdBytes>::do_accept() [with Strand = boost::asio::io_service::strand; Mutex = std::mutex; LockGuard = std::lock_guard; long unsigned int PacketIdBytes = 2]’
> /home/jonesmz/meshpp_frameworks/3rdparty/mqtt_cpp/include/mqtt/server.hpp:252:9:   required from ‘void mqtt::server_tls<Strand, Mutex, LockGuard, PacketIdBytes>::listen() [with Strand = boost::asio::io_service::strand; Mutex = std::mutex; LockGuard = std::lock_guard; long unsigned int PacketIdBytes = 2]’
> /home/jonesmz/meshpp_frameworks/src/cloud-connector/main.cpp:1411:32:   required from here
> /usr/include/boost/asio/detail/consuming_buffers.hpp:164:5: error: no type named ‘const_iterator’ in ‘class boost::asio::mutable_buffer’
>      const_iterator;
>      ^~~~~~~~~~~~~~
> /usr/include/boost/asio/detail/consuming_buffers.hpp:261:36: error: no type named ‘const_iterator’ in ‘class boost::asio::mutable_buffer’
>    typename Buffers::const_iterator begin_remainder_;
>                                     ^~~~~~~~~~~~~~~~
> ninja: build stopped: subcommand failed.
> 20:00:45: The process "/usr/bin/cmake" exited with code 1.
> Error while building/deploying project Project (kit: Desktop)
> When executing step "CMake Build"
> 20:00:45: Elapsed time: 00:20.

**Comment by redboltz** [comment]
Could you write a minimal example to reproduce the error?

**Comment by jonesmz** [comment]
I will try, yes.

**Comment by jonesmz** [comment]
I am able to reproduce this error simply by compiling the examples / tests for mqtt_cpp with Boost 1.65

I am now using Boost 1.68 and Boost 1.70, so the error doesn't happen for me anymore, but anyone who tries to use Boost 1.65 will have the problem.

**Comment by redboltz** [comment]
I reproduce the error. I guess that at boost 1.66.0, some issue that is related to this error has been fixed.

I also tried the different version of boost.

I only checked compile not link.

|boost version|result|
|---|---|
|1.65.0|error|
|1.65.1|error|
|1.66.0|success|
|1.67.0|success|
|1.68.0|success|
|1.69.0|success|
|1.70.0|success|

Current README.md said:
> mqtt_cpp is a header only library. It requires C++14 and the Boost Libraries 1.57.0 or later 

I'd like to update supported boost version from `1.57.0` to `1.66.0`.

We might be able to find a workaround to avoid the error but it is not my priority.

**Comment by jonesmz** [comment]
I think simply saying the minimum version of boost is `1.66.0` is fine.

**Comment by redboltz** [comment]
I sent the PR #403 .
