### ISSUE TITLE
error compiling with boost 1.70

### ISSUE THREAD

**Issue by jonesmz** [redboltz/mqtt_cpp#351]
FAILED: src/device-management/CMakeFiles/device-managementd.dir/main.cpp.o 
/usr/bin/g++-8.3.0  -DBOOST_LOG_NO_SHORTHAND_NAMES -DBOOST_LOG_USE_STD_REGEX -DBOOST_LOG_WITHOUT_EVENT_LOG -DBOOST_LOG_WITHOUT_SYSLOG -DBOOST_LOG_WITHOUT_WCHAR_T -DMQTT_STD_ANY -DMQTT_STD_OPTIONAL -DMQTT_STD_STRING_VIEW -DMQTT_STD_VARIANT -I/home/jonesmz/meshpp_frameworks/inc -I/home/jonesmz/meshpp_frameworks/3rdparty/json/single_include -I/home/jonesmz/meshpp_frameworks/3rdparty/mqtt_cpp/include -Wall -Wextra -fno-omit-frame-pointer  -Wno-psabi -fsanitize=address -fsanitize-address-use-after-scope -fsanitize=pointer-compare -fsanitize=pointer-subtract -fsanitize=leak -fstack-protector-all -fsanitize=bounds -fsanitize=enum -g -ggdb3 -gz -O0   -std=c++17 -MD -MT src/device-management/CMakeFiles/device-managementd.dir/main.cpp.o -MF src/device-management/CMakeFiles/device-managementd.dir/main.cpp.o.d -o src/device-management/CMakeFiles/device-managementd.dir/main.cpp.o -c /home/jonesmz/meshpp_frameworks/src/device-management/main.cpp
In file included from /usr/include/boost/fusion/adapted/std_tuple.hpp:21,
                 from /usr/include/boost/process/detail/execute_impl.hpp:37,
                 from /usr/include/boost/process/child.hpp:22,
                 from /usr/include/boost/process/async_system.hpp:22,
                 from /home/jonesmz/meshpp_frameworks/inc/meshpp/asio/async_system.h:8,
                 from /home/jonesmz/meshpp_frameworks/inc/meshpp/asio/async_system_command.h:8,
                 from /home/jonesmz/meshpp_frameworks/inc/meshpp/openwrt/uci_actions.h:10,
                 from /home/jonesmz/meshpp_frameworks/src/device-management/main.cpp:9:
/usr/include/boost/fusion/adapted/std_tuple/tag_of.hpp:35:12: error: redefinition of ‘struct boost::mpl::sequence_tag<std::tuple<_Tps ...> >’
     struct sequence_tag<std::tuple<Elements...>>
            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /usr/include/boost/type_erasure/detail/meta.hpp:29,
                 from /usr/include/boost/type_erasure/detail/get_placeholders.hpp:24,
                 from /usr/include/boost/type_erasure/detail/normalize.hpp:30,
                 from /usr/include/boost/type_erasure/any.hpp:40,
                 from /home/jonesmz/meshpp_frameworks/3rdparty/mqtt_cpp/include/mqtt/shared_any.hpp:12,
                 from /home/jonesmz/meshpp_frameworks/3rdparty/mqtt_cpp/include/mqtt/type_erased_socket.hpp:17,
                 from /home/jonesmz/meshpp_frameworks/3rdparty/mqtt_cpp/include/mqtt/endpoint.hpp:60,
                 from /home/jonesmz/meshpp_frameworks/3rdparty/mqtt_cpp/include/mqtt/client.hpp:31,
                 from /home/jonesmz/meshpp_frameworks/3rdparty/mqtt_cpp/include/mqtt/async_client.hpp:10,
                 from /home/jonesmz/meshpp_frameworks/inc/meshpp/mqtt/client.h:23,
                 from /home/jonesmz/meshpp_frameworks/src/device-management/main.cpp:4:
/usr/include/boost/mp11/mpl.hpp:155:29: note: previous definition of ‘struct boost::mpl::sequence_tag<std::tuple<_Tps ...> >’
 template<class... T> struct sequence_tag<std::tuple<T...>>
                             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

**Comment by Radagan** [comment]
In case it helps track down the issues with 1.70, I'm successfully building with 1.67.

**Comment by jonesmz** [comment]
I'm in kind of a damned-if-you-do, damned-if-you-dont situation.

I have to simultaneously support Ubuntu Bionic, which has Boost 1.65.

OpenWRT is 1.68.

Gentoo (which I use for development) is also 1.65

I've installed 1.70 on Gentoo to try to work around the issues i'm seeing, but that brings new compiler errors :-)

I deploy on Ubuntu, and for now I compile on Ubuntu for deployment, but I can compile on Gentoo and statically link. So as long as we can get 1.68 (OpenWRT) and 1.70 (Gentoo) to be happy, I can stop caring about 1.65 entirely.

I'm

**Comment by jonesmz** [comment]
The problem in this appears to be that I have boost fusion, and boost mpl, pulled into the same translation unit through third party dependencies.

It's not clear to me how to solve this issue...

**Comment by redboltz** [comment]
Unfortunately, I don't have much time so I don't check this issue yet.

But perhaps https://github.com/boostorg/fusion/issues/182 is related.

**Comment by jonesmz** [comment]
I just found https://github.com/boostorg/fusion/issues/182 a moment ago, and yet. It seems exactly the same issue.

**Comment by redboltz** [comment]
I created a new issue on mp11 https://github.com/boostorg/mp11/issues/39

**Comment by jonesmz** [comment]
This is not something that mqtt_cpp can solve, as it's an upstream bug.

I worked around my problem by using the PIMPL idiom, which isn't perfect, but it works well enough.

Closing this issue because we can't fix it.
