### ISSUE TITLE
Need factory function for make_sync_tls_client_ws and others

### ISSUE THREAD

**Issue by jonesmz** [redboltz/mqtt_cpp#354]
The sync_client class is missing factory functions for the tls versions.

The async_client has these factory functions.

**Comment by redboltz** [comment]
It seems that thy exist:

https://github.com/redboltz/mqtt_cpp/blob/master/include/mqtt/sync_client.hpp#L374

**Comment by jonesmz** [comment]
You're right. My mistake. I was spelling it wrong.
