### ISSUE TITLE
API deprecate plan

### ISSUE THREAD

**Issue by redboltz** [redboltz/mqtt_cpp#362]
I'm going to deprecate the following APIs. All of them have alternative and recommended APIs. They are decreasing maintainability.

1. Set deprecated attribute on 6.0.
2. Remove APIs on 7.0

The list of APIs:

|API|recommend|
|---|---|
|publish_at_most_once|publish|
|publish_at_least_once|publish|
|publish_exactly_once|publish|
|subscribe(topic, option, ...)|subscribe(std::vector { {topic, option}, ...} )|
|unsubscribe(topic, ...)|unsubscribe(std::vector { topic,...} )|
|acquired_publish_at_most_once|acquired_publish|
|acquired_publish_at_least_once|acquired_publish|
|acquired_publish_exactly_once|acquired_publish|
|acquired_subscribe(topic, option, ...)|acquired_subscribe(std::vector { {topic, option}, ...} )|
|acquired_unsubscribe(topic, ...)|acquired_unsubscribe(std::vector { topic,...} )|
|async_publish_at_most_once|async_publish|
|async_publish_at_least_once|async_publish|
|async_publish_exactly_once|async_publish|
|async_subscribe(topic, option, ...)|async_subscribe(std::vector { {topic, option}, ...} )|
|async_unsubscribe(topic, ...)|async_unsubscribe(std::vector { topic,...} )|
|acquired_async_publish_at_most_once|acquired_async_publish|
|acquired_async_publish_at_least_once|acquired_async_publish|
|acquired_async_publish_exactly_once|acquired_async_publish|
|acquired_async_subscribe(topic, option, ...)|acquired_async_subscribe(std::vector { {topic, option}, ...} )|
|acquired_async_unsubscribe(topic, ...)|acquired_async_unsubscribe(std::vector { topic,...} )|

Note:

Sync version of `publish_at_most_once` family take string_view parameter and no life keeper required. If it is really important, I will remain it but I think that removeing the APIs is not a big problem.

**Comment by redboltz** [comment]
Deprecated attributes are added.

**Comment by Radagan** [comment]
Just a note, many of these deprecations are used in the example code. For new users like me to your library, those examples are very important to show best practices. I'd offer to update them, but as I'm still struggling to get my app properly working with mqtt_cpp, it probably wouldn't be that helpful...

**Comment by redboltz** [comment]
I believe that I updated the examples. Could you tell me which one uses deprecated APIs?

**Comment by redboltz** [comment]
See https://github.com/redboltz/mqtt_cpp/pull/364/files#diff-5cd3816d62c8ce39cf5414e0422e7b7e

**Comment by Radagan** [comment]
My apologies, I missed that update. Thank you.

**Comment by redboltz** [comment]
I noticed that the [wiki](https://github.com/redboltz/mqtt_cpp/wiki) has deprecated code. I updated it.

**Comment by jonesmz** [comment]
Now that 6.0 has been released, how many 6.0.x release do you wish to do before removing the deprecated APIs ?

**Comment by redboltz** [comment]
The version v6.x is maintenance mode now.
I created the branch v6.x for mandatory fix.

The master is going to v7.x. I'm going to post a PR that removes deprecated APIs.

**Comment by redboltz** [comment]
#382 should be fixed on v6.x.

So I will do the following steps.

1. remove v6.x branch to avoid confusion.
2. fixed #382 then merge it to the master.
3. release master as v6.0.3
4. create v6.x branch from the master.
