### ISSUE TITLE
Doc Request: example showing async useage

### ISSUE THREAD

**Issue by Radagan** [redboltz/mqtt_cpp#373]
I'm having difficulty figuring out how to use an mqtt_cpp client for more than a short duration. My scenario is a class that has a tls_?_client and this client stays running until my class calls disconnect. Meaning, I need it to continue to process commands it receives from Google IoT Core and publish events as requested. 

My application controls a small Linux single board computer that has physical IO, like relays, sensors, etc., and enables control of those via MQTT to Google IoT Core. So my class that implements the mqtt_cpp tls_?_client is created and used by it as the communication layer. In other words, I don't want creating or connecting this instance to block.

From reading about Boost ASIO, I understand that ios.run() blocks until it is done working, then stops. At which point, to get it to do anything else, I call ios.reset() and then ios.run() again. But what if a command (mqtt network side) comes in after it finishes it's work and has stopped? 

Also, every twenty minutes, I need to disconnect, recreate the jwt based password token, and connect again. I have a mutex in my code that keeps app side events from trying to publish until the connection is back up. Adding a little bit to the complexity, but not much. Connecting and disconnecting calls in mqtt_cpp seem very straightforward, what isn't to me is how ios works with it.

Any pointers and advice would be most welcome. Thank you for what looks to be a great library once I get my head around how it works. ;^)

**Comment by redboltz** [comment]
I believe that Boost.Asio asynchronous code doesn't `reset()`, `stop()`, and  re`run()` in normal case.

See 

```cpp
#include <iostream>

#include <boost/asio.hpp>

int main() {
    boost::asio::io_service ios;
    
    ios.post(
        [&ios] {
            std::cout << "callback1 is called" << std::endl;
            ios.post(
                [] {
                    std::cout << "callback2 is called" << std::endl;
                }
            );
        }
    );
    
    ios.run();
}
```

https://wandbox.org/permlink/SHvQCLUPmwHI6mwl

Typical application triggers the first async API such as `connect()`, and then wait callback. During waiting callback, `ios.run()` is blocked. If connection is established (or errored) then the callback is called. I use `ios.post()` to call the callback lambda expression but in actual application, the API is various such as `async_publish()`.
Callback is called from `ios.run()`. Have you ever used node.js ? The concept is similar. node.js 's event loop is corresponding to `ios.run()`.

You need to kick the next trigger in the callback. `mqtt_cpp` keep `boost::asio::async_read()` between `connect()` and `disconnect()`.

`ios.run()` can wait multiple events. You can wait both `mqtt_cpp`'s receive message and other event such as serial port receive or sensor value changed.

Of course sensor value changed is not directly supported by asio. You need to adapt your devices to asio.

Here is asio APIs.

https://www.boost.org/doc/libs/1_71_0/doc/html/boost_asio/reference.html

**Comment by redboltz** [comment]
> @redboltz Can you remind me, honestly I'm just not remembering right now, what's the expected behavior with regards to calling async_publish() and async_subscribe() before async_connect() is called?

> At least for subscriptions, I'd really like to see the client offer subscription management at a (optional) higher level.

subscribe() APIs must be called **after connection is established**. It's really easy. Just move `subcribe()` function call to connack callback as follows:

```cpp
    c->set_connack_handler(
        [&c](bool sp, std::uint8_t connack_return_code) {
            std::cout << "Connack handler called" << std::endl;
            std::cout << "Session Present: " << std::boolalpha << sp << std::endl;
            std::cout << "Connack Return Code: "
                      << mqtt::connect_return_code_to_str(connack_return_code) << std::endl;
            if (connack_return_code == mqtt::connect_return_code::accepted) {
                c->subscribe("topic1", mqtt::qos::at_most_once);
            }
            return true;
        }
    );
```

Publish is a little bit different.
`publish()` can be called **before connection is established** and **after disconnected**. It is knows as offline publish functionality. If it is QoS1 or QoS2, then the message is sent after the next connection is established.

See https://github.com/redboltz/mqtt_cpp/wiki/Offline-Publish

QoS1 and QoS2 message re-sending mechanism is a part of MQTT specification. So I expand it as offline publish. It is common. Other library such as MQTT.js has the similar functionality.
However, subscribe is different. It is only allowed during connection is established.

**Comment by Radagan** [comment]
Thank you both very much for the help. I'm really glad I posted.

@jonesmz Between no longer needing a mutex to protect publish and your reconnect timer example, my code greatly simplified. It does sound like we have similar projects. Happy to exchange ideas.

**Comment by ropieur** [comment]
>     auto pMqttClient = mqtt::make_asio_client(...);
> 
I suppose you meant mqtt::make_**async**_client ?

**Comment by jonesmz** [comment]
Yes.

**Comment by redboltz** [comment]
Now,  there are document and example:
https://github.com/redboltz/mqtt_cpp/wiki/Sync-vs-Async
https://github.com/redboltz/mqtt_cpp/blob/master/example/no_tls_async_client.cpp

**Comment by Radagan** [comment]
@redboltz Thank you
