### ISSUE TITLE
Why does v3 suback handler take a vector of optionals, but not v5?

### ISSUE THREAD

**Issue by jonesmz** [redboltz/mqtt_cpp#391]
Can you point out the section of 

http://docs.oasis-open.org/mqtt/mqtt/v3.1.1/errata01/os/mqtt-v3.1.1-errata01-os-complete.html#_Toc442180884

and

https://docs.oasis-open.org/mqtt/mqtt/v5.0/os/mqtt-v5.0-os.html#_Toc3901178

That explain this difference?

I can't find any indication of why the v3 version of the protocol would use optional for the reason code.

**Comment by redboltz** [comment]
In 3.1.1, I understand that suback returns maximum QoS if success, otherwise fail with no error code (just error). So I use nullopt for error. In v5, error code is expanded.
We can modify v3.1.1 suback handler to similar to v5.
mqtt_cpp v7 has major breaking change. It is a good time to modify it.

**Comment by jonesmz** [comment]
I actually think that in the event of error, 0x80 is returned.

From: http://docs.oasis-open.org/mqtt/mqtt/v3.1.1/errata01/os/mqtt-v3.1.1-errata01-os-complete.html#_Toc442180884

```
Allowed return codes:

0x00 - Success - Maximum QoS 0 
0x01 - Success - Maximum QoS 1 
0x02 - Success - Maximum QoS 2 
0x80 - Failure 
```

**Comment by redboltz** [comment]
> I actually think that in the event of error, 0x80 is returned.

I don't have any objections to remove optional. The first implementation is just use nullopt as failure.

**Comment by jonesmz** [comment]
I think that we should remove use of optional when possible. I think concrete value is better, both in terms of cpu usage, and also in terms of API usage.

**Comment by redboltz** [comment]
It's OK. Could you send a PR?

**Comment by jonesmz** [comment]
I will try to find time to do so, yes.
