### ISSUE TITLE
Why is your library not listed on the official mqtt.org?

### ISSUE THREAD

**Issue by ropieur** [redboltz/mqtt_cpp#396]
Hello redboltz,
Is there any reason why your library is not listed on mqtt.org official site? My google searches  for mqtt didn't point to your library. Being a fan of boost asio, I recently found yours just fortuitously.
Is there any limitation I should consider before adopting it?
Thanx

**Comment by jonesmz** [comment]
As someone who's had several pull requests merged into mqtt_cpp, I'm not aware of any protocol incompatibilities.

Please do try the library out, and submit bug reports or pull requests to improve it.

**Comment by redboltz** [comment]
Hi @ropieur ,

> Is there any reason why your library is not listed on mqtt.org official site? 

Do you mean https://github.com/mqtt/mqtt.github.io/wiki/libraries ?
I'm not sure how to add mqtt_cpp in the list. I couldn't find wiki editing rule.

> Is there any limitation I should consider before adopting it?

AFAIK, no. You can start from https://github.com/redboltz/mqtt_cpp/wiki.
@jonesmz , thank you for following up:)

**Comment by redboltz** [comment]
> I'm not sure how to add mqtt_cpp in the list. I couldn't find wiki editing rule.

I've checked the history https://github.com/mqtt/mqtt.github.io/wiki/libraries/_history.
It seems that many people edited the page. I think that I can add mqtt_cpp to the list. 

What do you think adding mqtt_cpp by myself?

**Comment by ropieur** [comment]
Wow, I am surprised by your fast reaction :)
It would be really great if you could add it.
I gonna test it directly.
Thank you for your great job (also for msgpack)

**Comment by redboltz** [comment]
Added. See https://github.com/mqtt/mqtt.github.io/wiki/libraries
