### ISSUE TITLE
mqtt_cpp::server::accept_handler

### ISSUE THREAD

**Issue by jonesmz** [redboltz/mqtt_cpp#400]
`mqtt_cpp::server::accept_handler = std::function<void(endpoint_t& ep)>;`

But the only place where this is called is here:

```
auto sp = std::make_shared<endpoint_t>(force_move(socket), version_);
if (h_accept_) h_accept_(*sp);
```

I think that we should change server::accept_handler to 

`mqtt_cpp::server::accept_handler = std::function<void(std::shared_ptr<endpoint_t> ep)>;`

**Comment by redboltz** [comment]
I agree with you.
