### ISSUE TITLE
CI on your own account

### ISSUE THREAD

**Issue by redboltz** [redboltz/mqtt_cpp#404]
@jonesmz , if you set up your own CI environment, the process might become faster.
See https://github.com/redboltz/mqtt_cpp/wiki/CI-rule#setup-ci-on-your-account

That means your branch test on CI that is corresponding to your account before sending a PR.

**Comment by jonesmz** [comment]
I activated travis ci on my account.

We'll need to make a modification to the .travis file to support having travis build branches though.

**Comment by jonesmz** [comment]
You can close this issue now :-)
