### ISSUE TITLE
Support for BOOST_ASIO_NO_DEPRECATED

### ISSUE THREAD

**Issue by ropieur** [redboltz/mqtt_cpp#409]
Impossible for me to elude the #define BOOST_ASIO_NO_DEPRECATED.
Is there any plan to upgrade the code in a near future?

**Comment by redboltz** [comment]
I just recognized the issue now.

The minimum boost requirement is 1.66.0 on the master branch.
Does BOOST_ASIO_NO_DEPRECATED work on 1.66.0?

If it does, I will update step by step. But priority is not so high because I have other higher priority issues.

**Comment by redboltz** [comment]
@ropieur , do you know where `BOOST_ASIO_NO_DEPRECATED` is documented? I want to know features that will be deprecated.

**Comment by ropieur** [comment]
You should look at [here](https://www.boost.org/doc/libs/1_71_0/doc/html/boost_asio/net_ts.html)

**Comment by ropieur** [comment]
I found a bug in const_buffer_util.hpp
BOOST_VERION should be BOOST_VER**S**ION (with an S)

**Comment by ropieur** [comment]
- Replace all **io_service** by **io_context**
- In mqtt/null_strand.hpp: ios_.post( becomes boost::asio::post(ios_,
- In mqtt/client.hpp line 911, lamdba should take Iterator (or auto) instead of as::ip::tcp::resolver::iterator
- and in type_erased_socket.hpp, (as mentioned in closed ticket #345, but still don't know why)
skip #if BOOST_VERSION >= 106700

**Comment by redboltz** [comment]
@ropieur , thank you very much! Your comment would save my time a lot. 
I think that I can support BOOST_ASIO_NO_DEPRECATED earlier than I thought at first thanks to your comment.

I will fix BOOST_VERSION bug separately and immediately.

**Comment by redboltz** [comment]
#413 fixes BOOST_VERSION problem.

**Comment by redboltz** [comment]
@jonesmz , I will create a PR that support `BOOST_ASIO_NO_DEPRECATED` **after** the series of `enum class` pull requests are merged to avoid conflict.

**Comment by jonesmz** [comment]
Alright, sounds good to me.

**Comment by redboltz** [comment]
#268 is related issue.

I think that the following step is good:

1. Support BOOST_ASIO_NO_DEPRECATED.
2. Introduce MQTT_NS wrapper that wraps Boost.Asio and NetworkTS, and add MQTT_STD_NETWORK macro.

**Comment by redboltz** [comment]
@jonesmz , I think that the series of enum class pull requests have been merged. Is that right?

I will start implementing BOOST_ASIO_NO_DEPRECATED support.

**Comment by jonesmz** [comment]
Yes. Go ahead.

**Comment by redboltz** [comment]
I got compile error as follows:

```
[ 50%] Building CXX object test/CMakeFiles/pubsub_no_strand.dir/pubsub_no_strand.cpp.o
In file included from /home/kondo/work/mqtt_cpp/test/pubsub_no_strand.cpp:8:
In file included from /home/kondo/work/mqtt_cpp/test/test_settings.hpp:16:
In file included from /home/kondo/work/mqtt_cpp/include/mqtt/client.hpp:26:
/home/kondo/work/mqtt_cpp/include/mqtt/tcp_endpoint.hpp:72:13: error: no matching function for call to 'bind_executor'
            as::bind_executor(
            ^~~~~~~~~~~~~~~~~
/home/kondo/work/mqtt_cpp/include/mqtt/type_erased_socket.hpp:25:43: note: in instantiation of function template specialization
```

candidate templates

```
/usr/include/boost/asio/bind_executor.hpp:498:1: note: candidate template ignored: requirement
      'is_executor<mqtt::null_strand>::value' was not satisfied [with Executor = mqtt::null_strand, T = std::function<void
      (const boost::system::error_code &, unsigned long)>]
bind_executor(const Executor& ex, BOOST_ASIO_MOVE_ARG(T) t,
^
/usr/include/boost/asio/bind_executor.hpp:509:1: note: candidate template ignored: requirement 'is_convertible<mqtt::null_strand
      &, boost::asio::execution_context &>::value' was not satisfied [with ExecutionContext = mqtt::null_strand, T =
      std::function<void (const boost::system::error_code &, unsigned long)>]
bind_executor(ExecutionContext& ctx, BOOST_ASIO_MOVE_ARG(T) t,
```

It seems that null strand needs to meet executor concept.
https://github.com/redboltz/mqtt_cpp/blob/master/include/mqtt/null_strand.hpp#L20

I'm looking for a good way to do that but it's complicated. If someone know the way, please tell me.

Note: null_strand is do nothing strand. It is used to remove strand if dispatch in endpoint code.

**Comment by redboltz** [comment]
The error is reported ad modified `tcp_endpoint.hpp`.

The essence of the code is as follows:

```cpp
template <typename Socket, typename Strand>
class tcp_endpoint {
public:
   ...

    template <typename MutableBufferSequence, typename ReadHandler>
    void async_read(
        MutableBufferSequence && buffers,
        ReadHandler&& handler) {
        as::async_read(
            tcp_,
            std::forward<MutableBufferSequence>(buffers),
            as::bind_executor(
                strand_,
                std::forward<ReadHandler>(handler)
            )
        );
    }

```

**Comment by redboltz** [comment]
I solved the error.
I'm not sure it is the best way. At least, it successfully compiled and all tests passed.

```cpp
namespace MQTT_NS {

namespace as = boost::asio;

struct null_strand {
    null_strand(as::io_context& ioc) noexcept : ioc_(ioc) {}
    template <typename Func, typename Allocator>
    void post(Func&& f, Allocator) const {
        as::post(
            ioc_,
            [f = std::forward<Func>(f)] () mutable {
                std::forward<Func>(f)();
            }
        );
    }
    template <typename Func, typename Allocator>
    void defer(Func&& f, Allocator) const {
        as::defer(
            ioc_,
            [f = std::forward<Func>(f)] () mutable {
                std::forward<Func>(f)();
            }
        );
    }
    template <typename Func, typename Allocator>
    void dispatch(Func&& f, Allocator) const {
        std::forward<Func>(f)();
    }
    void on_work_started() const noexcept {}
    void on_work_finished() const noexcept {}
    as::io_context& context() noexcept{ return ioc_; }
    as::io_context const& context() const noexcept { return ioc_; }
private:
    as::io_context& ioc_;
};

inline bool operator==(null_strand const& lhs, null_strand const& rhs) {
    return std::addressof(lhs) == std::addressof(rhs);
}

inline bool operator!=(null_strand const& lhs, null_strand const& rhs) {
    return !(lhs == rhs);
}

} // namespace MQTT_NS

namespace boost {
namespace asio {

template<>
struct is_executor<MQTT_NS::null_strand> : std::true_type {
};

} // namespace asio
} // namespace boost
```

**Comment by redboltz** [comment]
I sent the PR to fix the issue as #419. Could you check this?

**Comment by ropieur** [comment]
@redboltz,
Just checked impl_409 branch. Everything is ok, except for #345.

**Comment by redboltz** [comment]
I reopen #345. I close the issue.
