### ISSUE TITLE
Code improvement suggestion

### ISSUE THREAD

**Issue by ropieur** [redboltz/mqtt_cpp#426]
Hi @redboltz,

You could emulate strong typedef for retain flag by using an empty enum class (see [article](https://accu.org/index.php/journals/2683))

```
enum class retained : bool { };

std::ostream &operator<<(std::ostream &os, retained flag)
{
   return os << std::boolalpha << static_cast<bool>(flag);
}
```

That would force explicit writing:
```
retained{true}
retained{false}
```
But this would indeed break all existing clients ...

**Comment by jonesmz** [comment]
I'd like to point out that the concept of retain gets treated as a flag in various bitfields in packets.

Personally, I'd rather see 

```
enum class retain : std::uint8_t { yes = 0b00000001, no = 0b00000000 }
```

As that would make the usage of it visually similar to the other enums that I recently added to the project (e.g. qos, reason_codes, so on), and also (potentially) make it possible to overload operator| in a very straightforward way

But I don't feel strongly about it, and really only care about how it looks to the end user.

Towards this same end, if we're going to change retain, we should also change the dup field for the publish_handler() to an enum.

**Comment by redboltz** [comment]
I like this one:

```cpp
enum class retain : std::uint8_t { yes = 0b00000001, no = 0b00000000 }
```
@jonesmz , could you write 

The goal is avoid user's misuse. Both achieves the goal.

**Comment by jonesmz** [comment]
@ropieur I've implemented a collection of enums, and some helper classes to make option handling much more type safe.

Have you had a chance to look at the changes? Do you have any further suggestions for them?

**Comment by jonesmz** [comment]
@redboltz I think this issue has been resolved.

**Comment by jonesmz** [comment]
@redboltz I think this issue has been resolved.

**Comment by ropieur** [comment]
Hello @jonesmz,
I reviewed the changes and it's ok to me.
