### ISSUE TITLE
[question] Why test_broker compare clean session and v3.1.1?

### ISSUE THREAD

**Issue by redboltz** [redboltz/mqtt_cpp#436]
@jonesmz , I think that this part of code is updated by you.

I don't understand why clean_session() and protocol_version v3.1.1 comparison connect with &&.

I think that clean_session() processing is in common between v3.1.1 and v5.

https://github.com/redboltz/mqtt_cpp/blob/ed216205ce2d327d712bd681cf7d0ebc78ce6829/test/test_broker.hpp#L940
https://github.com/redboltz/mqtt_cpp/blob/ed216205ce2d327d712bd681cf7d0ebc78ce6829/test/test_broker.hpp#L986

Am I missing something?

**Comment by redboltz** [comment]
I read your comment

```
            // In v3_1_1, we need to clear any subscriptions at the end of the session.
            // In v5, we always save them, and clear them at the beginning of a session.
```

and standard. https://docs.oasis-open.org/mqtt/mqtt/v5.0/os/mqtt-v5.0-os.html#_Toc3901039

Indeed, I understand your implementation. But I'm not sure MQTT v5 really intent to this breaking change. I still think that it might be just wording change and intent to the same meaning as v3.1.1.

Hmm...

**Comment by redboltz** [comment]
I found MQTT wiki that is linked from mqtt.org:

https://github.com/mqtt/mqtt.github.io/wiki/Differences-between-3.1.1-and-5.0

1. Session expiry: Split the Clean Session flag into a Clean Start flag which indicates that the session should start without using an existing session, and a Session Expiry interval which says how long to retain the session after a disconnect. The session expiry interval can be modified at disconnect. **Setting of Clean Start to 1 and Session Expiry Interval to 0 is equivalent in MQTT v3.1.1 of setting Clean Session to 1**.

@jonesmz , what do you think about that?

**Comment by redboltz** [comment]
The reason I think that the basic meaning of clean start is not changed, I don't see any reasonable benefit to change that behavior.

If user want to keep the previous session, then set Clean Start to 0. And keep the setting. If user want to clear the previous session, then set Clean Start to 1. 

This wording change effects to the following case:

The previous session is Clean Start 1, and the currently connecting session is Clean Start 0. In this case the current session keeps the previous session even if the previous session's Clean Start is 1.

I guess that the wording change is not intend to the behavior above.
But I'm not English expert. It is too difficult to me.

**Comment by redboltz** [comment]
Ah maybe I understand.
Session Expiry Interval is important factor. Clean Start is only evaluated on connection as you implemented. Even if Clean Start is set to 0, if Session Expiry Interval is set to 0, then the session state is cleared on close. 

So MQTT v3.1.1 equivalent setting is as follows:

|v3.1.1 Clean Session|v5 Clean Start|v5 Session Expiry Interval|
|---|---|---|
|0|0|0xFFFF(infinity)|
|1|1|0 or absent (on close clear session state|

**Comment by redboltz** [comment]
Some of unit tests aren't considered the condition above. I will fix them.

I noticed the issue during implementing #435 fix. After the fix, `shared_ptr<endpoint>` lifetime management will be clear the same as v3.1.0 (mqtt_cpp version).
And then, I will back to #430. It is hard way as I thought at first. Please wait a moment.

**Comment by jonesmz** [comment]
Correct. The session expiry interval is the key factor.

Currently we do not have any of

- Session Expiry
- Will Delay
- Publication Expiry

Implemented in test_broker.hpp. while I would like to use features like that, I have not had time to do any work on them.

**Comment by jonesmz** [comment]
If we do implement all of those, its not clear to me that making a new boost deadline timer for each is the right approach. I am not sure what the runtime cost of boost deadline timer is. Maybe it is very cheap. If so. We can use it. If it is not cheap, maybe a design that has multiple events sharing a timer somehow.

**Comment by redboltz** [comment]
> Maybe it is very cheap. If so. We can use it. 

Yes I think that it is cheap too. Let's use deadline_timer directly. 
I'm fixing #435. In this fix, I'm updating tests and I'm adding minimal support of Session Expiry Interval. It only distinguish 0 or not. Not set actual timer.
Now, existing reconnecting v5 tests are semantically wrong. Because they don't clear session enough.

Please wait editing test_broker.hpp to avoid conflict.
