### ISSUE TITLE
Decide minimum supported Windows version

### ISSUE THREAD

**Issue by jonesmz** [redboltz/mqtt_cpp#445]
Azure Pipelines produces compiler warning because the project isn't defining a variable.

```
  Please define _WIN32_WINNT or _WIN32_WINDOWS appropriately. For example:
  - add -D_WIN32_WINNT=0x0501 to the compiler command line; or
  - add _WIN32_WINNT=0x0501 to your project's Preprocessor Definitions.
  Assuming _WIN32_WINNT=0x0501 (i.e. Windows XP target).
```

I think mqtt_cpp should only support versions of windows that are not end-of-life. 

Windows 7 is end-of-life on January 2020. Maybe set the minimum version to Windows 7?

**Comment by redboltz** [comment]
> Windows 7 is end-of-life on January 2020. Maybe set the minimum version to Windows 7?

Yes, I think so.
