### ISSUE TITLE
Initialize suback_reason_code from qos

### ISSUE THREAD

**Issue by redboltz** [redboltz/mqtt_cpp#452]
I'm working to migrate my broker from v6.0.0. to master to check #444.
I noticed that `subscribe_options`, `qos`, and `suback_reason_code` conversion in inconvenient.

When the broker receives subscribe, one of the parameter is `subscribe_options`. It's good.
I can get `qos` from `subscribe_options` using `get_qos()`. It's good.
When the broker sends to suback to the client, I need to create the argument `suback_reason_code` from `qos`, if subscribe is successfully accepted.

Now, I need to do

```cpp
auto rc = static_cast<mqtt::suback_reason_code>(qos)
```

or

```cpp
mqtt::suback_reason_code rc;
switch (qos) {
case mqtt::qos::at_most_once:
    rc = mqtt::suback_reason_code::granted_qos_0;
    break;
case mqtt::qos::at_least_once:
    rc = mqtt::suback_reason_code::granted_qos_1;
    break;
case mqtt::qos::exactly_once:
    rc = mqtt::suback_reason_code::granted_qos_2;
    break;
}
```

I think that if `suback_reason_code` has a constructor that has `qos` parameter, then I can implement the broker easier. What do you think?

In addition, when the broker receives publish message, then the broker needs to adjust qos level between publish qos and subscribed qos.  Lower qos is chosen. If `qos` has `operator<`, I can easy to implement the broker. What do you think?

BTW, I will migrate my broker in two days. After I will do some performance tests in actual communication environment, then I will merge #444.

**Comment by jonesmz** [comment]
> I think that if suback_reason_code has a constructor that has qos parameter, then I can implement the broker easier. What do you think?

I think it's a good idea to auto-convert from `mqtt::qos` -> `mqtt::suback_reason_code` and `mqtt::qos` -> `mqtt::v5::suback_reason_code`.

I do not think it is a good idea to auto-convert `mqtt::suback_reason_code` -> `mqtt::qos`, or `mqtt::v5::suback_reason_code` -> `mqtt::qos`

To do this, `mqtt::suback_reason_code` cannot be an enum (At least, I don't know of a way to provide implicit conversion between enums...?), it must be a class, like `mqtt::subscribe_options`.

Also notice this: https://stackoverflow.com/a/57286964

Maybe have the following:

1. v3.1.1 enum suback_reason_code
2. v5 enum suback_reason_code
3. v3.1.1 class for implicit-conversions for suback_reason_code
4. v5 class for implicit-conversions for suback_reason_code
5. Use std::variant<v3.1.1::class, v5::class>

?

> In addition, when the broker receives publish message, then the broker needs to adjust qos level between publish qos and subscribed qos. Lower qos is chosen. If qos has operator<, I can easy to implement the broker. What do you think?

I use `std::min<mqtt::qos, mqtt::qos>(A, B)`

This does not work for you?

**Comment by redboltz** [comment]
> I use std::min<mqtt::qos>(A, B)
> 
> This does not work for you?

I looked over your comment. And post #453 .
I will check `std::min<mqtt::qos>(A, B)` soon.

**Comment by redboltz** [comment]
> I will check std::min<mqtt::qos>(A, B) soon.

It works. I did something wrong. I closed #453

**Comment by redboltz** [comment]
> I think it's a good idea to auto-convert from mqtt::qos -> mqtt::suback_reason_code and mqtt::qos -> mqtt::v5::suback_reason_code.
> 
> I do not think it is a good idea to auto-convert mqtt::suback_reason_code -> mqtt::qos, or mqtt::v5::suback_reason_code -> mqtt::qos

I think that both manual convert is also good. 

I think that the following is good enough.

https://wandbox.org/permlink/RD9c7EBrj53L8c2V

What do you think?

**Comment by jonesmz** [comment]
I guess that's good enough.

It would be nice to provide a type-safe implicit conversion, but i don't think C++ supports that yet.
