### ISSUE TITLE
Add another set_will function

### ISSUE THREAD

**Issue by jonesmz** [redboltz/mqtt_cpp#468]
I'm using `MQTT_NS::endpoint::set_will` like this:

```cpp
pEndpoint->set_will(MQTT_NS::will(MQTT_NS::allocate_buffer(stateTopic),
                                  MQTT_NS::allocate_buffer(stateString),
                                  true, // Retain, so that later connected units can know the status.
                                  MQTT_NS::qos::exactly_once));
```

We should add another set_will function so that I can instead do this:

```cpp

```cpp
pEndpoint->set_will(MQTT_NS::allocate_buffer(stateTopic),
                    MQTT_NS::allocate_buffer(stateString),
                    true, // Retain, so that later connected units can know the status.
                    MQTT_NS::qos::exactly_once);
```

**Comment by redboltz** [comment]
* It's nice to have. Is this based on #469?
* Could you write the PR for this?
* Would you like to include the PR to v7.0.0?

**Comment by redboltz** [comment]
I'm going to release v7.0.0 today.
This issue is just API addition, no breaking change, so it is a candidate of v7.1.0.

**Comment by jonesmz** [comment]
I'll try to write a PR for this today or tomorrow.

Go ahead and release
