### ISSUE TITLE
password for private key file

### ISSUE THREAD

**Issue by ineffective** [redboltz/mqtt_cpp#471]
I can't find any way to set password for private key. I believe in boost asio it is done by using ssl::context::set_password_callback, but I can't find anything regarding this call in source code. I also don't see any way to get ctx_ from client/server object. Is it currently impossible to set it or do I miss something?

**Comment by redboltz** [comment]
We don't have the setter function, so far. Maybe the default callback is called.
I understand that `ssl::context::set_password_callback` is the right one.

The current asio has 
https://www.boost.org/doc/libs/1_71_0/doc/html/boost_asio/reference/ssl__context.html

And only a part of them are supported by mqtt_cpp.

I think that adding reference (const/non const) getter for `ssl::context` is good only if `MQTT_USE_TLS` is defined.

mqtt_cpp start from minimal TLS support. At that time, I implement some of wrapper function for `ssl::context`. (It is not directly reflected their name though)
Continue adding all member functions is not a practical approach.

So I think that getter is good for advanced usecase. However, `set_password_callback` seems to be commonly used. Also providing the wrapper for `set_password_callback` might be better.

**Comment by jonesmz** [comment]
Personally I think it's better to just provide a getter for ssl::context (and asio::io_context), and leave it at that.

MQTT_CPP doesn't care about the details of the ssl context beyond that it does SSL. There's not a lot of value in providing any of these wrapper functions if all they'd do is just call the underlying ssl function.

**Comment by redboltz** [comment]
@jonesmz , let me clarify.

You mean,

1. Add context getter.
2. Don't remove existing member functions for the context.
3. Don't add set_password_callback.

Am I understanding correctly?

**Comment by jonesmz** [comment]
1. Add context getter.
2. **Do** remove existing member functions for the context.
3. Don't add set_password_callback.

**Comment by jonesmz** [comment]
Or maybe

1. Add context getter.
2. Mark existing member functions for the context as deprecated. Remove in 8.0.0
3. Don't add set_password_callback.

**Comment by redboltz** [comment]
I agree. I use deprecated mark.

**Comment by redboltz** [comment]
@ineffective , I implemented #472. Could you try this?

**Comment by redboltz** [comment]
meged. @ineffective if you still have a problem, please reopen the issue.

**Comment by ineffective** [comment]
No problems, I used new version and everything works as expected, so no need for reopening.
