### ISSUE TITLE
async_client::connect() uses blocking DNS resolve, and blocking connect function

### ISSUE THREAD

**Issue by jonesmz** [redboltz/mqtt_cpp#495]
```cpp
    void connect(std::shared_ptr<Socket>&& socket, std::vector<v5::property_variant> props, any session_life_keeper = any()) {
        as::ip::tcp::resolver r(ioc_);
        auto eps = r.resolve(host_, port_);
        socket_ = force_move(socket);
        base::socket_optional().emplace(socket_);
        connect_impl(*socket_, eps.begin(), eps.end(), force_move(props), force_move(session_life_keeper));
    }
```

Calls

```cpp
template <typename Iterator>
    void connect_impl(Socket& socket, Iterator it, Iterator end, std::vector<v5::property_variant> props, any session_life_keeper) {
        as::async_connect(
            socket.lowest_layer(), it, end,
            [this, self = this->shared_from_this(), &socket, session_life_keeper = force_move(session_life_keeper), props = force_move(props)]
            (boost::system::error_code const& ec, Iterator) mutable {
                if (!ec) {
                    base::set_connect();
                    if (ping_duration_ms_ != 0) {
                        set_timer();
                    }
                }
                if (base::handle_close_or_error(ec)) return;
                handshake_socket(socket, force_move(props), force_move(session_life_keeper));
            });
    }
```

Which calls

```cpp
template <typename Strand>
    void handshake_socket(
        tcp_endpoint<as::ssl::stream<as::ip::tcp::socket>, Strand>& socket,
        std::vector<v5::property_variant> props,
        any session_life_keeper) {
        socket.async_handshake(
            as::ssl::stream_base::client,
            [this, self = this->shared_from_this(), session_life_keeper = force_move(session_life_keeper), props = force_move(props)]
            (boost::system::error_code const& ec) mutable {
                if (base::handle_close_or_error(ec)) return;
                start_session(force_move(props), force_move(session_life_keeper));
            });
    }
```

Which finally calls

```cpp
    void start_session(std::vector<v5::property_variant> props, any session_life_keeper) {
        base::async_read_control_packet_type(force_move(session_life_keeper));
        // sync base::connect() refer to parameters only in the function.
        // So they can be passed as view.
        base::connect(
            buffer(string_view(client_id_)),
            ( user_name_ ? buffer(string_view(user_name_.value()))
                         : buffer() ),
            ( password_  ? buffer(string_view(password_.value()))
                         : buffer() ),
            will_,
            keep_alive_sec_,
            force_move(props)
        );
    }
```

This mix of synchronous operations and async operations is confusing and potentially risky. The call to connect() returns before the connection is actually established.

I think we should move the connect() function to sync_client.hpp

and make a new async_connect() function in async_client.hpp.

The sync_client.hpp function would use 100% blocking functions

The async_client.hpp function would use 100% non-blocking functions.

**Comment by redboltz** [comment]
Basically, I agree with you. `connect()` is a weird part of mqtt_cpp.

The approach is a little bit different.

|client class|member function|note|
|---|---|---|
|client|connect, async_connect||
|sync_client|connect|use client::connect|
|async_client|async_client|use client::async_connect|

A user uses `client` directly. It is consistent to other APIs such as `publish()`/`async_publish()`.

There are several phases.

1. resolve
2. TCP connect
3. TLS handshake
4. WS handshake
5. send MQTT connect
6. receive MQTT connack (contains SessionPresent and Connect[Reason|Return]Code)

mqtt_cpp doesn't have (sync) read functionality and no plan to have it.

So, `connect()` does 1 to 5 synchronously, and `async_connect()` does 1 to 5 asynchronously.

User still need to use `set_connack_handler()` to get connack information.

Maybe we also need to have `connect(error_code const&)`. It just set error_code if error happens during 1 to 5. `connect()` throws exception in the same case.

It is a breaking change. So it would be implemented in v8.0.0.
