### ISSUE TITLE
Provide macro to remove deprecated functions

### ISSUE THREAD

**Issue by jonesmz** [redboltz/mqtt_cpp#499]
This allows people who are planning to upgrade to a newer release to ensure that their code will compile with the newer release before that release is made.

**Comment by redboltz** [comment]
We already have `MQTT_DEPRECATED_TEST` macro.
See https://github.com/redboltz/mqtt_cpp/blob/master/include/mqtt/deprecated.hpp#L10

It is originally designed for testing deprecated functions. So it is not documentd
Maybe it should be renamed as something like `MQTT_USE_DEPRECATED` and add document to https://github.com/redboltz/mqtt_cpp/wiki/Config.

What do you think?

**Comment by jonesmz** [comment]
That seems reasonable to me
