### ISSUE TITLE
How to keep client connection alive?

### ISSUE THREAD

**Issue by sptrakesh** [redboltz/mqtt_cpp#502]
I am trying to implement a custom MQTT server and started with the tls_server example.  Using a listener written using this project, I do not see any issues with the connection dropping.  However, I am also testing using MQTT.fx desktop client.  The client (although I set keep-alive to 15s) loses connection after a while.  I added a `pingreq_handler` function that logs ping request, and I see that once, but nothing after that.  Do I need to do anything special to allow client to keep the connection?  The only log message the desktop client logs is not very helpful:

```2019-10-04 13:27:38,175  INFO --- MqttFX ClientModel             : Broker connection lost: Resetting client.```

The desktop client does stay alive when connected to an AWS IoT broker.

**Comment by redboltz** [comment]
I'm not sure MQTT.fx implementation. But if you MQTT server doesn't disconnect the session from the server side, the session might close **from the client(MQTT.fx) side**.

When your server receives pingreq, then the server need to send back pingresp to the client.
See test_broker implementation https://github.com/redboltz/mqtt_cpp/blob/master/test/test_broker.hpp#L336.

**Comment by sptrakesh** [comment]
Thanks, that was exactly what I was missing.  MQTT.fx is built on Eclipse Paho Java library.
