### ISSUE TITLE
travis-ci badge isn't reflected the master branch status

### ISSUE THREAD

**Issue by redboltz** [redboltz/mqtt_cpp#504]
travis-ci badge looks error but the actual master branch is not error:
https://github.com/redboltz/mqtt_cpp#mqtt-clientserver-for-c14-based-on-boostasio

It seems that the following line avoid master build
https://github.com/redboltz/mqtt_cpp/blob/master/.travis.yml#L5

How to fix it?

**Comment by jonesmz** [comment]
I think we should simply remove that line entirely.

Then travis will build all branches.

**Comment by redboltz** [comment]
Travis-ci is no longer used. Now I user github actions.
