### ISSUE TITLE
CI balancing strategy

### ISSUE THREAD

**Issue by redboltz** [redboltz/mqtt_cpp#509]
## Supported environment
|CI|Linux(gcc)|Linux(clang)|osx(clang)|windows(msvc)|
|---|---|---|---|---|
|travis-ci|x|x|x|-|
|azure build PL|x|x(maybe)|x|x|

## Parallel build limit
* travis-ci
  * osx (VM)
     * At most 2.
  * Linux (Container)
     * At most 5. (maybe)
* azure build PL
  * Total 10

## Current assignment
|CI|Linux(gcc)|Linux(clang)|osx(clang)|windows(msvc)|
|---|---|---|---|---|
|travis-ci|x|x|x|-|
|azure build PL|-|-|-|x|

The current bottleneck is osx builds. They might be able to move to azure build PL.

**Comment by jonesmz** [comment]
@redboltz 

See here for an attempt to improve the CI configuration: https://github.com/jonesmz/mqtt_cpp/tree/travis-config-changes

Note: Travis CI does not support applying the "addons" clause to all items in the matrix, it gets skipped. This is *not* properly documented on the Travis CI website, but is documented in a few bug reports.

Work-around, use the "install" section to run apt commands before compiling.

-------------------------------------------------------------------------------

Precompiled headers are well supported in GCC, Clang, and MSVC for the last few years. They can drastically reduce compilation times.

CMake supports precompiled headers in 3.16 : https://www.reddit.com/r/cpp/comments/cx59ci/pch_support_has_been_merged_to_cmake_unity_builds/

But it's not all that difficult to set up PCH support by hand for carefully controlled situations, such as a CI system.

Essentially we just need to "compile" mqtt/mqtt_client_cpp.hpp, and then include the resulting file in the commandline for all of the example / test apps that we build. That should reduce compile times by between 20 and 40 percent.

E.g. https://stackoverflow.com/questions/28868049/decrease-clang-compile-time-with-precompiled-headers

Another approach would be to use extern templates and explicit template instantiation. Use that to generate a single .o file, which gets included in all of the test apps.

A third technique is to link all of the existing test applications into a single test application, in addition to using precompiled headers and/or extern template / explicit instantiation.

All of these approaches, separately, or together, will improve build times.


---------------------------------------------


Also, did you know that the current Azure Pipelines build is not running test group 7?

**Comment by redboltz** [comment]
I believe that the issue is fixed by github actions and azure pipelines combination.
