### ISSUE TITLE
can't compile mqtt client with tls

### ISSUE THREAD

**Issue by okideal** [redboltz/mqtt_cpp#511]
Hello, I encountered a problem when compile the [https://github.com/redboltz/mqtt_cpp/blob/master/example/tls_client.cpp](url) example client code with tls.

`/root/CLionProjects/test_mqtt_cpp/main.cpp: In function ‘int main()’:
/root/CLionProjects/test_mqtt_cpp/main.cpp:20:23: error: ‘make_tls_sync_client’ is not a member of ‘mqtt’
     auto c = MQTT_NS::make_tls_sync_client(ioc, host, port);
                       ^~~~~~~~~~~~~~~~~~~~
/root/CLionProjects/test_mqtt_cpp/main.cpp:20:23: note: suggested alternative: ‘make_async_client’
     auto c = MQTT_NS::make_tls_sync_client(ioc, host, port);
                       ^~~~~~~~~~~~~~~~~~~~
                       make_async_client
/root/CLionProjects/test_mqtt_cpp/main.cpp:21:70: error: template argument 1 is invalid
     using packet_id_t = typename std::remove_reference_t<decltype(*c)>::packet_id_t;
                                                                      ^
/root/CLionProjects/test_mqtt_cpp/main.cpp: In lambda function:
/root/CLionProjects/test_mqtt_cpp/main.cpp:52:32: error: ‘c’ is not captured
                     pid_sub1 = c->subscribe("mqtt_client_cpp/topic1", MQTT_NS::qos::at_most_once);
                                ^
/root/CLionProjects/test_mqtt_cpp/main.cpp:45:38: note: the lambda has no capture-default
             [&c, &pid_sub1, &pid_sub2]
                                      ^
/root/CLionProjects/test_mqtt_cpp/main.cpp:20:10: note: ‘<typeprefixerror>c’ declared here
     auto c = MQTT_NS::make_tls_sync_client(ioc, host, port);
          ^
/root/CLionProjects/test_mqtt_cpp/main.cpp:53:32: error: ‘c’ is not captured
                     pid_sub2 = c->subscribe(
                                ^
/root/CLionProjects/test_mqtt_cpp/main.cpp:45:38: note: the lambda has no capture-default
             [&c, &pid_sub1, &pid_sub2]
                                      ^
/root/CLionProjects/test_mqtt_cpp/main.cpp:20:10: note: ‘<typeprefixerror>c’ declared here
     auto c = MQTT_NS::make_tls_sync_client(ioc, host, port);
          ^
/root/CLionProjects/test_mqtt_cpp/main.cpp: In function ‘int main()’:
/root/CLionProjects/test_mqtt_cpp/main.cpp:74:22: error: ‘packet_id_t’ has not been declared
                     (packet_id_t packet_id){
                      ^~~~~~~~~~~
/root/CLionProjects/test_mqtt_cpp/main.cpp:81:22: error: ‘packet_id_t’ has not been declared
                     (packet_id_t packet_id){
                      ^~~~~~~~~~~
/root/CLionProjects/test_mqtt_cpp/main.cpp:87:22: error: ‘packet_id_t’ has not been declared
                     (packet_id_t packet_id){
                      ^~~~~~~~~~~
/root/CLionProjects/test_mqtt_cpp/main.cpp:94:22: error: ‘packet_id_t’ has not been declared
                     (packet_id_t packet_id, std::vector<MQTT_NS::suback_return_code> results){
                      ^~~~~~~~~~~
/root/CLionProjects/test_mqtt_cpp/main.cpp:113:40: error: ‘packet_id_t’ was not declared in this scope
                      MQTT_NS::optional<packet_id_t> packet_id,
                                        ^~~~~~~~~~~
/root/CLionProjects/test_mqtt_cpp/main.cpp:113:51: error: template argument 1 is invalid
                      MQTT_NS::optional<packet_id_t> packet_id,
                                                   ^
/root/CLionProjects/test_mqtt_cpp/main.cpp: In lambda function:
/root/CLionProjects/test_mqtt_cpp/main.cpp:121:52: error: invalid type argument of unary ‘*’ (have ‘int’)
                     std::cout << "packet_id: " << *packet_id << std::endl;
                                                    ^~~~~~~~~
CMakeFiles/test_mqtt_cpp.dir/build.make:62: recipe for target 'CMakeFiles/test_mqtt_cpp.dir/main.cpp.o' failed
make[3]: *** [CMakeFiles/test_mqtt_cpp.dir/main.cpp.o] Error 1
CMakeFiles/Makefile2:72: recipe for target 'CMakeFiles/test_mqtt_cpp.dir/all' failed
make[2]: *** [CMakeFiles/test_mqtt_cpp.dir/all] Error 2
CMakeFiles/Makefile2:84: recipe for target 'CMakeFiles/test_mqtt_cpp.dir/rule' failed
make[1]: *** [CMakeFiles/test_mqtt_cpp.dir/rule] Error 2
Makefile:118: recipe for target 'test_mqtt_cpp' failed
make: *** [test_mqtt_cpp] Error 2`

And I've add `OPTION(MQTT_USE_TLS "Enable building TLS code" ON)` and Boost dependencies in CMakeList.

Thanks in advance~

**Comment by jonesmz** [comment]
We'll need a minimal reproduction

Please post the bare minimum cmake file and associated c++ file that reproduces the issue.

We also need platform and compiler information.

**Comment by ineffective** [comment]
`CMakeLists.txt` file that I used to compile `tls_client.cpp` was:

```cmake
cmake_minimum_required(VERSION 3.1)
project("mqtt-test" VERSION 1.0.0.0 LANGUAGES CXX)
include(FindBoost)
include(FindOpenSSL)

set(CMAKE_SCRIPTS "${CMAKE_SOURCE_DIR}/cmake")
set(THREADS_PREFER_PTHREAD_FLAG ON)
find_package(Threads REQUIRED)

set(Boost_USE_MULTITHREADED ON)
find_package(Boost 1.66.0 REQUIRED system)

include_directories(${Boost_INCLUDE_DIR} ${OPENSSL_INCLUDE_DIR} ".")
add_executable(test tls_client.cpp)
target_link_libraries(test ${Boost_LIBRARIES} ${OPENSSL_LIBRARIES} Threads::Threads)
```

I'm not that familiar with `cmake` so I also (as mentioned in previous post) added:

```cpp
#define MQTT_USE_TLS
```

before all headers in `tls_client.cpp` file instead of defining it throught `cmake`.

**Comment by redboltz** [comment]
> 1. Provide clear information that MQTT_USE_TLS must be defined if TLS is expected.

It should be provided at https://github.com/redboltz/mqtt_cpp/wiki/Config. I just noticed that there was only old information (`MQTT_NO_TLS`). I updated the wiki page.

**Comment by redboltz** [comment]
If you still has problem, feel free to reopen it.
