### ISSUE TITLE
Reconnect

### ISSUE THREAD

**Issue by ineffective** [redboltz/mqtt_cpp#526]
I wonder how you manage reconnects and retry connecting to the server when it is down. I could try to call `client->connect()` repeatedly ( I mean after io.run() exits, call c->connect() and io.run() again), but it doesn't seem very elegant. So maybe I should check for error `connection refused` (or other similar) in error handler and then set timer that would call `c->connect()` again? Or maybe there is some other option? I had traumatic past experiences with timers and boost::asio but maybe it is best to try and reconcile now?

**Comment by ineffective** [comment]
And also one more question. Assuming that I don't readily have access to io_context that the client object uses, can I retrieve it somehow from it?

**Comment by redboltz** [comment]
It is currently changing. Which version of mqtt_cpp are you using ? v7.0.0 or master ?

**Comment by redboltz** [comment]
> So maybe I should check for error connection refused (or other similar) in error handler and then set timer that would call c->connect() again? 

What kind of error are you asking ? Underlying network error before MQTT connection is established or after MQTT connection is established?

**Comment by ineffective** [comment]
> > So maybe I should check for error connection refused (or other similar) in error handler and then set timer that would call c->connect() again?
> 
> What kind of error are you asking ? Underlying network error before MQTT connection is established or after MQTT connection is established?

It doesn't matter, I can simply check what I receive when and then check for them. This is not a problem.

> It is currently changing. Which version of mqtt_cpp are you using ? v7.0.0 or master ?

v7.0.0, pulled from tag v7.0.0. I *could* use master, but I hoped for some stability so that we could start developing. On the other hand it would take some time before we are finished, so maybe this is not a problem right now.

**Comment by redboltz** [comment]
## In v7.0.0, 
call `connect()` from close or error handler. You can directly call it but usually set `boost::asio::deadline_timer` and call `connect()` from timer handler.

## In master, 
if MQTT connection is established, then call `connect()` from close or error handler. 

If MQTT connection is not established (that mean underlying network error), then call as follows:

* sync_client
  * If you use `connect()` with `boost::system::error_code& ec`, then check ec and call `connect()`.
  * If you use `connect()` without `boost::system::error_code& ec`, then catch exception and call `connect()`.
* async_client
  * You can use only `async_connect()`. It has `async_handler_t` as the parameter. You can call `async_connect()` from the handler.

**Comment by redboltz** [comment]
> I mean after io.run() exits, call c->connect() and io.run() again

If you use the approach above I commented, `io.run()` is never finished.

**Comment by ineffective** [comment]
> > I mean after io.run() exits, call c->connect() and io.run() again
> 
> If you use the approach above I commented, `io.run()` is never finished.

Yes, that's true. It is because timer handler is still pending. But it will be pending only if i post it on io_context. And my problem is that if I don't have io_context used for client initialization at hand (for example I am in different file and in different context, I don't see any way to obtain it from the client. In short I don't see any way to get io_context from the client - is that true?

I checked API documentation and failed to find it. It doesn't mean that there is no such way, is that there is no simple way to do it I think. Once again, I'm on v7.0.0.

**Comment by jonesmz** [comment]
So you're just looking got a "get_io_context()" member function?

**Comment by ineffective** [comment]
I am looking for both solution, which i got, and grt io context member.

Sorry for a mess, I answer from phone using email.

**Comment by jonesmz** [comment]
@ineffective I would love to see a pull request from you that adds a `get_io_context()`, or `io_context()` public member function to endpoint.hpp. It should only be about 5 lines of code, and should take approximately 15 minutes.

Up for it?

**Comment by ineffective** [comment]
No problem i think, but i'll be unable to do it before monday
unfortunately. If it is  still actual by that time i, ll gladly do it.

**Comment by redboltz** [comment]
I understand what the problem is.

I thought that you can get `io_context` as follows:

```cpp
    auto c = MQTT_NS::make_sync_client(ioc, argv[1], argv[2]);
    auto&ioc = c->socket()->get_io_context();
```

But I noticed that it outputs a compile error.
I need to fix tcp_endpoint.hpp and ws_endpoint.hpp, then you can call as follows:

```cpp
    auto c = MQTT_NS::make_sync_client(ioc, argv[1], argv[2]);
    auto exe = c->socket()->get_executor();
    boost::asio::deadline_timer tim(exe);
```

See 
https://www.boost.org/doc/libs/1_71_0/doc/html/boost_asio/reference/basic_stream_socket/get_executor.html
https://www.boost.org/doc/libs/1_71_0/doc/html/boost_asio/reference/basic_stream_socket/executor_type.html
https://www.boost.org/doc/libs/1_71_0/doc/html/boost_asio/reference/basic_deadline_timer/basic_deadline_timer.html

I'm still not sure why executor_type is copyable and why `get_executor()` returns value type. Also I'm not sure user needs to manage gotten executor lifetime or not. I guess user doesn't need to manage it. I guess that executor_type has the pointer io_context internally. 
Anyway I need to time for investigation.

**Comment by redboltz** [comment]
>  Also I'm not sure user needs to manage gotten executor lifetime or not. 
> I guess user doesn't need to manage it.

It's true.

>  I guess that executor_type has the pointer io_context internally.

It's wrong. Old io_service became to io_context. And io_context has executor. Some of responsibilities are moved into executor. You can create deadline_timer using executor. And executor is copyable.

**Comment by redboltz** [comment]
@ineffective , could you try #528 ?

**Comment by redboltz** [comment]
Now, you can also call a wrapped function as follows:

```cpp
    auto exe = c->get_executor();
```

**Comment by ineffective** [comment]
Hi, I see that it is still opened and scheduled for v8. From my perspective everything works fine so it seems that this issue can be closed.
