### ISSUE TITLE
Roadmap/versioning

### ISSUE THREAD

**Issue by ineffective** [redboltz/mqtt_cpp#529]
There is a change that I'm interested in, namely #526. Will it make into some new version of v7.x.x or will it be part of v8.x.x?

I ask because I'd like to have some version number that I'll be able to target in our own software. mqtt_cpp is *the* library that we will use, as it seems quite mature, performant and easy to use, the only thing I miss is some API/versioning stability. Currently this part seems somewhat neglected, page [releases](https://github.com/redboltz/mqtt_cpp/releases) has v.7.0.0 as last version, [wiki](https://github.com/redboltz/mqtt_cpp/wiki/News) mentions 6.0.2 as last release and I see [here](https://github.com/redboltz/mqtt_cpp/projects) that v7.x is basically ready and v8.x in the making.

None of the latter pages mentions #526 or #528 (merge of #526) as part of it.

**Comment by redboltz** [comment]
I will update wiki and related pages later. 
The project page is not well maintained, so far.

Let me explain the current status. 

Here is the release policy:

The latest release is v7.0.0. 
Until breaking change is merged, then master is for v7.x.
If a breaking change is merged, then master is for v8.0.0. The current master is for v8.0.0. (Version text should be updated but not done yet.)

If a serious bug is reported and fixed then the fix will be backported to v7.x.
#526 and #528 are for v8.0.0.

**Comment by redboltz** [comment]
Updated https://github.com/redboltz/mqtt_cpp/wiki/News.
Added https://github.com/redboltz/mqtt_cpp/wiki/Versioning-Policy.
Send #533. It is for updating README.md. It doesn't mean v8.0.0 will release immediately.

**Comment by ineffective** [comment]
Thanks, this answers my questions. Have you considered merging small fixes into older releases? I'm not sure how viable it is, I *think* that this would cause problems only if client/server was exposed directly from .so/.dll, but I might be wrong.

**Comment by jonesmz** [comment]
mqtt_cpp offers no ABI stability. As a header only library, the only stability it offers on non-major releases is end-user API stability.

**Comment by jonesmz** [comment]
Sure, I don't see why not.

@redboltz has been very responsive on accepting PRs from me. He and I have seriously evolved the codebase over the last 6 months since I discovered it and started using it for my current work project.

**Comment by redboltz** [comment]
> Which means that if I wanted to backport to e.g. v7.x.x something that only enhances API and does not break it and I'd provide patch/merge request then it will be likely accepted?

I just pushed `v7.x` branch for backporting. You can create PR for the branch.

**Comment by ineffective** [comment]
Thanks, I will look through differences between these branches and try to prepare a PR.
