### ISSUE TITLE
Removing the "acquired_***" version of functions

### ISSUE THREAD

**Issue by jonesmz** [redboltz/mqtt_cpp#534]
I think we should remove the "acquired_***" functions.

Instead, what we should do is have `acquire_unique_packet_id()` return an opaque type that can only be constructed by either `acquire_unique_packet_id()` or `register_packet_id()`.

Then, the overloads of the existing end-user API functions would either have no packet_id, and therefore internally call `acquire_unique_packet_id()`, like we do now, or the end-user must call register_packet_id() in order to get a packet_id object (which they can't construct themselves, as noted before).

Making this change would allow us to eliminate >30 different functions, while also reducing the situations where end-users can misuse the library.

Note: I also think that we should separate the packet_id algorithm from the endpoint class, as detailed here: https://github.com/redboltz/mqtt_cpp/issues/223

**Comment by redboltz** [comment]
I don't understand what you mean yet.
acurired_* version is required to reserve packet id. It is heavily used on my broker.
Maybe you don't say just remove them but I can't imagine updated code.
I need code example.

**Comment by redboltz** [comment]
My usecase is

1. packet_id = acquire_unique_packet_id()
2. store packet_id to DB
3. acuired_***(packet_id)

If broker is down between 2 and 3 then,

1. reboot broker (with clean memory)
2. read stored packet_id from DB if it exists
3. register_packet_id(packet_id)
4. acuired_***(packet_id)

It is a part of exactly once message delivery across broker (cluster) process is down.

**Comment by jonesmz** [comment]
There are three end-user api function versions for each message that uses packet_id.

e.g. subscribe.

```cpp
subscribe(...);
subscribe(packet_id, ...);
acquired_subscribe(packet_id, ...);
```

I'm saying to do this;

```cpp
using packet_id = /* some type that can only be constructed by struct endpoint. Has integer packet id internally, has const getter for numeric representation. */

packet_id register_packet_id(...); // Gets packet id object based on the provided id number. Throws exception on failure, or takes reference to boost::system::error_code, or whatever failure mechanism.
packet_id acquire_unique_packet_id(...); // Gets packet id object guaranteed to not overlap with any existing packet ids. Used by end-user only if they need to know the packet id ahead of time.

subscribe(...); // endpoint gets packet id automatically.
subscribe(packet_id, ...); // end-user must get packet id themselves. Neither version returns the packet id, because that would interfere with the concept of completion tokens from https://github.com/redboltz/mqtt_cpp/issues/523
```

Having packet_id be a type that can only be constructed by `struct endpoint` makes this safe. End-users can't accidentally provide bad packet_id to packet_id version of function. They *must* call either `acquire_unique_packet_id()` or `register_packet_id()`, or call non-packet_id version of function.

For your code you would do:
```cpp
packet_id = acquire_unique_packet_id()
store packet_id to DB
subscribe(packet_id, ...)
If broker is down between 2 and 3 then,

reboot broker (with clean memory)
read stored packet_id from DB if it exists
packet_id = register_packet_id(packet_id_number)
// check failure here
subscribe(packet_id, ...)
```

The difference is that `acquired_***(...)` is renamed as `***(packet_id)`, and replaces the existing version of `***(packet_id)`. End-user can no longer just call function with numeric packet_id and have it auto-registered.

Benefits:

1) Removes >30 functions from mqtt_cpp, significant reduction in code size.
2) Easier to do https://github.com/redboltz/mqtt_cpp/issues/523 (Because CompletionToken specifies return type)
3) Easier for end user to not make mistakes. Their choices go from 1) automatic packet id 2) half-automatic packet id, 3) manual packet_id. -> 1) automatic 2) manual. No half-automatic. Since doing half-automatic is only one function call, they can do that easily.

**Comment by redboltz** [comment]
Ok, you mean remove 

```cpp
bool subscribe(packet_id_t packet_id, ...);
```
that calls `register_packet_id(packet_id)` internally.

And rename from

```cpp
void acquired_subscribe(packet_id_t packet_id, ...);
```

to

```cpp
void subscribe(packet_id_t packet_id, ...);
```
.

If I understanding correctly, that's fine.

**Comment by jonesmz** [comment]
Yes. Correct.

And also provide type-safety, to prevent accidental misuse.

**Comment by uecasm** [comment]
Correct me if I'm wrong, but #547 does not include the "type safety" part (changing the type of `packet_id_t` to prevent implicit construction from integers) that was mentioned above.... was that intended?

**Comment by jonesmz** [comment]
Redboltz was opposed to changing the api such that the packet id *must* be acquired ahead of time by the end user, so I did not add changes to prevent implicit construction to avoid the api break.
