### ISSUE TITLE
acquire_unique_packet_id / acquire_publish -> "packet_id exhausted error"

### ISSUE THREAD

**Issue by ineffective** [redboltz/mqtt_cpp#540]
I publish messages using the following (partial) code:

```c++
auto pid = client_->acquire_unique_packet_id();
client_->acquired_subscribe(pid, topic, MQTT_NS::qos::exactly_once);
```
After sending 65k messages exception `packet_id_exhausted_error` is thrown for each message that I try to send. I publish ~2k messages per minute (using `MQTT_NS::qos::exactly_once` as you can see above).

My understanding was that if I call `acquired_publish()` with packet id that I got from `acquire_unique_packet_id` then it is automatically passed to `release_packet_id`, since library takes ownership of this packet_id and I don't have to do it. But it doesn't seem to be the case, `release_packet_id` is mentioned in source code only three times, one of them is method declaration and other two are in comments.

I tried simply publishing messages without using `acquired_***` methods, but I still get `packet_id_exhausted_error`.

So what should I do to get "proper" behaviour, that is reuse of ids? Should I call `release_packet_id` on my own? But if answer is yes, then what does it mean that library takes ownership of packet id? And if I should use `release_packet_id` then how do I know if I should call it in pubrec_handler (for messages with `qos` less than `exactly_once`) or in `pubcomp_handler` (that is function/method/lambda registered via set_pubcomp_handler`)?

I use synchronous client, but I suppose that the same thing happens with asynchronous one.

**Comment by andybayer** [comment]
Hello,

my colleague had a similar problem publishing with qos::exactly_once. I also have this problem. I just wanted to open an issue but saw that you have the same problem. 

It looks like packet ids are not released when receiving pubcomp. Executing`const auto success = client->release_packet_id(id);` within the client's pubcomp_handler seems to solve this (as long as you don't have over 65k messages in flight).

I searched the source code a bit and found this suspicious snippet in v7.0.0:
https://github.com/redboltz/mqtt_cpp/blob/9a63149965556bc5c16da3a974b9544e04acff5a/include/mqtt/endpoint.hpp#L10255-L10279

Seems like this is a small copy paste error from pubrec_phase::finish? Cause the packet_id is erased within the puback handler and this issue happened only with qos 2 but not with qos 1.
https://github.com/redboltz/mqtt_cpp/blob/9a63149965556bc5c16da3a974b9544e04acff5a/include/mqtt/endpoint.hpp#L9777-L9800

But I have to admit that I only read small parts of the code.

**Comment by ineffective** [comment]
I modified `pubcomp_handler` so that now it releases packet_id:

```c++
client_->release_packet_id(packet_id);
```
and everything works find. I wonder why it doesn't work automatically when I use automatic packet_id manager.

Still it isn't obvious how to determine whether `release_packet_id` can be safely called - are all handlers always called and are called in predetermined order and only once? And also how to determine that packet_id was acquired using `acquire_unique_packet_id`.

**Comment by redboltz** [comment]
@ineffective , @andybayer , thank you for reporting the issue.

On puback, ` packet_id_.erase(info.packet_id);` is called. It is the same effect as `release_packet_id()`. It is right code.
https://github.com/redboltz/mqtt_cpp/blob/7d4ac58462112558e349b5b1d5e7f796f76550c5/include/mqtt/endpoint.hpp#L9404-L9413

On pubrec, the packet_id in the container `packet_id_` is not erased. It is expected.
https://github.com/redboltz/mqtt_cpp/blob/7d4ac58462112558e349b5b1d5e7f796f76550c5/include/mqtt/endpoint.hpp#L9549-L9557

However, on pubcomp, ` packet_id_.erase(info.packet_id);`  should be called but not called.
https://github.com/redboltz/mqtt_cpp/blob/7d4ac58462112558e349b5b1d5e7f796f76550c5/include/mqtt/endpoint.hpp#L9882-L9892

I will fix it.

**Comment by redboltz** [comment]
@ineffective , user doesn't need to call `release_packet_id()` manually if you call `acqruired_*()` APIs. If you don't call `acqired_*()` APIs some reason, then yo need to call `release_packet_id()` to cancel.

**Comment by redboltz** [comment]
Just created PRs.

* #541 is fix for master
* #542 is fix for v7.x.

Could you try this? No manual `relased_packet_id()` is required.

**Comment by andybayer** [comment]
Seems to work for me. Thank you for your very fast response.

**Comment by ineffective** [comment]
Great, it seems to work without problems, both when I call `acquire_unique_packet_id` and when I just send messages without it. 

One question though: could you describe scenario when using `acquire_unique_packet_id` would be required?

**Comment by jonesmz** [comment]
The acquire_ version of the api is used when the end user guarantees that the packet Id provided is acceptable (e.g. unique).

The acquire_ version of the api is going away in the master branch as soon as I finish writing the pull request. See https://github.com/redboltz/mqtt_cpp/issues/534

**Comment by ineffective** [comment]
Yes, I am aware of that, this is one of the reasons why I asked if it is
used at all by the clients. I understand from discussion under #534 that
there is no need for that whatsoever in the client and only server would
use that?

**Comment by jonesmz** [comment]
Ah, I misread your original question.

You would use `acquire_unique_packet_id` when you want to know the packet id that's going to be used prior to the creation / sending of the mqtt message.

For example, imagine you have a clustered mqtt broker, that has multiple instances of the mqtt-broker process running, and coordinating with itself using some unspecified cluster technology (e.g. custom network protocol, or corosync, or a database backend, so on).

You would want to ensure that your cluster doesn't use the same packet id twice at the same time, 
 when generating an outgoing mqtt message. So you would "acquire" the packet id, and the `acquire_unique_packet_id` function would need to use your application specific coordination mechanism to lock that packet id for all instances, before you send.

You should not need to use `acquire_unique_packet_id`, or even really `register_packet_id` in client code. 

That being said, if you want to implement the more advanced publish behavior, such as journaling the packets you've received into a local database, before sending the ACK, so that your message can survive a crash, you can use those two functions (and the various customization points for them) to do so.

In my code, I've structured my MQTT protocol usage such that I don't care if my application crashes and restarts. But everyone's application is different :-)

**Comment by ineffective** [comment]
@jonesmz Thank you, this is what I wanted to know.

**Comment by redboltz** [comment]
It was a serious bug so I've merged the fix not only master but also v6.x and v7.x branches, then released them. See https://github.com/redboltz/mqtt_cpp/wiki/News

**Comment by ropieur** [comment]
I saw that this bug affects QoS2 messages only. As I've been faced to the same issue but I use only QoS0 and QoS1, I am wondering whether this bug could also affect QoS1 messages.
