### ISSUE TITLE
acquire_unique and register_packet_id should assume an async implementation

### ISSUE THREAD

**Issue by jonesmz** [redboltz/mqtt_cpp#546]
By this, I mean that the function signatures should take a CompletionToken, (Most commonly a callback function that accepts a MQTT_NS::error_code)

To implement a Clustered MQTTv5 broker using mqtt_cpp, the packet id registration family of functions would need to be asynchronous, because they will use network traffic, and therefore may not complete promptly.

**Comment by redboltz** [comment]
I'm not sure why packet_id allocation/registration requires network traffic (access).
Could you elaborate this?

Packet id is unique on each client/broker and direction.
Direction means client1 publishes to client2 using packet_id 1 and client2 publishes to client1 using packet_id1 is allowed.

Packet id allocation is simple process it requires at most 0xffff times loop in the worst case. The normal case is usually O(log 0xffff).

**Comment by jonesmz** [comment]
It may be async because the packet Id is synchronized across multiple instances using an external database.


The current implementation can be implemented using an async "interface" that immediately calls the completion token. But the current interface cannot be used for an async operation.

Assuming async operation allows end user full flexibility to implement packet I'd any way

**Comment by redboltz** [comment]
Do you mean packet_id should be unique across multiple brokers? And in order to do that, the packet_id creator is shared database?

**Comment by jonesmz** [comment]
That is one example, yes.

Or imagine a database api. Such as sqlite, but async. It would be local, but to avoid blocking the process on disk access, the api is async

**Comment by jonesmz** [comment]
I'm not saying that end users SHOULD implement globally unique packet id for multiple brokers. I'm just saying we are restricting end user options.

**Comment by redboltz** [comment]
I think that packet_id should be locally unique. It is MQTT philosophy I believe. 16 bit is too small to globally unique.

It seems to relate to #547, `acquire_unique_packet_id()` is called internally.
We need to keep the original (sync) version, and if you want to add async version (overload?), it is no problem. Actually, it may increase end user option. I agree this point.

**Comment by redboltz** [comment]
Thanks to #778, packet_id allocation became extremely fast. So we don't need async operation.
