### ISSUE TITLE
async_client has disconnect() method marked as deleted

### ISSUE THREAD

**Issue by thoism** [redboltz/mqtt_cpp#549]
I noticed that the `async_client.disconnect()` method is marked as deleted. What is the actual reason behind this?

As it seems this gives me the only option of disposing the client as a disconnection mechanism or I am missing something.

Thank you

**Comment by jonesmz** [comment]
Use async_disconnect()

**Comment by jonesmz** [comment]
@thoism 

Are you in good shape now?

**Comment by thoism** [comment]
thanks!
