### ISSUE TITLE
add Github Actions CI service

### ISSUE THREAD

**Issue by jonesmz** [redboltz/mqtt_cpp#550]
Supports 20 concurrent jobs, and supports Mac OS.

Might be worth trying.

Here's a work-in-progress script.

https://github.com/jonesmz/mqtt_cpp/blob/github-ci/.github/workflows/continuous-integration.yml

Currently, I'm having problems with boost on the ubuntu image. The BOOST_ROOT and BOOST_ROOT_1_69 environment variables are set, but the directory they point to doesn't exist.

I've opened a support case with github to ask what's going on.

A work around might be to install boost via apt, and then change the value of BOOST_ROOT to point to the new one.

**Comment by redboltz** [comment]
Currently, osx builds are bottle neck. It seems to be a good solution.
Unfortunately, I'm extremely busy in this month to arrange a tech show.
I will check it later.

**Comment by redboltz** [comment]
I started trying Github Actions. At first, it worked well. But when I tried to implement the same behavior as travis-ci, I've been stuck.

It seems that I'm facing this issue.
https://github.community/t5/GitHub-Actions/GitHub-Actions-Matrix-options-dont-work-as-documented/td-p/29558

I cannot place `FLAGS`, `CXXFLAGS`, and so on at the include entry. 
https://github.com/redboltz/mqtt_cpp_github_actions/blob/cb983e19e43a393db00690d95ad90c078e6d548b/.github/workflows/gha.yml#L13

I guess that Github Actions **include** is different from travis-ci's one.
travis-ci's **include** is adding variables. But Github Actions **include** is **filtering** variables. That means I need to prepare all vector of candidate values.

**Comment by redboltz** [comment]
I found one solution. It is not elegant but work.
https://github.com/redboltz/mqtt_cpp_github_actions/blob/ddbbfc84c122b0522210e5b4124880fbebc5359d/.github/workflows/gha.yml#L12
(Only implemented osx build)

**Comment by redboltz** [comment]
https://github.com/redboltz/mqtt_cpp_github_actions/runs/330806655

Now, I achieved that the same tests as travis-ci except codecov. I will add codecov support.

Github Actions each task time limit is 6 hours. It is longer that travis-ci's 50 minutes.
In order to optimize CI time, I will update the number of osx task to 5 from 7. 5 means osx parallel build limit. It can be achieved remapping tests.

**Comment by redboltz** [comment]
Fixed by #553. For codecov, I use github secret and access `secrets.CODECOV_TOKEN` in the gha.yml.
