### ISSUE TITLE
Clean Session vs Session Present

### ISSUE THREAD

**Issue by BillPlunkett** [redboltz/mqtt_cpp#567]
It seems like the following line of code in (from tls_client, in this case):
            std::cout << "Clean Session: " << std::boolalpha << sp << std::endl;

Should really be:
            std::cout << "Session Present: " << std::boolalpha << sp << std::endl;

I'm using AWS IOT and reading from https://docs.aws.amazon.com/iot/latest/developerguide/mqtt-persistent-sessions.html

**Comment by redboltz** [comment]
Thank you for reporting the issue. Yes, it should be fixed.

**Comment by redboltz** [comment]
Fixed by #580
