### ISSUE TITLE
tls_client example and set_keep_alive_sec_ping_ms()

### ISSUE THREAD

**Issue by BillPlunkett** [redboltz/mqtt_cpp#573]
I'm testing with the tls_client example and have modified as follows:

```C++
    // Setup client
    c->set_client_id("cid1");
    c->set_clean_session(false);
    c->get_ssl_context().load_verify_file(cacert);
    c->get_ssl_context().use_certificate_chain_file(devcert);
    c->get_ssl_context().use_private_key_file(privkey, boost::asio::ssl::context::file_format::pem);
    c->set_keep_alive_sec_ping_ms(1200, 10*1000); // still get EOF errors with this - only a single ping req sent?

    // Setup handlers
    c->set_pingreq_handler(
        [&]
        ()
        {
          std::cout << "pingreq_handler" << std::endl;
          return true;
        });
    c->set_pingresp_handler(
        [&]
        ()
        {
          std::cout << "pingresp_handler" << std::endl;
          return true;
        });

```

I'm seeing only a single callback to the ping response handler and so the server (AWS in this case) disconnects the client after 10 minutes.  I also see no callbacks to the ping request handler; maybe I'm misunderstanding that part?

Setting breakpoints in client.hpp, I see that handle_timer() is called just once, as if an additional call to tim_ping_.expires_from_now() is required.

**Comment by jonesmz** [comment]
It wouldn't be tim_ping_.expires_from_now by itself, you'd also need a new async_wait.

Probably what's happening here is that the ping timer is based on the "on_pre_send()" function, which re-triggers the timer, and it looks like "callable_overlay" does not call the base-class implementation of on_pre_send().

Can you modify callable_overlay.hpp line 710 to call the base implementation of on_pre_send() if-and-only-if the callback function is not defined? Similar to how "on_mqtt_message_processed()" is done on line 730.

**Comment by BillPlunkett** [comment]
That suggestion works when base::on_pre_send() is called unconditionally; same behavior as before when the callback function is defined (which is evidently the case with the tls_client example).

To be clear, only when I modify callable_overlay.hpp as shown below, I see multiple calls to the ping response handler:

```C++
    MQTT_ALWAYS_INLINE void on_pre_send() noexcept override final {
        /*if(h_pre_send_) h_pre_send_();
        else*/ base::on_pre_send();
    }
```

**Comment by BillPlunkett** [comment]
The following also appears to work, though I'm a bit over my head in making such a change:

```C++
    MQTT_ALWAYS_INLINE void on_pre_send() noexcept override final {
        base::on_pre_send();
        if(h_pre_send_) h_pre_send_();
    }
```

**Comment by jonesmz** [comment]
```cpp
    MQTT_ALWAYS_INLINE void on_pre_send() noexcept override final {
        if(h_pre_send_) {
            h_pre_send_();
        }
        else {
            base::on_pre_send();
        }
    }
```

Does not work for you?

Are you installing a callback for on_pre_send in your code?

**Comment by jonesmz** [comment]
E.g. are you calling this function?

set_pre_send_handler

**Comment by BillPlunkett** [comment]
I am not

**Comment by jonesmz** [comment]
> I am not

Then
```cpp
     MQTT_ALWAYS_INLINE void on_pre_send() noexcept override final {
        if(h_pre_send_) {
            h_pre_send_();
        }
        else {
            base::on_pre_send();
        }
    }
```

Should work for you.

The only difference here is the check for whether the callback is initialized to something non-null.

**Comment by BillPlunkett** [comment]
Sorry, Pilot error here.  Your original suggestion *does* work.  However, there is an issue with client::on_pre_send() being marked private.  To get around that, I resorted to this:

```C++
public:
    void on_pre_send() noexcept override
    {
        if (ping_duration_ms_ != 0) {
            reset_timer();
        }
    }
private:
```

**Comment by jonesmz** [comment]
We should just make the function in client.hpp non private.

Protected should be perfectly fine.

Are you still interested in making a PR?

**Comment by BillPlunkett** [comment]
Yes.  I will do that.  Thanks!

**Comment by redboltz** [comment]
I understand the issue. Thank you for reporting.
It is caused by some mistake when we introduce callable_overlay mechanism.

In order to fix the issue, I need to consider following things.

* `endpoint` provides pre_send_handler setting mechanism.
* `client` uses it for resetting timer.
*  pre_send_handler setting mechanism is not only for `client`.
* `client` user (application code) might want to use pre_send_handler setting mechanism.
* In the case above, resetting timer should be remained.
* The same pattern could be existed other handlers (not only pre_send_handler)

I need to check those things.
Please wait a moment.

**Comment by redboltz** [comment]
I've checked.
`client` overrides not only `on_pre_send()` but also `on_close()` and `on_error()`.
In `on_close()` and `on_error()`, the client cancels timer if it is set.

They need to similar care as `on_pre_send()`.
