### ISSUE TITLE
Getting TLS peer certificate

### ISSUE THREAD

**Issue by uecasm** [redboltz/mqtt_cpp#575]
If I've made a TLS broker server along the lines of [tls_server.cpp](https://github.com/redboltz/mqtt_cpp/blob/master/example/tls_server.cpp)...

First, it appears that these examples are a bit outdated and only support v3 or v5 but not both (although they can be combined to support both).  And they appear to be missing support for some apparently necessary things (eg. #502 recommended adding pingreq handlers).

Is [test_broker.cpp](https://github.com/redboltz/mqtt_cpp/blob/master/test/test_broker.hpp) a better example to base a new broker on instead?

But anyway, the _real_ question is: from an accept (or connect) handler (when I know that the underlying connection is a TLS stream), how do I get the peer client certificate?  My use case requires validating the MQTT CONNECT against information in that certificate.

I've combed through the Boost.Asio docs and as far as I can tell the only method is to call `SSL_get_peer_certificate(sslstream.native_handle())` directly.  However I'm not sure how to get at the `sslstream`, given the `server_tls<>::endpoint_t` passed to the accept handler.

`ep.socket()` returns an `mqtt::socket`, but that's some kind of type-erased thing and not the underlying `as::ssl::stream<as::ip::tcp::socket>` (buried somewhere in `mqtt::server_tls<>::socket_t`), which is what I need to get at.

**Comment by uecasm** [comment]
Mostly as an exercise, https://github.com/uecasm/mqtt_cpp/commit/3105c02 was an attempt to add `native_handle` to `mqtt::socket`.

It doesn't work (or compile).  I don't really know what I'm doing with Boost.TypeErasure -- in particular how to tell it that `native_handle()` returns `T::native_handle_type` (which is different types).  Or if that's even possible.  (The [TypeErasure docs](https://www.boost.org/doc/libs/1_72_0/doc/html/boost_typeerasure/concept.html) seemed to suggest that it might be, however.)

**Comment by redboltz** [comment]
Thank you reporting the issue.
Do you want to do client certification authentication on server side?

I don't check the problem deeply but I guess that there are two possible approaches.

Both requires mqtt_cpp modify.

### Approach 1
The socket in `endpoint` is type erased. So we need to add extracting function to get native socket. It is just you trying approach.

### Approach2
Add client certification authorization mechanism on server.hpp before the type is erased.

I don't have much time now so those approach is just idea. I'm not sure it is possible.
I'm doing other issue and pull requests on mqtt_cpp. After finished them, I will take a look the issue.

**Comment by uecasm** [comment]
No, it's not client certificate authentication -- that can already be done in a handler on the ``ssl::context`.  But the context handler is agnostic of a particular client socket.

What I'm trying to do is that after SSL has successfully completed client certificate authentication and the MQTT CONNECT is being processed, I want to look up some data from the client certificate that was presented earlier and compare it with the MQTT client id and username.

Having access to `asio::ssl::stream::native_handle()` would suffice for that.

**Comment by uecasm** [comment]
Well, it looks like https://github.com/uecasm/mqtt_cpp/commit/a0d7c747f1adf57f4f75c85e63140620f03fb51e works, although it makes use of `boost::any` as the return type, which isn't ideal.  (But maybe that's the best we can do in a type-erased context?)

Given this, the peer certificate can be extracted with:

    auto cert = SSL_get_peer_certificate(boost::any_cast<SSL*>(ep.socket().native_handle()));

(I can turn it into a PR if you like, although I'm not sure if it's complete.  Or the right way to do it.)

**Comment by redboltz** [comment]
I guess that websocket support is required.
I wrote #577. Could you check this?

The return value type any is the best choice.
I use `any`. That means `MQTT_NS::any`. It is `std::any` or `boost::any` depend on compile option (or cmake option), the default is `boost::any`.

**Comment by uecasm** [comment]
#577 seems to work ok.

Although (since upgrading from 7.0.1) the new `dup`/`retain` enums seem more annoying (and error prone) than the bools.  Also there's a copy/paste error in `dup_to_str`.  And ideally `is_dup` etc shouldn't duplicate the bitmasks.

**Comment by redboltz** [comment]
> #577 seems to work ok.

Thanks, I close the issue.

Please don't write unrelated topic. If you have some issue, create new one
