### ISSUE TITLE
New publish_options

### ISSUE THREAD

**Issue by uecasm** [redboltz/mqtt_cpp#578]
As mentioned in #575:

Since upgrading from 7.0.1 to master, the new `dup`/`retain` enums seem more annoying (and error prone) than the bools.  Also there's a copy/paste error in `dup_to_str`.  And ideally `is_dup` etc shouldn't duplicate the bitmasks.

(It also seems inconsistent that the `qos` enum values are the non-bit-shifted values and the `dup`/`retain` enum values are the shifted values.  Or vice-versa, depending on perspective.)

**Comment by jonesmz** [comment]
The mqtt standard does not keep consistent positioning of the individual bits for each of the different message types, so we have to shift the QOS value in some cases, we don't have a choice.

Please open a PR for dup_to_str.

Can you elaborate on the is_dup function?

**Comment by jonesmz** [comment]
The reason for using enums for these is to provide better type safety, and remove ambiguity in the API of the library. 

In fact, I found several places where I had flipped the order of retain / dup in my own client code when I changed things to be enums. In my opinion, the additional type safety is overwhelmingly more important than the extra verbosity.

I'm certainly open to discussing it more though, if you'd like to.

**Comment by uecasm** [comment]
It looks like `dup_to_str` has just been fixed by 872cd3a92.

Regarding `is_dup`, what I meant is that the bitmask that represents the dup bit is repeated in all of `is_dup`, `set_dup`, and `enum class dup`.  It really should only be in one place.  In fact it seems peculiar that these free functions aren't implemented just by calling `publish_options` methods.  I can't see any reason why they couldn't be.

Regarding the bit-shifting, this is the part I meant:
https://github.com/redboltz/mqtt_cpp/blob/82bbc9b9702e851c102bde142a3faa01b9a20343/include/mqtt/publish.hpp#L62-L64

The `qos` enum values are pre-shifted so that QoS 1 is enum value 1, which then requires shifting them to the "correct" spot when building a `publish_options`, and shifting back when extracting the value:
https://github.com/redboltz/mqtt_cpp/blob/82bbc9b9702e851c102bde142a3faa01b9a20343/include/mqtt/publish.hpp#L79-L84

Meanwhile the `dup` and `retain` enums instead contain the post-shifted value as already present in the `publish_options` byte.

Either one of these is ok (although I personally prefer the way that `qos` is implemented, since it means that only `publish_options` needs to know about the bitmasks), but mixing the two together seems like inconsistent and bad design.

(Technically, I suppose, that means that `dup` is ok and it's only `retain` that's "wrong".)

**Comment by uecasm** [comment]
I can make a PR for my suggested consistency improvement, if you like.

**Comment by jonesmz** [comment]
Please make a PR for the is_dup change.

The reason that it is this way is because the enums were added after the free standing functions.

You're welcome to provide a patch to always use the publish_options class instead.

**Comment by jonesmz** [comment]
The reason why qos is bit-shifted in the publish_options type but the others are not is because the qos enum is shared between publish_options (publish.hpp) and subscribe_options (subscribe_options.hpp). 

The MQTT Standard doesn't keep a consistent bit pattern for the QOS concept between the publish packet and the subscribe packet.

But I agree it's annoying. I'd love to not have it bit-shift like that.

Do you have a suggestion ?

**Comment by jonesmz** [comment]
@uecasm Is this still a concern for you?
