### ISSUE TITLE
increase minimum boost requirement from 1.66 to 1.67

### ISSUE THREAD

**Issue by redboltz** [redboltz/mqtt_cpp#586]
I have a problem with boost 1.66.

This code works well with the combination of C++14 and boost 1.66.
https://wandbox.org/permlink/fsKdnstRM9J9MizT

```cpp
#include <iostream>
#include <boost/variant.hpp>

inline void sink(std::unique_ptr<int>&&) {
    std::cout << "sink" << std::endl;
}

struct visitor_for_boost : boost::static_visitor<int> { // add static visitor inheritance for return type
    visitor_for_boost(std::unique_ptr<int>&& up):up(std::move(up)) {}
    int operator()(int v) const { // const is required
        sink(std::move(up));
        return v;
    }
    mutable std::unique_ptr<int> up; // mutable is required for move operation in the const function
};

int main() {
    auto up {std::make_unique<int>(42)};
    boost::variant<int> v = 1;
    boost::apply_visitor(visitor_for_boost(std::move(up)), v);
}
```

I want to move the variable to the visitor class and move it somewhere in `visitor::operator()()`.
However, boost 1.66 requires `boost::static_visitor<int>` and if I inherit it, the `visitor::operator()()` need to be const. So I need to declare up as mutable. It is unnatural.

Here is the result that I remove const and mutable:
https://wandbox.org/permlink/O0BH43RIKRQrsGCS

If I update boost to 1.67, then I can write the following natural code.

```cpp
#include <iostream>
#include <boost/variant.hpp>

inline void sink(std::unique_ptr<int>&&) {
    std::cout << "sink" << std::endl;
}

struct visitor_for_boost {
    visitor_for_boost(std::unique_ptr<int>&& up):up(std::move(up)) {}
    int operator()(int v) {
        sink(std::move(up));
        return v;
    }
    std::unique_ptr<int> up;
};

int main() {
    auto up {std::make_unique<int>(42)};
    boost::variant<int> v = 1;
    boost::apply_visitor(visitor_for_boost(std::move(up)), v);
}
```

https://wandbox.org/permlink/n2jXW3VYiKPinIfB

I no longer need to inherit `boost::static_visitor<int>` (return type is deduced since C++14 but boost 1.66 doesn't seem to use it yet).

So I want to update to boost 1.67.

**Comment by jonesmz** [comment]
As far as I'm aware, boost 1.67 should be fine for me. So I have no objection.

However, please be aware that the platform that I'm deploying to (OpenWRT 18.06) has boost 1.67. So if we push the minimum version higher than that, I'm going to have difficulties continuing to use the master branch.

I'm working on getting access to newer boost though, so this won't be a problem for me forever.

**Comment by redboltz** [comment]
Thank you for the comment. I will update to 1.67.
I am aware that you are using 1.67.

**Comment by redboltz** [comment]
Updated by #589
