### ISSUE TITLE
Handle both QOS bits set, Malformed Packet

### ISSUE THREAD

**Issue by jonesmz** [redboltz/mqtt_cpp#591]
https://docs.oasis-open.org/mqtt/mqtt/v5.0/os/mqtt-v5.0-os.html#_Toc3901103

A PUBLISH Packet MUST NOT have both QoS bits set to 1 [MQTT-3.3.1-4]. If a Server or Client receives a PUBLISH packet which has both QoS bits set to 1 it is a Malformed Packet. Use DISCONNECT with Reason Code 0x81 (Malformed Packet) as described in section 4.13.

We currently do not attempt to detect this, but the standard states that both clients and servers should detect this and explicitly disconnect.

**Comment by redboltz** [comment]
Implemented.
