### ISSUE TITLE
Access Username and Password on Publish/Subscribe

### ISSUE THREAD

**Issue by david114** [redboltz/mqtt_cpp#597]
Hi,
I'm using the example-code tls_server.cpp code and it works fine, so far.
I want to access the username and password of an MQTT-User when hes publishing or subscribing.
What is the smartest way to access these client information inside `ep.set_publish_handler()` and `ep.set_subscribe_handler()`?

```
ep.set_publish_handler(
  [&subs]
  (MQTT_NS::optional<packet_id_t> packet_id,
  MQTT_NS::publish_options pubopts,
  MQTT_NS::optional<MQTT_NS::buffer> username // LIKE THIS WOULD BE GREAT!
  MQTT_NS::buffer topic_name,
  MQTT_NS::buffer contents) {
    cout << "[server] topic_name: " << topic_name << endl;
    cout << "[server] contents: " << contents << endl;
    auto const& idx = subs.get<tag_topic>();
    auto r = idx.equal_range(topic_name);
    for (; r.first != r.second; ++r.first) {
      r.first->con->publish(
        topic_name,
        contents,
        min(r.first->qos_value, pubopts.get_qos())
     );
   }
   return true;
});
```

**Comment by redboltz** [comment]
username and password are passed at a connect handler that is set by set_connect_handler. So you can store username and password to somewhere at your connect handler, and then access them at your publish handler.

**Comment by david114** [comment]
I'm new to C++ so i experienced some unwanted behaviour when trying to pass a variable to the `set_publish_handler()` 
After figuring out that this was due to C++'s data encapsulation i came up with something like this:
`ep.set_publish_handler([&connections, &subs, wp, mqtt_user, mqtt_password] (.....))`

thanks!
