### ISSUE TITLE
Performing a re-connection

### ISSUE THREAD

**Issue by kmare** [redboltz/mqtt_cpp#606]
First of all, thank you for this library, it looks really well designed.
I'm having a hard time figuring out/understanding how to perform a re-connection in case for example the server is down. Do I need to create a new boost::asio::io_context every time a connection is failing? 
I've tried to call c->disconnect() and a few ms later c->connect(), and that doesn't seem to actually work. Calling c->connected() simply returns false. What exactly am I missing?

Thank you in advance, any help would be really appreciated.

**Comment by redboltz** [comment]
Could you post a minimal and complete client code to reproduce the issue?

For broker side, please use `mqtt_cpp/example/broker`. (port 1883 for MQTT (TCP))

**Comment by kmare** [comment]
Hi @redboltz , sorry about the delay. I've uploaded a snippet to better show what I meant.
https://gitlab.com/snippets/1939514
(it's on a gitlab, let me know if you'd prefer it on github).
It is basically the sample code from this repo, with simply having the ioc in a separate thread and afterwards connecting, disconnecting and finally re-connecting.
I didn't use the broker you mentioned, but a mosquitto server running on my Linux setup.

Thank you in advance!

**Comment by redboltz** [comment]
`boost::asio::ip::tcp::socket` is NOT thread safe.
See
https://www.boost.org/doc/libs/1_72_0/doc/html/boost_asio/reference/ip__tcp/socket.html#boost_asio.reference.ip__tcp.socket.thread_safety

And mqtt_cpp uses `boost::asio::ip::tcp::socket` internally.

You need to care mqtt_cpp endpoint similar to `boost::asio::ip::tcp::socket`.

The easiest way to checking re-connection functionality is, first, call `disconnect()` in some handler such as connack or puback, and then, close handler (or error handler) is called. In the close handler, call `connect()` again.
