### ISSUE TITLE
Broker publish acknowledgement?

### ISSUE THREAD

**Issue by sptrakesh** [redboltz/mqtt_cpp#614]
I tried to test my broker as shown in a Lua client library, and I found that the Lua client hangs waiting on a acknowledge to a publish message.  I may have missed something when I built my broker off your test broker, but could you point me to the relevant handler function that is supposed to handle this?

https://github.com/xHasKx/luamqtt/blob/master/tests/spec/mqtt-client.lua#L180

**Comment by redboltz** [comment]
I don't understand what are you asking. Could you elaborate your question?

Here is the document:
https://github.com/redboltz/mqtt_cpp/wiki

You can set publish response handler using https://redboltz.github.io/contents/mqtt/structMQTT__NS_1_1callable__overlay.html#a4910da7101ee9d3fa46ec576a1ebafd7

**Comment by sptrakesh** [comment]
Thanks, your documentation at https://github.com/redboltz/mqtt_cpp/wiki/automatically-sending-messages was exactly what I was looking for.
