### ISSUE TITLE
Can't make async_client work with support of SSL

### ISSUE THREAD

**Issue by ropieur** [redboltz/mqtt_cpp#615]
Hi,

I successfully implemented an async_client without SSL and now I am required to support SSL (which is completely new to me).

From my understanding, the code adaptation would be quite easy and limited:
- make_async_client should be "replaced" by make_tls_async_client
- add a call to async_client->load_verify_file(cacert), where cacert is the file path of .PEM file containing all necessary certificates and private keys to perform the handshake with the broker.
- and potentially async_client->get_ssl_context().set_options(
                boost::asio::ssl::context::default_workarounds |
                boost::asio::ssl::context::no_sslv2 |
                boost::asio::ssl::context::no_sslv3);

With openssl, I managed to verify that the generated .PEM file works correctly with a local mosquitto broker (impossible with mosquitto clients _sub/_pub that require separated piece explicitly). When I use the same .PEM file directly from the adapted code, it fails with the following error: "sslv3 alert handshake failure"
My investigations led me to a potential limitation with the boost asio library (something related to "server name indication") and a call to SSL_set_tlsext_host_name could solve the issue. So we could argue here that this is more related to boost asio itself. Except that the function requires the native handle of the ssl stream and I have no clue how I can access it from the created "tls_async_client".
Also if this limitation is effective, it might be valuable to handle it in mqtt client library.

Thank you

**Comment by jonesmz** [comment]
As a crappy workaround, you could try setting these:

    get_ssl_context().set_verify_mode(boost::asio::ssl::verify_none);
    get_ssl_context().set_default_verify_paths();

**Comment by redboltz** [comment]
The issue is closed due to no response. If you still interested in the issue, please reopen it.
