### ISSUE TITLE
Hidden compile errors after #623 merged

### ISSUE THREAD

**Issue by redboltz** [redboltz/mqtt_cpp#633]
Before #623 is merged, no error is reported.
https://github.com/redboltz/mqtt_cpp/runs/645858623?check_suite_focus=true#step:6:11

After #623 merged, errors are reported but github actions put green check mark.
https://github.com/redboltz/mqtt_cpp/runs/645859237?check_suite_focus=true#step:6:14

So I looked over the errors.

I think that the errors should be fixed.
In addition, github actions put invalid green check should be fixed too.

**Comment by jonesmz** [comment]
This is very strange.

I will look.

**Comment by redboltz** [comment]
Any updates?
If it will still take some time to fix the issue, I revert #623 once because it avoid checking other pull requests.

**Comment by jonesmz** [comment]
Sorry, spent a few hours to find problem, but wasn't able to.

Please revert for now.
