### ISSUE TITLE
Need for synchronization of message-handler?

### ISSUE THREAD

**Issue by rberlich** [redboltz/mqtt_cpp#635]
Hi there,

I am new to MQTT and have so far only played with some easy MQTT Python-models, based on Paho and Mosquitto. I would now like to apply my knowledge to C++ (in which I am generally experienced) and mqtt_cpp (to which I am new). 

So apologies if this is a naive question: Is it safe to assume that, with an async_client, I do not have to manually synchronize the message-handler regarding mqtt_cpp-calls? A new message may arrive when the old one is still being processed, and I would like to use publish from within the message handler, so two publish-calls may occur at the same time. Is this safe? I.e., are these calls internally run though a strand or protected with a mutex?

Thanks and Kind Regards,
Rüdiger

**Comment by redboltz** [comment]
async_client as async APIs as follows:

|type\operation|send|recv|
|---|---|---|
|async_client|async|asnyc|
|sync_client|sync|async|

Note that recv operation is always async.

If you want to use async_client on multi thread environment, you need to use strand.
The strand is automatically prepared when you call 

https://github.com/redboltz/mqtt_cpp/blob/d2c09d884a27d5f96e3a550511fb36a32ffc5b14/include/mqtt/client.hpp#L1392-L1405.

Consider the following scenario:

1. make_cliient() is called with `ioc` (io_context).
2. `ioc.run()` is called from the multiple thread.
3. async_subscribe topic1
4. publish is received multiple times.

publish_handler calls are serialized. So one thread receives publish message and then call publish_handler. On the same time, the other thread receives publish message, then waits until the previous publish_handler is finished. **wait** doesn't meas block. 

Here is a good document how strand work:
https://www.boost.org/doc/libs/1_73_0/doc/html/boost_asio/tutorial/tuttimer5.html

This is receiving process.

The scenario contains sending a message. Step3 calls async_subscribe. 

All async APIs call do_async_write internally.
https://github.com/redboltz/mqtt_cpp/blob/d2c09d884a27d5f96e3a550511fb36a32ffc5b14/include/mqtt/endpoint.hpp#L8802-L8818

In the do_async_write, `socket_->post()` is called. the `socket_` contains the strand. So the async APIs call is automatically serialized.

So far, you don't need to use manual synchronization.

There is one exception. It is force_disconnect().

https://github.com/redboltz/mqtt_cpp/blob/d2c09d884a27d5f96e3a550511fb36a32ffc5b14/include/mqtt/endpoint.hpp#L889-L893.

If you call `force_disconnect()` inside of the strand, it is safe. For example, in the publish_handler. However, If you call `force_disconnect()` outside of the strand, it is unsafe.
The latter case, you need to write the following code.

```cpp
client->socket().post(
    [&] { // keeping client lifetime is caller's responsibility
        client->force_disconnect(); // in the strand, so thread safe
    }
);
```

**Comment by rberlich** [comment]
Thanks for the help. This is most appreciated!
