### ISSUE TITLE
Server socket options

### ISSUE THREAD

**Issue by mhfrantz** [redboltz/mqtt_cpp#638]
I would like to run a `server` with the `SO_REUSEPORT` option. Does there need to be a way to send socket options into the constructor, or expose the socket in a callback? My use case is a test fixture where I would like to recreate the server on the same port without waiting for `WAIT_TIME`. Apologies if I missed how this works.

**Comment by redboltz** [comment]
mqtt_cpp provides a callback to setup acceptor.
For example, reuse_address is set as follows:
https://github.com/redboltz/mqtt_cpp/blob/b51d4c8afcfef3ddade45ee13f203ac31c94e566/test/test_server_no_tls.hpp#L30

I'm not sure boost asio provides reuse_port() convenient function (or class). Maybe doesn't exist.

https://www.boost.org/doc/libs/1_73_0/doc/html/boost_asio/reference/basic_socket_acceptor/set_option.html
https://www.boost.org/doc/libs/1_73_0/doc/html/boost_asio/reference/SettableSocketOption.html

But you can define your own wrapper. See asio reference.

**Comment by mhfrantz** [comment]
Thanks, this worked great. Sorry I didn't understand what `AcceptorConfig` was for, but it makes perfect sense now. I really like this library.

I found [this hack](https://stackoverflow.com/questions/34596638/boost-asio-so-reuseport) for dealing with `SO_REUSEPORT`:
```c++
using ReusePort = boost::asio::detail::socket_option::boolean<SOL_SOCKET, SO_REUSEPORT>;
```

**Comment by redboltz** [comment]
Here is an example code to implement the class that satisfied SettableSocketOption concept.

```cpp
struct tcp_cork {
    tcp_cork(bool v):value_(v ? 1 : 0) {}

    template <typename Protocol>
    int level(Protocol const&) const {
        return IPPROTO_TCP;
    }

    template <typename Protocol>
    int name(Protocol const&) const {
        return TCP_CORK;
    }

    template <typename Protocol>
    void const* data(Protocol const&) const {
        return &value_;
    }

    template <typename Protocol>
    std::size_t size(Protocol const&) const {
        return sizeof(value_);
    }
private:
    int value_;
};


acceptor.set_option(tcp_cork(true)); 
```

Maybe you can modify the example code.
