### ISSUE TITLE
Release plan for v8

### ISSUE THREAD

**Issue by shantanu1singh** [redboltz/mqtt_cpp#639]
There are a few new changes/features in v8 that I'd like to use for my project. Is there an expected release date/month for it?

**Comment by jonesmz** [comment]
I suspect that I am the hold-up for this release.

Which features, in particular, are you interested in?

For what it's worth, I'm currently running a relatively recent master branch commit in my production code, so I'm personally not all that committed to making specific named releases.

**Comment by shantanu1singh** [comment]
Here's a list of the features I'd like to use

Changes already in `master`:
- Pass boost::system::error_code to the `connect()` API
- Use `find_package(mqtt_cpp_iface REQUIRED)` in my `CMakeLists.txt`. This brings up a side-question - would you know what changes should be made to the CMakeLists.txt of a consumer project that is using v7.0.1?

Changes yet to be merged:
- Use the logging changes that are being tracked by issue #292 
- If I do get time to get to #636 , I'd like to get that included in v8 too.

**Comment by shantanu1singh** [comment]
@jonesmz - thought I'll check-in again to see if there are any updates on the release plan?

**Comment by jonesmz** [comment]
@shantanu1singh Sorry, didn't realize you wanted a reply from me.

Ultimately this is @redboltz project, so all I can do is offer speculation for you.

>  would you know what changes should be made to the CMakeLists.txt of a consumer project that is using v7.0.1?

I didn't have to make any changes to my project, but that doesn't mean you won't have to make some adjustments.

> Use the logging changes that are being tracked by issue #292

This is not going to happen soon. It'll easily be 2-3 months before this is ready for review, unless @redboltz is spending all of his work time on it.

> If I do get time to get to #636 , I'd like to get that included in v8 too.

I think this change would be almost entirely CMake changes, right? That should be straight forward to get merged.

> Pass boost::system::error_code to the connect() API

Could you be more specific? Maybe a PR or commit hash? It could probably be backported easily.

**Comment by redboltz** [comment]
I don't have much time to check merged PRs.
If the PRs contains breaking changes, the new version will be v8.0.0.
Otherwise, if the PRs contains adding functionalities, the new version will be v7.1.0
Otherwise (contains bug fixes only) , the new version will be v7.0.2.

> Here's a list of the features I'd like to use
> 
> Changes already in `master`:
> 
> * Pass boost::system::error_code to the `connect()` API
> * Use `find_package(mqtt_cpp_iface REQUIRED)` in my `CMakeLists.txt`. This brings up a side-question - would you know what changes should be made to the CMakeLists.txt of a consumer project that is using v7.0.1?

I can release the next version that contains merged PRs above., *1

> Changes yet to be merged:
> 
> * Use the logging changes that are being tracked by issue #292
> * If I do get time to get to #636 , I'd like to get that included in v8 too.

These functionalities require additional work. So the time of release is unpredictable. It depends on our work.

If you want to *1 release, I can do that.

**Comment by redboltz** [comment]
> I don't have much time to check merged PRs.
> If the PRs contains breaking changes, the new version will be v8.0.0.
> Otherwise, if the PRs contains adding functionalities, the new version will be v7.1.0
> Otherwise (contains bug fixes only) , the new version will be v7.0.2.

Note: if I the current master contains breaking change, and release it as the v8.0.0, then the feature for v8.0.0 is moved to v9.0.0.

**Comment by shantanu1singh** [comment]
> I can release the next version that contains merged PRs above., *1

@redboltz That'd be great. The features themselves might be split across PRs. Although I'm not sure.


> These functionalities require additional work. So the time of release is unpredictable. It depends on our work.

I understand. That's okay - we could potentially have another release later that has the other features once they've been merged?

**Comment by shantanu1singh** [comment]
Hey @redboltz, would it be possible for you to create a v8.0.0 release including the features discussed above then?

**Comment by redboltz** [comment]
> Hey @redboltz, would it be possible for you to create a v8.0.0 release including the features discussed above then?

Yes, I'm going to release based on the current master (https://github.com/redboltz/mqtt_cpp/commit/805df1bd9fe8b8aa207bec27e8a98d76966599e1) as 8.0.0.

**Comment by shantanu1singh** [comment]
@redboltz Great, thanks! Is there an expected timeframe when you think you'll be able to do this by?

**Comment by redboltz** [comment]
I can do that today. See #651 

NOTE: It doesn't solve #650 .

**Comment by redboltz** [comment]
v8.0.0 has been released.

https://github.com/redboltz/mqtt_cpp/releases/tag/v8.0.0
