### ISSUE TITLE
Detect broken link on client side

### ISSUE THREAD

**Issue by marcel-behlau-elfin** [redboltz/mqtt_cpp#648]
Hello,

i observed the problem, that a broken link (by unplugging my network cable) isn't detected by my client application. The broker (mosquitto) detects the broken link after the configured keep alive time. The client should be able to detect a broken link also by detecting PINGRESP timeout. Is there already a PINGRESP timeout callback, which is missed?

**Comment by redboltz** [comment]
> Is there already a PINGRESP timeout callback, which is missed?

No.

https://docs.oasis-open.org/mqtt/mqtt/v5.0/os/mqtt-v5.0-os.html#_Keep_Alive_1


> If the Keep Alive value is non-zero and the Server does not receive an MQTT Control Packet from the Client within one and a half times the Keep Alive time period, it MUST close the Network Connection to the Client as if the network had failed [MQTT-3.1.2-22].

The server (broker) side spec is well defined. Timeout value is KeepAlive*1.5. And the spec uses "MUST".

> If a Client does not receive a PINGRESP packet within a reasonable amount of time after it has sent a PINGREQ, it SHOULD close the Network Connection to the Server.

The client side spec said that "a reasonable amount of time after it has sent a PINGREQ". And the spec uses "SHOULD".

So far, mqtt_cpp delegate the disconnection checking responsibility to the underlying layer. However, the underlying layer might not check the disconnection. In addition, broker might not send PINGRESP even if network is connected. So mqtt_cpp should have PINGRESP timeout functionality.

I think that "a reasonable amount of time" should be defined by user because it depends on the environment.

Maybe we should have something like the following function:

```cpp
void set_pingresp_timeout(std::chrono::steady_clock::duration time);
```

If the client doesn't receive PINGRESP from the broker until `time` after sending PINGREQ, then call force_disconnect() internally. As the result of the `force_disconnect()`, on_error callback is called.

**Comment by marcel-behlau-elfin** [comment]
Hi,

thanks for your fast reply. Adding an extra option to enable an `force_disconnect()` wihle a PINGRESP timeout sounds like an good solution for me.

I'm not sure, if i like to add an new `set_pingresp_timeout();` method.

I think, for the user of mqtt_cpp it's easier, if this function would be integrated into the existing `set_keep_alive_sec_ping_*()` via an default parameter. This reduces the available methods and also avoids the wrong usage of the pingresp timeout function. (a pingresp timeout can only be enabled, if keep alive has been enabled). 

```
    /**
     * @brief Set a keep alive second and optionally a ping duration and pingresp_timeout_disconnect time.
     * @param keep_alive_sec keep alive seconds
     * @param ping_ms ping sending interval
     * @param pingresp_timeout_disconnect timeout time after missing PINGRESP before perform force_disconnect().
     * Values < 0 disables the pingresp_timeout_disconnect
     *
     * When a endpoint connects to a broker, the endpoint notifies keep_alive_sec to
     * the broker.
     * After connecting, the broker starts counting a timeout, and the endpoint starts
     * sending ping packets for each ping_ms.
     * When the broker receives a ping packet, timeout timer is reset.
     * If the broker doesn't receive a ping packet within keep_alive_sec, the endpoint
     * is disconnected.<BR>
     * See https://docs.oasis-open.org/mqtt/mqtt/v5.0/os/mqtt-v5.0-os.html#_Toc464635115<BR>
     * 3.1.2.10 Keep Alive
     */
  void set_keep_alive_sec(std::uint16_t keep_alive_sec,
                          std::chrono::steady_clock::duration ping = std::chrono::seconds(keep_alive_sec / 2),
                          std::chrono::steady_clock::duration pingresp_timeout_disconnect = std::chrono::seconds(-1)
  );
```

**Comment by redboltz** [comment]
I think that KeepAlive functionality and PINGRESP timeout functionality are independent.

According to the spec 
https://docs.oasis-open.org/mqtt/mqtt/v5.0/os/mqtt-v5.0-os.html#_Keep_Alive_1

> The Client can send PINGREQ at any time, irrespective of the Keep Alive value, and check for a corresponding PINGRESP to determine that the network and the Server are available.

Even if KeepAlive is disabled, the client can send PINGREQ. In this case, if PINGRESP timeout is set, then timeout should work.

`set_pingresp_timeout()` would be newly introduced function and functionality. It is not set by default.
If it is set, then, the timeout is enabled regardless of the KeepAlive.

**Comment by marcel-behlau-elfin** [comment]
Ahhh, okay, if this can be used indenpentaly from each other, adding `set_pingresp_timeout()` is fine.

**Comment by redboltz** [comment]
@marcel-behlau-elfin , I implemented #649 
Could you try this?

**Comment by redboltz** [comment]
Fixed by #649

**Comment by redboltz** [comment]
If you still have the issue, feel free to reopen the issue.

**Comment by marcel-behlau-elfin** [comment]
Thank you very much!
