### ISSUE TITLE
Recommendation for publish() with minimal copying

### ISSUE THREAD

**Issue by shantanu1singh** [redboltz/mqtt_cpp#652]
The library currently has the following publish() APIs:

```
void publish(
        packet_id_t packet_id,
        std::string topic_name,
        std::string contents,
        publish_options pubopts = {},
        v5::properties props = {},
        any life_keeper = {}
    )

void publish(
        packet_id_t packet_id,
        as::const_buffer topic_name,
        as::const_buffer contents,
        publish_options pubopts,
        v5::properties props,
        any life_keeper
    )

void publish(
        packet_id_t packet_id,
        as::const_buffer topic_name,
        as::const_buffer contents,
        publish_options pubopts,
        any life_keeper
    )

void publish(
        packet_id_t packet_id,
        buffer topic_name,
        buffer contents,
        publish_options pubopts = {},
        any life_keeper = {}
    )

void publish(
        packet_id_t packet_id,
        buffer topic_name,
        buffer contents,
        publish_options pubopts,
        v5::properties props,
        any life_keeper = {}
    )
```

I'm trying to understand which API would be ideal for my project's use.
I'm currently using QoS 1 for publishing messages and would like to minimize the amount of copying that's done once these APIs are called by my project code.

Reading through the comments in the code, it seems like the APIs that accept `buffer` and `const_buffer` are ideal for that but they require the consumer of the API to manage the lifetime of the buffer(s). Is that correct?

I would like to avoid having to do that. If so, is the API that accepts a `std::string` the only option I can use?

Appreciate your help!

**Comment by jonesmz** [comment]
`buffer` and `as::const_buffer` are from two different namespaces.

`buffer` is the MQTT_NS::buffer, which is essentially a std::shared_ptr<char[]> + std::string_view.

You can use this with `MQTT_NS::allocate_buffer(mystringhere)`

If you keep your data in this form for most of your application, then you want to use this form of the API.

If you want to manage the lifetime yourself, then you want to use the `as::const_buffer` form.

**Comment by shantanu1singh** [comment]
I see. Just to confirm - if I were to use `buffer`, I wouldn't have to manage the lifetime of the `buffer` in my application code, right?

I might opt for that if so. The way we've set up our application so far is to create a new thin library over the mqtt_cpp client which abstracts away the interface of the mqtt_cpp library. In the sense that it's not aware of the MQTT_NS::* namespace constructs. 

I am thinking of accepting an `std::string` or char array/vector in the Publish APIs exposed by this thin wrapper layer and internally creating an `MQTT_NS::buffer` that copies the string or char array/vector before calling the APIs on the mqtt_cpp library.

**Comment by jonesmz** [comment]
> I see. Just to confirm - if I were to use buffer, I wouldn't have to manage the lifetime of the buffer in my application code, right?

It has the same lifetime semantics as std::shared_ptr.

> The way we've set up our application so far is to create a new thin library over the mqtt_cpp client which abstracts away the interface of the mqtt_cpp library. In the sense that it's not aware of the MQTT_NS::* namespace constructs.

Why?

> I am thinking of accepting an std::string or char array/vector in the Publish APIs exposed by this thin wrapper layer and internally creating an MQTT_NS::buffer that copies the string or char array/vector before calling the APIs on the mqtt_cpp library.

Why?

There's no point in doing that, the MQTT_NS::publish function that accepts std::string is the most efficent way of handing data that is stored in an std::string.

Unless your data never lives in an std::string, and only lives in something that's analogous to std::shared_ptr + std::string_view, there's no point in copying things in the way you described.

**Comment by jonesmz** [comment]
If you read the publish() functions, you'll see that all that is happening is that the std::string is being std::moved() into a newly allocated std::shared_ptr<std::string>.

The MQTT_NS::buffer functions are the most efficient if you already have your data stored in a std::shared_ptr

But the as::const_buffer functions are the most efficent possible if you have some other lifetime management system, as they are equivalent to std::string_view.

**Comment by shantanu1singh** [comment]
Sounds good, I'll just use std::string for now

**Comment by DavidAntliff** [comment]
> Sounds good, I'll just use std::string for now

Sorry to bump this, but how do you pass in a `std::string` as topic or contents? The function `mqtt::buffer::buffer(std::string)` is deleted (with the comment "to avoid misuse") so it won't compile.
