### ISSUE TITLE
client::async_connect() sets username/password flags even without provided username/password

### ISSUE THREAD

**Issue by geith** [redboltz/mqtt_cpp#653]
When `client::async_connect()` (current version in the master branch) is called without any username/password set, RabbitMQ rejects the connection with error code 4 (`bad_user_name_or_password`). This happens, because the username and password flags are set in the connect message (traces with Wireshark) but the username/password fields are empty.

Source of the issue is `client::async_start_session()` in _client.hpp:1069_; `endpoint::async_connect()` (_endpoint.hpp:3093_) expects `optional<buffer>` as arguments for username and password, but `client::async_start_session()` creates empty buffers.

This patch solves the issue, but I'm not sure if there are similar issues somewhere else:
```diff
diff --git a/include/mqtt/client.hpp b/include/mqtt/client.hpp
index a7b9dcc..39a745e 100644
--- a/include/mqtt/client.hpp
+++ b/include/mqtt/client.hpp
@@ -1069,9 +1069,9 @@ private:
         base::async_connect(
             buffer(string_view(client_id_)),
             ( user_name_ ? buffer(string_view(user_name_.value()))
-                         : buffer() ),
+                         : optional<buffer>() ),
             ( password_  ? buffer(string_view(password_.value()))
-                         : buffer() ),
+                         : optional<buffer>() ),
             will_,
             keep_alive_sec_,
             force_move(props),
```

**Comment by redboltz** [comment]
@geith , thank you for reporting issue and giving the solution.

I sent #654 to fix the issue.

> This patch solves the issue, but I'm not sure if there are similar issues somewhere else:

**sync** version had the same issue so #654 fix both async and sync.
