### ISSUE TITLE
Fails to compile with boost asio 1.74

### ISSUE THREAD

**Issue by rezahousseini** [redboltz/mqtt_cpp#669]
When compiling against boost asio 1.74 one has to define `BOOST_ASIO_USE_TS_EXECUTOR_AS_DEFAULT` for it to compile.
The details are explained [here](https://think-async.com/Asio/asio-1.18.0/doc/asio/std_executors.html#asio.std_executors.polymorphic_i_o_executor), in fact one has to change the old polymorphic `executor` type into the new polymorphic executor type `any_io_executor`.

**Comment by redboltz** [comment]
@rezahousseini , thank you for reporting the issue.
I reproduced the error. And I read the document.
mqtt_cpp supports boost 1.66.0 or later.
I'd like to support both old (boost 1.66.0) and new (boost 1.74.0 without BOOST_ASIO_USE_TS_EXECUTOR_AS_DEFAULT).
However, I couldn't find how to do that.

If you know a good way, please tell me or make a pull request.

**Comment by redboltz** [comment]
I found the solution by myself. Please check #670

**Comment by rezahousseini** [comment]
I assumed it has something to do with the type erased socket, thank you!

**Comment by redboltz** [comment]
@rezahousseini , yes and I fixed it. Does #670 work well on your environment?
