### ISSUE TITLE
What does retained_topic_map::size() return ?

### ISSUE THREAD

**Issue by redboltz** [redboltz/mqtt_cpp#692]
@kleunen , I got confused the return value of `retained_topic_map::size()`.

https://github.com/redboltz/mqtt_cpp/blob/master/test/retained_topic_map.cpp#L23
I think that two elements insert and one element erase then the number of element is 1.

https://github.com/redboltz/mqtt_cpp/blob/master/test/retained_topic_map.cpp#L26
And one more element erased then  the number of element is 0.

But size() returns something different.

**Comment by kleunen** [comment]
Yes, it returns the number of entries in the map inside the retained_topic_map. This is after tokenizing the stores topics, so a/b/ create 2 entries and creating a/b/c creates 1 additional entry (total 3). We can calculate how many values / topics are actually stored.

**Comment by redboltz** [comment]
Ok I understand.
