### ISSUE TITLE
Ether share name or topic filter should be a primary factor for delivery on shared subscriptions ?

### ISSUE THREAD

**Issue by redboltz** [redboltz/mqtt_cpp#716]
Consider the following scenario:

Here is a list of shared subscription.

```
c1: $share/sn1/t1
c1: $share/sn1/t2
c2: $share/sn1/t1
c3: $share/sn1/t1
c3: $share/sn1/t2
```

A publisher publishes t1,t2,t1,t2.... continuously.

## Share Name based

If share name is primary factor to decide delivery target, then the expected delivery order should be as follows:

| client | share name | topic | expected delivery order |
|----|---|---|---|
|c1|sn1|t1|1,7,9|
|c1|sn1|t2|4|
|c2|sn1|t2|2,6,10|
|c3|sn1|t1|3,5,11|
|c3|sn1|t2|8|

### Pros
Client based load ballancing can be achieved.
c1, c2, anc c3 has similar loads.

### Cons
Difficult to implement. I'm not sure it can be acheived without O(N) complexity.
I guess that some LRU algorithm for client and share name is required.
It needs to care about not matched topics.

## Topic Filter based

If topic filter is primary factor to decide delivery target, then the expected delivery order should be as follows:

| client | share name | topic | expected delivery order |
|----|---|---|---|
|c1|sn1|t1|1,5,9|
|c1|sn1|t2|2,8|
|c2|sn1|t2|4,10|
|c3|sn1|t1|3,7,11|
|c3|sn1|t2|6|

In this scenario the broker delivers to c2 very small amount of message.

### Pros
Easier to implement.

### Cons
Client based load ballancing can't be achieved.

NOTE: MQTT spec doesn't say anything about delivery algorithm. That means both satisfies the spec. But I guess that users expectation is Share Name based.

**Comment by kleunen** [comment]
If I read:
https://docs.oasis-open.org/mqtt/mqtt/v5.0/os/mqtt-v5.0-os.html#_Toc3901250

_Each Shared Subscription is independent from any other. It is possible to have two Shared Subscriptions with overlapping filters. In such cases a message that matches both Shared Subscriptions will be processed separately by both of them. If a Client has a Shared Subscription and a Non‑shared Subscription and a message matches both of them, the Client will receive a copy of the message by virtue of it having the Non‑shared Subscription. A second copy of the message will be delivered to one of the subscribers to the Shared Subscription, and this could result in a second copy being sent to this Client._

It is my understanding that not only the share name, or only the topic filter, but the combination (share name / topic filter) is the key to determine which clients receive a published message. 

So if you have two subscribers with different group names::
c1: $share/sn1/t1
c2: $share/sn2/t1
And you publish to /t1, both c1 and c2 will receive a message. 


If you have two subscribers with same group name:
c1: $share/sn1/t1
c2: $share/sn1/t1
And you publish to /t1, first c1 will receive message, second publish to /t1, c2 will receive message

If you have two subscribers with same group name but different but overlapping topics:
c1: $share/sn1/t1
c2: $share/sn1/+
And you publish to /t1, both c1 and c2 will receive message


You can have different load balancing strategies:

- Round-robin: go through subscribed client one-by-one
- Load based: you know the load of the subscriber and give it to the lowest load subscriber
- Random: Pick a random subscriber, load will be evenly / normally distributed

https://en.wikipedia.org/wiki/Load_balancing_(computing)#Static_load_distribution_without_prior_knowledge

**Comment by kleunen** [comment]
So in your scenario, you would actually have two round-robin load-balancers:

(sn1, t1) -> 1 (c1), 3 (c3), 5 (c1), 7 (c3), 9 (c1)

(sn1, t2) -> 2 (c1), 4 (c2), 6 (c3), 8 (c1), 10 (c2)

**Comment by redboltz** [comment]
> So in your scenario, you would actually have two round-robin load-balancers:
> 
> (sn1, t1) -> 1 (c1), 3 (c3), 5 (c1), 7 (c3), 9 (c1)
> 
> (sn1, t2) -> 2 (c1), 4 (c2), 6 (c3), 8 (c1), 10 (c2)

Could you write the same table format as my comment? It is easy to understand.

**Comment by redboltz** [comment]
> It is my understanding that not only the share name, or only the topic filter, but the combination (share name / topic filter) is the key to determine which clients receive a published message.

That is the same as my understanding. My example https://github.com/redboltz/mqtt_cpp/issues/716#issue-731179540 is using both share name and topic filter to determine. My point is which is the first key and which is the second key. That is order issue. Finally both keys are used.

For simplify the example I only use `sn1`. But off course, I care `sn2`.

**Comment by redboltz** [comment]
> So in your scenario, you would actually have two round-robin load-balancers:

I think that it is an interesting method.

**Comment by redboltz** [comment]
Sorry I noticed my mistake. I will post the fixed version soon.

**Comment by kleunen** [comment]
ok, i did not fully understand your explanation

**Comment by kleunen** [comment]
client | share name | topic | expected delivery order
-- | -- | -- | --
c1 | sn1 | t1 | 1,5,9
c1 | sn1 | t2 | 2,8,14
c2 | sn1 | t2 |  4,10,16
c3 | sn1 | t1 | 3,7,11
c3 | sn1 | t2 | 6,12,18

**Comment by redboltz** [comment]
I updated https://github.com/redboltz/mqtt_cpp/issues/716#issue-731179540 second table.

**Comment by kleunen** [comment]
But the load balancing is not based on all shares combined. So you are not load-balacing based on the total number of clients for all subscriptions combined. You are load balancing based on a single topic. All messages for a single topic are spread accross clients. 

If a client subscribes to multiple topics, and receives 2x or 3x the amount of messages compared to another client, that is responsibility of the user.

**Comment by redboltz** [comment]
https://github.com/redboltz/mqtt_cpp/issues/716#issuecomment-717925286
Thank you! It is completely the same as I updated one.
So this one is first key is topic filter and the second key is share name.
It is easy to implement but c2 receives small amount of messages.

**Comment by redboltz** [comment]
> But the load balancing is not based on all shares combined. So you are not load-balacing based on the total number of clients for all subscriptions combined. You are load balancing based on a single topic. All messages for a single topic are spread accross clients.
> 
> If a client subscribes to multiple topics, and receives 2x or 3x the amount of messages compared to another client, that is responsibility of the user.
> 
> So indeed:
> 
> > In this scenario the broker delivers to c2 very small amount of message.
> 
> That is correct, c1 and c3 subscribe to two topics, c2 only to one

Yes, it is one of the point of view.

I think that shared subscriptions is designed for application server not iot devices.
Before shared subscriptions is introduced, sharding is common way to load balancing.
Let's say c1, c2, and c3 are application servers. They have similar computing resorces.

Devices publish to various kinds of topics. It is unpredictable.
If share name can balance across topics, then c1, c2, and c3 just set the same share name.
The broker automatically does load balancing.

I think that it could be helpful and perhaps it is more much to user needs than topic filter first way.

However, it is only my guessing. 

If both topic filter first and share name first are easy to implement, I can implement both using something like strategy pattern and switch the strategy on compile time or runtime. (I love customize, you know ;)

As far as I considered, share name first strategy is pretty difficult to implement at least or me.

**Comment by redboltz** [comment]
I also think that , if c1, c2, and c3 have similar computing resources, and user want to fair load balancing, then there is no reason to subscribing different topics. So on typical usecase, c1, c2, and c3 subscribe the same topics.
That means topic filter first strategy is enough to fair load balancing.

**Comment by kleunen** [comment]
> If both topic filter first and share name first are easy to implement, I can implement both using something like strategy pattern and switch the strategy on compile time or runtime. (I love customize, you know ;)

Yes, i want those Japanese options in broker now :)
But seriously, different strategies make sense. 

You can use the subscription map also to tracker shares. 

If client c1 wants to subscribe to share: 
$share/sn1/t1

You add entry to "subscription map":
$share/+/t1 -> (sn1, c1)

If client c2 wants to subscribe to share: 
$share/sn1/t1

You will have:
$share/+/t1 -> [ (sn1, c1), (sn1, c2) ]

If client c3 wants to subscribe to share: 
$share/sn2/t1

You will have:
$share/+/t1 -> [ (sn1, c1), (sn1, c2), (sn2, c3) ]

When a message is published to /t1, then you group based on share name:
[ (sn1, c1), (sn1, c2) ] -> select one
[ (sn2, c3) ] -> select one

**Comment by redboltz** [comment]
So I think there is no big reasons to support share name first strategy.
It can achieve fair load balancing even if each client that subscribe the same share name and different topics.
It is conceptually good but maybe not a practical usecase.

So it isn't valuable that supporting share name first strategy ( that is harder way).

That is my current conclusion. But before I start implementing the topic filter first strategy, I will wait a time.
Perhaps different idea would come up with.

**Comment by kleunen** [comment]
> Perhaps different idea would come up with.

yes, it is always good to step back and wait for a while.

**Comment by redboltz** [comment]
> But seriously, different strategies make sense.

I agree. Some of brokers support some strategy.

For example
1. very simple round robin (offline/online mixed)
2. online clients have high priority. If there is no online deliver targets, then try offline .
3. weight based round robin parameter using UserProperty (broker extension).

I guess that switching them are not so difficult. (But not well considered)

However, topic filter first and share name first are different. At least share name first strategy needs deep relationship with the data structure. So I wanted to discuss the topic first.

**Comment by kleunen** [comment]
> However, topic filter first and share name first are different. At least share name first strategy needs deep relationship with the data structure. So I wanted to discuss the topic first.

Yes, but also for (sharename/topic) combination key, we need to change the subscription map. Now on the callback, you do not know which topic filter was matched. 

so when both /t1 and /+ will match,  according to specification, this would mean you receive 2 messages (overlapping topic filters)

_It is possible to have two Shared Subscriptions with overlapping filters. In such cases a message that matches both Shared Subscriptions will be processed separately by both of them._

**Comment by redboltz** [comment]
> > However, topic filter first and share name first are different. At least share name first strategy needs deep relationship with the data structure. So I wanted to discuss the topic first.
> 
> Yes, but also for (sharename/topic) combination key, we need to change the subscription map. Now on the callback, you do not know which topic filter was matched.

Ah, exactly. I think that we should have matched topic filter as additional callback parameter. (Not well considered.)
Or we can store topic filter as value similar as subscription identifier.

> so when both /t1 and /+ will match on one client, according to specification, this would mean you receive 2 messages (overlapping topic filters)
> 
> _It is possible to have two Shared Subscriptions with overlapping filters. In such cases a message that matches both Shared Subscriptions will be processed separately by both of them._

At first, I skipped to think about it. Because it was not essential point to decide share name first or topic filter first.

But now, I think it is a time to consider it :)

Let me clarify my understanding.

As you commented before:

Subscription:

c1: $share/sn1/t1
c2: $share/sn1/+

When you publish t1, then the broker delivers to both c1 and c2.

Subscription:

c1: $share/sn1/t1
c1: $share/sn1/+

When you publish t1, what would happen?

> It is possible to have two Shared Subscriptions with overlapping filters. In such cases a message that matches both Shared Subscriptions will be processed separately by both of them.

I understand that describes topic filter overlapping case. It is OK. But how about share name ? At least the sentence above nothing refer to share name.

c1: $share/sn1/t1
c1: $share/sn2/+

When you publish t1, matched subscription `t1` and `+` processed separately. It is reasonable.

Let's back to the following case

Subscription:

c1: $share/sn1/t1
c1: $share/sn1/+

1. The broker deliver the published message to c1 twice, even if the two subscriptions have the same share name.
2. The broker deliver the published message to c1 once. Choosing one of `t1` or `+`. Imagine they have different QoS and subscription identifier.
3. The broker deliver the published message to c1 once. But subscription information is mixed. So QoS is adjusted to higher one and two subscription identifiers are added.

Note that non shared subscription case, send twice or send (mixed) once are implementation choice.
What happened shared subscription case ?

**Comment by redboltz** [comment]
```
c1: $share/sn1/t1
c1: $share/sn2/t2
         .
         .
         .
c1: $share/snN/tN

c2: $share/sn1/t1
c2: $share/sn2/t2
         .
         .
         .
c2: $share/snN/tN
```

Could be a solution for Topic Filter first.

**Comment by kleunen** [comment]
> I understand that describes topic filter overlapping case. It is OK. But how about share name ? At least the sentence above nothing refer to share name.

In this case:
c1: $share/sn1/t1
c1: $share/sn1/+

_In such cases a message that matches both Shared Subscriptions will be processed separately by both of them._

You have two load balancer here:
balancer1: (sn1, t1) 
balancer2: (sn1, +)

So possibly, based on the states of the load balancers, c1 might receive 0, 1 or 2 messages.

**Comment by jonesmz** [comment]
> For example
> 
>     1. very simple round robin (offline/online mixed)
> 
>     2. online clients have high priority. If there is no online deliver targets, then try offline .
> 
>     3. weight based round robin parameter using UserProperty (broker extension).

My understanding of the shared subscription feature from the standard is that if there are online clients, the message must not be delivered to offline clients, even if those offline clients later re-connect.

**Comment by kleunen** [comment]
_A Session can explicitly detach itself from a Shared Subscription by sending an UNSUBSCRIBE Packet that contains the full Shared Subscription Topic Filter. Sessions are also detached from the Shared Subscription when they terminate._

**Comment by jonesmz** [comment]
An offline session and a terminated session are not the same thing.

**Comment by kleunen** [comment]
> An offline session and a terminated session are not the same thing.

No, so does it state somewhere in the specification how to handle shared topics and offline clients ?

**Comment by kleunen** [comment]
Qos1: _If the Server is in the process of sending a QoS 1 message to its chosen subscribing Client and the connection to that Client breaks before the Server has received an acknowledgement from the Client, the Server MAY wait for the Client to reconnect and retransmit the message to that Client. If the Client'sSession terminates before the Client reconnects, the Server SHOULD send the Application Message to another Client that is subscribed to the same Shared Subscription. It MAY attempt to send the message to another Client as soon as it loses its connection to the first Client._

Qos2:  _If the Server is in the process of sending a QoS 2 message to its chosen subscribing Client and the connection to the Client breaks before delivery is complete, the Server MUST complete the delivery of the message to that Client when it reconnects [MQTT-4.8.2-4] as described in section 4.3.3. If the Client's Session terminates before the Client reconnects, the Server MUST NOT send the Application Message to any other subscribed Client [MQTT-4.8.2-5]._

**Comment by jonesmz** [comment]
> > An offline session and a terminated session are not the same thing.
> 
> No, so does it state somewhere in the specification how to handle shared topics and offline clients ?

Yes, in multiple places, including the two details you located in your reply.

Some other notable points from the standard

> In the case of a Shared Subscription where the message is too large to send to one or more of the Clients but other Clients can receive it, the Server can choose either discard the message without sending the message to any of the Clients, or to send the message to one of the Clients that can receive it.

Personally I think making the broker choose a client that can receive the message, instead of discarding it would be substantially better.

> If the subscription was shared, then only the Subscription Identifiers that were present in the SUBSCRIBE packet from the Client which is receiving the message are returned in the PUBLISH packet.

> Bit 2 of the Subscription Options represents the No Local option. If the value is 1, Application Messages MUST NOT be forwarded to a connection with a ClientID equal to the ClientID of the publishing connection [MQTT-3.8.3-3]. It is a Protocol Error to set the No Local bit to 1 on a Shared Subscription [MQTT-3.8.3-4].

> If a Server receives a Topic Filter that is identical to the Topic Filter for a Shared Subscription that already exists on the Server, the Session is added as a subscriber to that Shared Subscription. No retained messages are sent. 

> If a Server receives a Shared Subscription Topic Filter that is not identical to any existing Shared Subscription’s Topic Filter, a new Shared Subscription is created. The Session is added as a subscriber to that Shared Subscription. No retained messages are sent.

**Comment by jonesmz** [comment]
So having searched for all instances of the "Shared" keyword in the standard... I'm not actually able to locate the passage that led me to the conclusion that offline sessions that are not terminated do not receive messages from the shared subscription.

That may not be something that the standard says anything about, and my reason for saying it may have been that as I was implementing the first pass of the shared subscription feature it seemed like the "correct" thing to do from an application's perspective.

I recommend assuming that I was incorrect unless someone finds a passage in the standard that explains how to handle sending messages to offline sessions in a shared subscription that agrees with my previous statement.

**Comment by kleunen** [comment]
Well. The broker is free to choose how to perform the load balancing. I guess choosing to exclude offline clients from the set of clients is a load balancing approach. And i would say it makes sense. Especially if you read another client may be chosen when the client disconnects during delivery of a qos 1 and 2 message

**Comment by redboltz** [comment]
I noticed that I misunderstood something about https://github.com/redboltz/mqtt_cpp/issues/716#issuecomment-717994904

It couldn't be a solution for https://github.com/redboltz/mqtt_cpp/issues/716#issuecomment-717991838

So topic filter first approach still has the problem.

**Comment by redboltz** [comment]
> Well. The broker is free to choose how to perform the load balancing. I guess choosing to exclude offline clients from the set of clients is a load balancing approach. And i would say it makes sense. 

Let me define the term `offline`. `offline` means the client is disconnected but session state exists.

* Both offline and online session could be a delivery target of shared subscription.
* Delivery strategy is out of spec. So broker can choose any strategy.
* Let's say `prefer online` is deliver to an online client if it exists, otherwise deliver to offline.
* I think that `prefer online` strategy is reasonable to be the default strategy.

> Especially if you read another client may be chosen when the client disconnects during delivery of a qos 1 and 2 message

**Disconnects during delivery** case is slightly different.

As you mentioned https://github.com/redboltz/mqtt_cpp/issues/716#issuecomment-718877168

The delivery target has already been decided. So waiting the reconnection of the same client is reasonable. QoS2
The class `endpoint` on mqtt_cpp does resend. It is existing mechanism. It is not relate to shared subscriptions.

> Qos2: If the Server is in the process of sending a QoS 2 message to its chosen subscribing Client and the connection to the Client breaks before delivery is complete, the Server MUST complete the delivery of the message to that Client when it reconnects [MQTT-4.8.2-4] as described in section 4.3.3. If the Client's Session terminates before the Client reconnects, the Server MUST NOT send the Application Message to any other subscribed Client [MQTT-4.8.2-5].

I think it is good. Session Expiration happens **after** delivery target is decided. The spec above is reasonable.

> Qos1: If the Server is in the process of sending a QoS 1 message to its chosen subscribing Client and the connection to that Client breaks before the Server has received an acknowledgement from the Client, the Server MAY wait for the Client to reconnect and retransmit the message to that Client. If the Client'sSession terminates before the Client reconnects, the Server SHOULD send the Application Message to another Client that is subscribed to the same Shared Subscription. It MAY attempt to send the message to another Client as soon as it loses its connection to the first Client.

However QoS1 is weird  for me.

Let's say the following subscription exists.

|client id|share name|topic filter|session expiry interval|
|---|---|---|---|
|c1| sn1| t1|1hour|
|c2|sn1| t1|infinity|

1. A publisher publish to t1 QoS1. 
2. The broker decided that the delivery target is c1.
3. The broker PUBLISH to c1.
4. Before PUBACK receive, c1 disconnected.
5. The broker (actually class endpoint) store the PUBLISH message for resend. And start 1hour timer.
6. When 1 hour passed, then the broker PUBLISH the message (1 hour ago) to c2.

I think that it is weird. So I sent mqtt-comment (OASIS) https://lists.oasis-open.org/archives/mqtt-comment/202005/msg00000.html

**Comment by kleunen** [comment]
Yes, it is weird because both clients have different session expiry intervals. I think in practice, this would not make much sense. And also, i think, no user would actually start using different session expiry intervals for different clients. But maybe there is a case where it does make sense. 

And I don't think the broker needs to make a "prefered online" approach. The user/clients can configure this themselves. If the client configure no session expiry or session expiry interval = 0, the session is terminated immediatly when the client disconnects. Queued messages for this session are republished to other clients on the shared topic. 

If the client does configure a session expiry interval, it will select a reasonable value in which it expects the client to reconnect. So it expects maybe a client will temporarily disconnect for a moment, but will reconnect within one minute, it will configure a expiry interval of maybe two minutes. The user will probably don't want the messages to wait for too long within the broker. 

All the broker has to do is load balance the messages over different sessions. These sessions maybe online or offline. But if the session goes offline and expires (immediately or after an interval), the broker just takes the messages from this session and republishes this again to other sessions on the shared topic.

**Comment by kleunen** [comment]
> Why the behavior of QoS1 and QoS2 are diffferent ?

I think behaviour of QoS1 and QoS2 is different because, QoS2 guarantees: delivered at most once. If the message was send to a client, and the client disconnects. You can not be certain if the message was delivered or not (maybe yes, maybe no). Therefore you can not send it to another client at another time. Otherwise, you may deliver the message twice in some cases.

**Comment by redboltz** [comment]
> > Why the behavior of QoS1 and QoS2 are diffferent ?
> 
> I think behaviour of QoS1 and QoS2 is different because, QoS2 guarantees exactly once. If the message was send to a client, and the client disconnects. You can not be certain if the message was delivered or not (maybe yes, maybe no). Therefore you can not send it to another client at another time. Otherwise, you may deliver the message twice in some cases.

I understand the policy some extent. Send twice violates "exactly once".
Send twice is worse than not send in QoS2 in the special case.

> For QoS2 you would use a very large session timeout, hours, or maybe even days or infinite. Because you do not want the message to get lost.

Session has been expired is exactly the special case.
I think it depends on application. I think that session expiry means "I don't want to receive resended messages after session has been expired.". It is reasonable.

I think that QoS2 policy of https://github.com/redboltz/mqtt_cpp/issues/716#issuecomment-718877168 is reasonable.

I expect that QoS1 should have consistency.
Even if QoS1, I think that session expiry means "I don't want to receive resended messages after session has been expired.". It is the same as QoS2.

I know at least once. 
When session has expired, QoS2 Exactly once is violated. Similarly, QoS1 At least once is violated. It is consistent.
I think that the combination of QoS1 and shared subscription and session expiration, the spec apply at least once meaning too much.

**Comment by kleunen** [comment]
> I mean the spec should allow message lost on QoS1 if already published but not received puback message and session expired case.

I understand and agree, but that would be something for the consortium behind MQTT specification to discuss :)

**Comment by redboltz** [comment]
I'm implementing share name first strategy. The algorithm contains one O(N) part. N is number of shared subscribers that have the same shared name. (Typically scale outed servers). I think that it is efficient enough.
I need a couple of weeks to send the PR.

**Comment by kleunen** [comment]
Excellent, looking forward to seeing the PR. More efficient algorithm can be added always later, or configurable algorithms :)

**Comment by kleunen** [comment]
Is this issue still relevant or can be closed now ?

**Comment by redboltz** [comment]
We can close it now.
