### ISSUE TITLE
boost 1.74+VS2019 x64 Compilation failed

### ISSUE THREAD

**Issue by MorningLight-Li** [redboltz/mqtt_cpp#719]
error message:
1>E:\CPlusPlusLIB\boost_1_74_0\boost/asio/impl/executor.hpp(104,15): error C2039: 'defer': is not a member of 'boost::asio::execution::any_executor<boost::asio::execution::context_as_t<boost::asio::execution_context &>,boost::asio::execution::detail::blocking::never_t<0>,boost::asio::execution::prefer_only<boost::asio::execution::detail::blocking::possibly_t<0>>,boost::asio::execution::prefer_only<boost::asio::execution::detail::outstanding_work::tracked_t<0>>,boost::asio::execution::prefer_only<boost::asio::execution::detail::outstanding_work::untracked_t<0>>,boost::asio::execution::prefer_only<boost::asio::execution::detail::relationship::fork_t<0>>,boost::asio::execution::prefer_only<boost::asio::execution::detail::relationship::continuation_t<0>>>'
.....
I track the template instantiation process to
BOOST_TYPE_ERASURE_MEMBER((MQTT_NS)(has_get_executor), get_executor, 0)
Did not find the problem,
It is estimated that it should be caused by some changes after asio 7.0,
Please help to fix the code so that it can run on the latest boost version。

**Comment by redboltz** [comment]
Similar issue was reported as #669 and fixed by #670 .
mqtt_cpp with boost 1.74 successfully compiled on Linux.

Could you try the latest master of mqtt_cpp ?

**Comment by MorningLight-Li** [comment]
It was my negligence. I checked out the error in V8.0 code compilation. Now I recompile using the master branch and it is no problem. Thank you, continue to use it below.
