### ISSUE TITLE
test_retained_map large_number_of_topics is not finished on CI

### ISSUE THREAD

**Issue by redboltz** [redboltz/mqtt_cpp#741]
After I re-enabled warnings, test_retained_map large_number_of_topics is not finished on CI.
https://github.com/redboltz/mqtt_cpp/blob/master/test/retained_topic_map.cpp#L209

I disabled the test as temporary.

@kleunen , could you check this ?

**Comment by kleunen** [comment]
i will have a look

**Comment by kleunen** [comment]
The issue is the number or log messages generated. I will create fix and cleanup some other small things i am seeing

**Comment by redboltz** [comment]
At first, I thought log outputs is the reason of the problem.
So I removed BOOST_TEST() in the loop and replaced to throw.
See https://github.com/redboltz/mqtt_cpp/blob/master/test/retained_topic_map.cpp#L225

But it still unfinihed.

Anyway, I will wait your PR.

**Comment by kleunen** [comment]
Ah yes. I was already thinking the throw was for this. Hmm. Some other debugging has been enabled and could slow down the test? Iterator validation ?

**Comment by redboltz** [comment]
> Ah yes. I was already thinking the throw was for this. Hmm. Some other debugging has been enabled and could slow down the test? Iterator validation ?

Good point.

```
 -DBOOST_MULTI_INDEX_ENABLE_SAFE_MODE -DBOOST_MULTI_INDEX_DISABLE_SERIALIZATION -DBOOST_MULTI_INDEX_ENABLE_INVARIANT_CHECKING
```

are defined 

https://github.com/redboltz/mqtt_cpp/blob/master/.github/workflows/gha.yml#L57
https://github.com/redboltz/mqtt_cpp/blob/master/.github/workflows/gha.yml#L60

You can insert

```cpp
#undef BOOST_MULTI_INDEX_ENABLE_SAFE_MODE 
...
```

Just before the test case.

I think that it is worth trying.

**Comment by kleunen** [comment]
Thank you. I will further investigate

**Comment by redboltz** [comment]
I noticed that my undef location is wrong.
It modifies boost multi_index header file behavior. So the undef should be placed before boost multi_index header file include.
For example the top of the test file.

**Comment by kleunen** [comment]
I tried enabling BOOST_MULTI_INDEX_ENABLE_SAFE_MODE and BOOST_MULTI_INDEX_ENABLE_INVARIANT_CHECKING on my local machine on the retained map test, it makes a huge difference in performance. I think this should be left enabled on the unit test, it is useful to test the retained map. I changed the test a little bit, to reduce the number of test entries, and perform some more useful test.

**Comment by kleunen** [comment]
See #742

**Comment by kleunen** [comment]
Close issue?
