### ISSUE TITLE
error: no such file or directory: 'mqtt_client_cpp.hpp'

### ISSUE THREAD

**Issue by pankajverma190** [redboltz/mqtt_cpp#782]
Hello everyone,

I am facing problem. I am trying to download and run no_tls_client.cpp and no_tls_server.cpp file but every time it is showing 

error: no such file or directory: 'mqtt_client_cpp.hpp'

But  'mqtt_client_cpp.hpp' file is present inside mqtt_cpp/include.

I am following every steps as per given instruction.
![Screenshot from 2021-01-18 16-00-27](https://user-images.githubusercontent.com/22872805/104904008-b7eae580-59a6-11eb-81e8-26378cea1c3a.png)

**Comment by pankajverma190** [comment]
![Screenshot from 2021-01-18 16-04-40](https://user-images.githubusercontent.com/22872805/104904184-e799ed80-59a6-11eb-9543-7ae3a56c17bc.png)

**Comment by redboltz** [comment]
It seems that include path is wrong.
If you want to add cloned github repository as include path, you need to do  `-I /home/pankaj/mqtt_cpp/include`.

In addition your boost library is too old. 
mqtt_cpp requires Boost Libraries 1.67.0 or later.

**Comment by pankajverma190** [comment]
Hi  Redboltz,
 
thanks for your reply.

I have tried as per your instruction

But still it is showing same error.

Boost i have 1.67.0

Tell me one thing that we NEED to install Doxygen software also. 

PFA
![Screenshot from 2021-01-18 17-30-36](https://user-images.githubusercontent.com/22872805/104913127-2cc41c80-59b3-11eb-91aa-b693d876203e.png)

**Comment by pankajverma190** [comment]
Hello ,

I am also sharing screen shot for your reference

Doxygen installed 
DOT missing problem solved

But still facing same problem.

Can you please share me the step how to compile and run code for no_tls_client.cpp and for no_tls_server.cpp.

Is am still missing some thing please let me know. It will help me a lot.
 
![Screenshot from 2021-01-18 17-46-21](https://user-images.githubusercontent.com/22872805/104914542-4d8d7180-59b5-11eb-9f96-a85ab92412b2.png)

**Comment by redboltz** [comment]
Doxygen is NOT mandatory. It is optional for make document.

You need to read g++ manual before you use mqtt_cpp.
See https://gcc.gnu.org/onlinedocs/gcc-10.2.0/gcc/

Your `-I` option missing the first `/`. In addition, don't set the include file.

**Comment by rakshita1006** [comment]
Hi,

I am also facing the same issue. I am using Boost 1.75.0 on Ubuntu 18.0 to compile my code.When I am trying to cake my project I get the following error:
Error 1:- **Could not find a package configuration file provided by "mqtt_cpp_iface"**  I tried to include lines in the Cmakelist.txt file(as given in the build instruction on the github site) but still get the same error. 

Could you please tell me in which Camkelist.txt I have to include these line (as there are many Cmakelist.txt) and what depedency need to be includede in Camkelist

Error 2:  **undefined reference to `main'**: I have included no_tls_client.cpp but main is missing.Do we need to include any other file or path?

Please, help me with the problem. For reference do find the attachment of errors.
![Error1](https://user-images.githubusercontent.com/36527418/105032127-5e54ea80-5a7c-11eb-97d2-e9515266f689.png)
![error 2](https://user-images.githubusercontent.com/36527418/105032149-69a81600-5a7c-11eb-9ded-d6c35863e069.png)

Thanks & Regards,
Rakshita

**Comment by redboltz** [comment]
Hi, @akshita1006 

Error1:

Perhaps delete build directory would solve the problem.

In the build directory. do `rm -rf *` then, `cmake ..`.

Error2:
Your `-I` option is invalid. The parameter should be directory, not file.

See https://github.com/redboltz/mqtt_cpp and gcc manual.

In addition, please don't attach screenshot. I can't search the text.

Please use https://guides.github.com/features/mastering-markdown/

**Comment by redboltz** [comment]
I have no idea. I guess that it is your environmental problem. So I don't have solution.

But https://github.com/redboltz/mqtt_cpp/blob/master/.github/workflows/gha.yml#L46-L76 could help you.
It is github actions CI build script. It uses ubuntu and works well.

**Comment by redboltz** [comment]
If you still interested in the issue, feel free to reopen it with additional information.

**Comment by pankajverma190** [comment]
Hello,

I have tried everything which you have suggested to us, but i am still getting same error.
