### ISSUE TITLE
Will Delay Interval

### ISSUE THREAD

**Issue by redboltz** [redboltz/mqtt_cpp#788]
The example broker doesn't support Will Delay Interval yet.

The spec is ambiguous for me.

https://docs.oasis-open.org/mqtt/mqtt/v5.0/os/mqtt-v5.0-os.html#_Toc3901062
>  The Server delays publishing the Client’s Will Message until the Will Delay Interval has passed or the Session ends, whichever happens first. If a new Network Connection to this Session is made before the Will Delay Interval has passed, the Server MUST NOT send the Will Message [MQTT-3.1.3-9].

Consider the following scenario:

1. c1 connected to the broker with WDI(Will Delay Interval) 10, and SEI(Session Expiry Interval) 0 (Equivalent to be omitted).
2. c1 disconnected forcibly.
3. The broker should publish the will immediately because the session ended.

I think that it is meaningless that WDI smaller than SEI because the session ends is always earlier than WDI passed.

Consider the following scenario:

1. c1 connected to the broker with WDI(Will Delay Interval) 10, and SEI(Session Expiry Interval) 20.
2. c1 disconnected forcibly.
3. c1 reconnected with CleanStart 0.
4. The broker shouldn't send the will even if WDI passed. (Sending the will is cancelled)

It is reasonable.

Consider the following scenario:

1. c1 connected to the broker with WDI(Will Delay Interval) 10, and SEI(Session Expiry Interval) 20.
2. c1 disconnected forcibly.
3. c1 reconnected with CleanStart 1.
4. The broker should publish the will immediately because the session ended. Is this right ?

"a new Network Connection to this Session is made before the Will Delay Interval has passed" is satisfied.
But "Session ends" by the new connection with CleanStart 1.
So "until the Will Delay Interval has passed or the Session ends" the latter condition is satisfied so the will should be send.
Is this right?

> Non-normative comment
> If a Network Connection uses a Client Identifier of an existing Network Connection to the Server, the Will Message for the exiting connection is sent unless the new connection specifies Clean Start of 0 and **the Will Delay is greater than zero**. If the Will Delay is 0 the Will Message is sent at the close of the existing Network Connection, and if Clean Start is 1 the Will Message is sent because the Session ends.

It is the most confusing comment.
What does "the Will Delay is greater than zero" mean?
The existing connection's WDI or the new connection's WDI?
If it is the new connection's WDI, it's contradicts the spec.

**Comment by kleunen** [comment]
Issue #340 and issue #516 are related.

Will expiry was implemented in PR #731, but this issue is related to will delay, which was not implemented in this PR.

**Comment by kleunen** [comment]
> What does "the Will Delay is greater than zero" mean?

I think this relates to the Will Delay setting of the new connection that is made. So, if a client reconnects, and on the reconnect the Will Delay is specified and is > 0 ...

**Comment by redboltz** [comment]
> Issue #340 and issue #516 are related.
> 
> Will expiry was implemented in PR #731, but this issue is related to will delay, which was not implemented in this PR.

Thanks. I know the issues. But the current broker design is slightly different from at that time. So WDI should be implemented form the scratch.

**Comment by redboltz** [comment]
> > What does "the Will Delay is greater than zero" mean?
> 
> I think this relates to the Will Delay setting of the new connection that is made. So, if a client reconnects, and on the reconnect the Will Delay is specified and is > 0 ...

From the location, it seems to be new Connection but perhaps **the** is for previously appeared word so it might be the previous WDI.

If it is the new connection's WDI, it is very weird. The will is the existing will in the context. I believed that the new WDI shouldn't be affected to the current (previous) will.

**Comment by redboltz** [comment]
What happened the following case?

1. c1 connected to the broker. SEI: 0, CleanStart any, WDI any.
2. Another c1 connected to the broker. SEI any, CleanStart 0 WDI 10.

https://docs.oasis-open.org/mqtt/mqtt/v5.0/os/mqtt-v5.0-os.html#_Toc3901059
> Each Client connecting to the Server has a unique ClientID. 

I think that there is not enough notation about online to online transition.
The practical implementation is the new connection wins.
So the first connection is closed due to the second connection.
The first connection's SEI is 0 so session ends. Then will should be sent.

**Comment by redboltz** [comment]
Another case:

1. c1 connected to the broker. SEI: 10, CleanStart any, WDI 10.
2. Another c1 connected to the broker. SEI any, CleanStart 0 WDI 0.

In this case, should will send at the step 2 ?
The new connection's WDI is not > 0.
I think it is very weird.

**Comment by kleunen** [comment]
> Another case:
> 
> 1. c1 connected to the broker. SEI: 10, CleanStart any, WDI 10.
> 2. Another c1 connected to the broker. SEI any, CleanStart 0 WDI 0.
> 
> In this case, should will send at the step 2 ?
> The new connection's WDI is not > 0.
> I think it is very weird.

In this case the will should not be send. The new connection overrides the settings of old connection.

This makes sense. The will should be sent when the device has died. That is what the will delay is for. To account for the fact the connection is temporarly lost. A reconnect can stop the will from being send. The will should be sent when the device or battery dies.

**Comment by kleunen** [comment]
It does not really make sense to change the will delay between connections.

It is either 0 and should be send immediatly when connection terminates

Or it is > 0 and a reconnect with no clean session within the delay period blocks the will from being sent.

**Comment by kleunen** [comment]
> If it is the new connection's WDI, it is very weird. The will is the existing will in the context. I believed that the new WDI shouldn't be affected to the current (previous) will.

Yes, I think you are right.

**Comment by kleunen** [comment]
But does it make sense to have SEI < WDI ? 
Session expires, but will has not been send yet. 
Is the will not part of a session ?

**Comment by redboltz** [comment]
Implemented by #839
