### ISSUE TITLE
Error: mqtt_client_cpp.hpp not found in directory

### ISSUE THREAD

**Issue by pankajverma190** [redboltz/mqtt_cpp#790]
Hello,

I have follow all the step as given.

mkdir build
cd build
cmake ..
make
make test

cmake ..   working properly
make   working fine
make test working fine

what is the next step i have to do

If i am running command
**g++ -std=c++14 -I/mqtt_cpp/include no_tls_client.cpp -I /home/pankaj/mqtt_cpp/include mqtt_client_cpp.hpp**
This id always showing find doesnot found in directory

I am trying to include mqtt_cleint_cpp.hpp file but it is always shoeing error

Boost version is correct

reference error is
 **error: no such file or directory: 'mqtt_client_cpp.hpp' #782**

**Comment by redboltz** [comment]
It is not mqtt_cpp issue.
Try google g++ manuall or tutorial.
Then learn how to use g++.

**Comment by redboltz** [comment]
make VERBOSE=1
outputs actual command. You can get information why make working fine.

**Comment by pankajverma190** [comment]
Hello Redbolitz,

I have complied code successfully by below command
clang++ -std=c++14 -D MQTT_NO_TLS -I path_to_mqtt_cpp no_tls_client.cpp -I/home/pankaj/mqtt_cpp/include -lboost_system -lpthread

Now i am running code by below command 
./a.out test.mosquitto.org 1883

I got below output

Connack handler called
Session Present: false
Connack Return Code: accepted
suback received. packet_id: 1
[client] subscribe result: success_maximum_qos_0
suback received. packet_id: 2
[client] subscribe result: success_maximum_qos_1
[client] subscribe result: success_maximum_qos_2
publish received. dup: no qos: at_most_once retain: no
topic_name: mqtt_client_cpp/topic1
contents: test1
publish received. dup: no qos: at_least_once retain: no
packet_id: 1
topic_name: mqtt_client_cpp/topic2_1
contents: test2_1
puback received. packet_id: 1
pubrec received. packet_id: 2
publish received. dup: no qos: exactly_once retain: no
packet_id: 2
topic_name: mqtt_client_cpp/topic2_2
contents: test2_2
pubcomp received. packet_id: 2
closed.

Is this correct output?

For subscriber side i am running " no_tls_server.cpp" file but i didn't get any output
Is i am running correct file for server(subscriber) side?

Please see and let me know 
Is i am going correct ?

**Comment by redboltz** [comment]
I think that the output you got on the client side is correct.
Your client connected to `test.mosquitto.org 1883` on the internet.

The server side program compiled from `no_tls_server.cpp` is just waiting the connection from the client. So no output.

If you run the server as `./server 12345` and the client as `./a.out 127.0.0.1 12345`, then you got both output.

**Comment by pankajverma190** [comment]
Hello Redboltz,

Thanks for your valuable answer and support.

I got the output both side on localhost.
Below is the output 

CLIENT SIDE output

Connack handler called
Session Present: false
Connack Return Code: accepted
suback received. packet_id: 1
[client] subscribe result: success_maximum_qos_0
suback received. packet_id: 2
[client] subscribe result: success_maximum_qos_1
[client] subscribe result: success_maximum_qos_2
publish received. dup: no qos: at_most_once retain: no
topic_name: mqtt_client_cpp/topic1
contents: HELLO WORLD MQTT
publish received. dup: no qos: at_least_once retain: no
packet_id: 1
topic_name: mqtt_client_cpp/topic2_1
contents: test2_1_PANKAJ
puback received. packet_id: 1
publish received. dup: no qos: exactly_once retain: no
packet_id: 2
topic_name: mqtt_client_cpp/topic2_2
contents: test2_2_MQTT
pubrec received. packet_id: 2
pubcomp received. packet_id: 2
closed.


Server Side OUTPUT

[server] client_id    : cid1
[server] username     : none
[server] password     : none
[server] clean_session: true
[server] keep_alive   : 0
[server]subscribe received. packet_id: 1
[server] topic_filter: mqtt_client_cpp/topic1 qos: at_most_once
[server]subscribe received. packet_id: 2
[server] topic_filter: mqtt_client_cpp/topic2_1 qos: at_least_once
[server] topic_filter: mqtt_client_cpp/topic2_2 qos: exactly_once
[server] publish received. dup: no qos: at_most_once retain: no
[server] topic_name: mqtt_client_cpp/topic1
[server] contents: HELLO WORLD MQTT
[server] publish received. dup: no qos: at_least_once retain: no
[server] packet_id: 1
[server] topic_name: mqtt_client_cpp/topic2_1
[server] contents: test2_1_PANKAJ
[server] publish received. dup: no qos: exactly_once retain: no
[server] packet_id: 2
[server] topic_name: mqtt_client_cpp/topic2_2
[server] contents: test2_2_MQTT
[server] puback received. packet_id: 1
[server] pubrec received. packet_id: 2
[server] pubrel received. packet_id: 2
[server] pubcomp received. packet_id: 2
[server] disconnect received.
[server] error: Bad file descriptor
accept


This output is for Localhost. 
If i want to send data to Mosquitto or any other broker. Can we do that from same code or i have to write code for it? 
what is the process to communicate from client(publisher) to broker and broker to subscriber, using mosquitto or other broker?

Once again thanks for your support.

**Comment by redboltz** [comment]
It seems that your problem has been solved.
I close the issue.
If you have further issues, please create a new issue.
