### ISSUE TITLE
Timeout for not received puback/pubrec/pubcomp

### ISSUE THREAD

**Issue by Stannieman** [redboltz/mqtt_cpp#791]
Is there some built in way to have a timeout for when the client never receives a puback/pubrec/pubcomp from the broker?Or some other way to handle this scenario?
I think this can happen when either the broker never receives our publish OR the broker is faulty and doesn't send the response at all.

For example I think a common thing is that you publish a message and then somehow keep track of it. Then on puback know the broker got it and you can stop keeping track. But in case no puback comes you never know it failed. I'm thinking of some timeout mechanism here. Do I have to implement that myself or is there something built in?

**Comment by redboltz** [comment]
> Is there some built in way to have a timeout for when the client never receives a puback/pubrec/pubcomp from the broker?

No.

> Or some other way to handle this scenario?

You need to implement by yourself. I think that all handlers are provided by mqtt_cpp to implement it.

> I think this can happen when either the broker never receives our publish OR the broker is faulty and doesn't send the response at all.

In this scenario, setting keep alive is helpful. The client send pingreq packet, but broker doesn't reply pingresp, so timeout happens.

You can set the timeout using the following functions.
https://github.com/redboltz/mqtt_cpp/blob/master/include/mqtt/endpoint.hpp#L4753

If the broker has some bug that the broker can't return only `puback`, `pubrec`, and `pubcomp`, the the solution doesn't work but it is not practical scenario.

> For example I think a common thing is that you publish a message and then somehow keep track of it. Then on puback know the broker got it and you can stop keeping track. But in case no puback comes you never know it failed. I'm thinking of some timeout mechanism here. Do I have to implement that myself or is there something built in?

**Comment by kleunen** [comment]
Also, if you use QoS1 or QoS2, at a certain point in time, the broker will receive the message. There is no need to implement a timeout yourself. If your client stays connected, a TCP retry will handle the retrying of the message. If the client disconnects and you perform a reconnect, QoS1 and QoS2 will be resend by the mqtt_cpp library when connected again. 

Please have a look at this example:
[long lived client](https://github.com/redboltz/mqtt_cpp/blob/master/example/long_lived_client.cpp)

That is how MQTT was designed.

**Comment by Stannieman** [comment]
My main concern was when the broker doesn't reply like it should. It's a bit strange that the client should have full trust in the broker even though they could be different things on different machines etc. But if the protocol is designed in such a way they I guess I'll have to assume my broker behaves.
