### ISSUE TITLE
make test failed

### ISSUE THREAD

**Issue by rakshita1006** [redboltz/mqtt_cpp#792]
Hi,

I was trying to build the mqtt_cpp project. I am using Ubuntu 18.0 and Boost 1_67_0. I have following questions for building projects

1) When I did the **cmake ..**, the configuration and generation of cmake was done but it is showing **-Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed**
Will this effect my build?

Below is my output for cmake

The C compiler identification is GNU 7.5.0
-- The CXX compiler identification is GNU 7.5.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Setting minimum C++ standard to C++14
-- TLS disabled
-- WebSocket disabled
-- Always send reason code enabled
-- UTF8String check enabled
-- Using boost::variant instead of std::variant
-- Using boost::optional instead of std::optional
-- Using boost::string_view instead of std::string_view
-- Using boost::any instead of std::any
-- Using boost::shared_ptr<char []> instead of std::shared_ptr<char []>
-- std::tuple<std::any> workaround for libstdc++ enabled
-- Dynamically linking with Boost
-- Dynamically linking with Openssl
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- **Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed**
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Logging disabled
-- Found Boost: /usr/local/lib/cmake/Boost-1.75.0/BoostConfig.cmake (found suitable version "1.75.0", minimum required is "1.67.0") found components: system date_time program_options 
-- Tests enabled
-- Found Boost: /usr/local/lib/cmake/Boost-1.75.0/BoostConfig.cmake (found suitable version "1.75.0", minimum required is "1.67.0") found components: unit_test_framework 
-- Examples enabled
-- Found Doxygen: /usr/bin/doxygen (found version "1.8.13") found components: doxygen dot 
-- Configuring done
-- Generating done
-- Build files have been written to: /home/rakshita/mqtt_PubSub/build

2) When I tried to do "**make test**" my test failed with message "28 test failed out of 39". Please let me know what I am doing wrong.
Below is my output:

28% tests passed, 28 tests failed out of 39

Total Test time (real) =   1.92 sec

The following tests FAILED:
	  1 - st_connect (Failed)
	  3 - st_as_buffer_sub (Failed)
	  4 - st_topic_alias_recv (Failed)
	  5 - st_as_buffer_pubsub (Failed)
	  6 - st_shared_sub (Failed)
	  7 - st_pubsub_1 (Failed)
	  8 - st_sub (Failed)
	  9 - st_pubsub_2 (Failed)
	 10 - st_pubsub_no_strand (Failed)
	 11 - st_as_buffer_async_pubsub_1 (Failed)
	 12 - st_multi_sub (Failed)
	 13 - st_as_buffer_async_pubsub_2 (Failed)
	 14 - st_async_pubsub_1 (Failed)
	 15 - st_resend (Failed)
	 16 - st_retain_1 (Failed)
	 17 - st_resend_new_client (Failed)
	 18 - st_retain_2 (Failed)
	 19 - st_will (Failed)
	 20 - st_offline (Failed)
	 21 - st_manual_publish (Failed)
	 22 - st_async_pubsub_2 (Failed)
	 23 - st_issue_749 (Failed)
	 24 - st_broker_offline_message (Failed)
	 25 - st_remaining_length (Failed)
	 26 - st_utf8string_validate (Failed)
	 27 - st_resend_serialize (Failed)
	 28 - st_length_check (Failed)
	 29 - st_resend_serialize_ptr_size (Failed)
Errors while running CTest
Makefile:104: recipe for target 'test' failed
make: *** [test] Error 8

Kindly, help me with the solution.

Thanks

**Comment by redboltz** [comment]
I couldn't reproduce the issue.
If you still have the issue, please post the detail information.

**Comment by redboltz** [comment]
Closed due to no response.
