### ISSUE TITLE
Shared Subscription?

### ISSUE THREAD

**Issue by xerdink** [redboltz/mqtt_cpp#803]
Hi, thank you for your great work.

I run example broker but cannot make shared subscriptions work?

Also, I couldn't figure out [tests](../blob/master/test/system/st_shared_sub.cpp)

**Comment by redboltz** [comment]
You can use shared subscriptions functionality on the broker.
See https://docs.oasis-open.org/mqtt/mqtt/v5.0/os/mqtt-v5.0-os.html#_Toc3901250

Note that the broker is experimental feature.
https://github.com/redboltz/mqtt_cpp#experimental-feature
