### ISSUE TITLE
Compile with Clang 

### ISSUE THREAD

**Issue by axbusch** [redboltz/mqtt_cpp#805]
Did anybody manage to compile this with clang? I can't because of errors (in gcc these errors are just warnings)

Or am i doing something wrong?

**Comment by redboltz** [comment]
https://github.com/redboltz/mqtt_cpp/blob/master/.github/workflows/gha.yml#L76-L79
https://github.com/redboltz/mqtt_cpp/runs/2166497081?check_suite_focus=true
Build linux 0..3 is compiled by clang.

**Comment by axbusch** [comment]
Hi,

ok i'm using v7.0.1 and the problem was
`set_protocol_version(size_t version)`
i manually changed it to 
`set_protocol_version(protocol_version version)`

and compiling works.
In the 9.0 release this is already fixed

**Comment by redboltz** [comment]
It has been fixed v8.0.0.
https://github.com/redboltz/mqtt_cpp/blob/v8.0.0/include/mqtt/endpoint.hpp#L4020
