### ISSUE TITLE
can client be publisher and subscriber at the same time ?

### ISSUE THREAD

**Issue by mgoutham** [redboltz/mqtt_cpp#807]
Hi,

I had a requirement where client had to act as subscriber and publisher to different topics at same time.
Whenever the subscribed topic is received then client had to publish a message to different topic to the Broker. so, I had placed publisher in a callback (i.e. set_publish_handler) as soon as the client receives the publication but during my testing, I found the client is not receiving any messages after the first message received therfore i had a doubt i.e. can a client act as publisher and subscriber at the same time ? does publishing a message in a callback cause deadlock (found on internet) I don't think so because examples show publication is part of a callback. could you please let me know what causes the client not to receive messages after the first message in this scenario?

**Comment by redboltz** [comment]
> can client be publisher and subscriber at the same time ?

Yes,

For example, you can replace the following `disconnect()` with 
```cpp
c->publish("other_topic", "your message", MQTT_NS::qos::at_least_once);
```
https://github.com/redboltz/mqtt_cpp/blob/master/example/no_tls_client.cpp#L119

**Comment by mgoutham** [comment]
@redboltz - firstly, Thanks for the very prompt response and sorry i wasn't able to reply since I was trying to setup this on another machine and it's taking longer. will try to reply to this asap.

**Comment by mgoutham** [comment]
Thank You! it did work, had to do with wrapper written on this lib.
