### ISSUE TITLE
use_certificate_file: no start line

### ISSUE THREAD

**Issue by JensInc** [redboltz/mqtt_cpp#813]
In a part using ` std::shared_ptr<MQTT_NS::callable_overlay<
      MQTT_NS::sync_client<MQTT_NS::tcp_endpoint<MQTT_NS::tls::stream<as::ip::tcp::socket>, as::io_context::strand>>>>
      c`   (from [example tls_client](https://github.com/redboltz/mqtt_cpp/blob/master/example/tls_client.cpp)):

When using boost ssl::context::use_certificate_file
```
this->c->get_ssl_context().use_certificate_file(path_to_file_as_std::string, boost::asio::ssl::context::pem);
```
 I got the error `use_certificate_file: no start line`.

Loading the CA via load_verify_file and the private key with use_private_key_file works and I can communicate with a self build mqtt broker also built with mqtt_cpp.

Using the associated *crt file (pem format) and try to communicate to a mosquitto broker I got the error mentioned above. Using the same key file and *crt file in a python program I can communicate with e..g the mosquitto broker.

**Comment by redboltz** [comment]
Here is a client side certificate example.
https://github.com/redboltz/mqtt_cpp/blob/master/example/tls_both_client_cert.cpp

**Comment by JensInc** [comment]
It is the same code (line 392 to 394) - just the order is different:  `use_certificate_file,  use_private_key_file,  load_verify_file` instead of `load_verify_file, use_private_key_file, use_certificate_file` .

I will try. But for me it seems that `use_certificate_file` is complaining about the file format. I have already tried p12. But the file I am using should be a valid pem-file. It has been created via: 
```
   openssl req -newkey rsa:4096 -nodes -sha256 -subj "$SUBJECT_CLIENT" -out client_"$number".csr -keyout client_"$number".key 
   openssl x509 -req -sha256 -passin pass:"$3" -in client_"$number".csr -CA ca.crt -CAkey ca.key -CAcreateserial -out client_"$number".crt -days 730
#openssl pkcs12 -export -nodes -in client_"$number".crt -inkey client_"$number".key -out client_"$number".p12 -passout pass:
```
and has got a `-----BEGIN CERTIFICATE-----` ... `-----END CERTIFICATE-----` structure.

P.S.:
Sorry for contacting you. As a said I guess it is either a boost problem or a problem of key/certificate creation. As there was no answer in StackOverflow and I have not found any contact option at the boost project I have created this issue here. Maybe you can help anyway.

**Comment by JensInc** [comment]
As expected: Changing the order of `use_certificate_file, use_private_key_file, load_verify_file` did not help.

**Comment by JensInc** [comment]
Finally the certificate format matches.
