### ISSUE TITLE
How to integrate mqtt_cpp as a CMake Module rather than external build?

### ISSUE THREAD

**Issue by DavidAntliff** [redboltz/mqtt_cpp#837]
Working with 07c70974c481809e8f1aff0725a77a83c62c8101.

I'm attempting to integrate this project as a "Module" in an existing CMake project, _rather than separately compiling/installing it first_. I'm doing this to avoid adding an explicit build step to the process, and it is not an uncommon way to incorporate full and header-only libraries into a project. I also want it to use the version of Boost I already have available via Conan when building my main project (which is not installed on the host system - trying to avoid that).

The instructions to use `find_package(mqtt_cpp_iface REQUIRED)` does not work (even after setting `CMAKE_MODULE_PATH`) because there is no suitable file found (e.g. `Findmqtt_cpp_iface.cmake`) in this project's `cmake` directory, which is what `find_package` looks for in "Module" mode. I understand that one of these files is created at install time and is called `mqtt_cpp_ifaceTargets.cmake`. The other is created at cmake time and is called `mqtt_cpp_ifaceConfig.cmake`.

Ok, so instead I tried this in my top-level CMakeLists.txt:

```
add_subdirectory(mqtt_cpp EXCLUDE_FROM_ALL)
include(${CMAKE_BINARY_DIR}/mqtt_cpp/mqtt_cpp_ifaceConfig.cmake)
```

This fails because `mqtt_cpp_ifaceTargets.cmake` doesn't exist yet.

So `mqtt_cpp_ifaceConfig.cmake` is created by mqtt_cpp's CMakeLists.txt file when it is included by `add_subdirectory`, but `mqtt_cpp_ifaceTargets.cmake` is not created because the `install` target is not executed.

Is it intended that this library be used in this way? If so, can someone please provide advice on how to integrate it properly?

**Comment by igor-epam** [comment]
Do you have any plans to make conan header only package?

**Comment by rsnitsch** [comment]
> Just add mqtt_cpp as a subdirectory in cmake, and link against the library that gets defined (mqtt_cpp_iface)
> 
> That will create an interface library that has the include directory set up properly without having to do anything extra.

Thank you, this worked for me. Code in `CMakeLists.txt`:

    set(MQTT_DIR ${CMAKE_SOURCE_DIR}/../dependencies/mqtt_cpp)
    add_subdirectory(${MQTT_DIR} ${MQTT_DIR}/build)
    target_link_libraries(myProjectName LINK_PUBLIC mqtt_cpp_iface)
