### ISSUE TITLE
Question: what is the intended mechanism for integration of synchronous API with application?

### ISSUE THREAD

**Issue by DavidAntliff** [redboltz/mqtt_cpp#838]
What is the intended mechanism for using the synchronous part of the library when the application can provide data to publish at any time, or receive published data at any time?

For example, I have an application that generates a lot of outgoing data, destined for many MQTT topics. This data is generated elsewhere in the program but could be serialised and passed to the MQTT subsystem via a queue.

In addition, a reasonably large number of incoming publications are expected that need to find their way back into the application.

One idea I had was to run the whole mqtt_cpp component in its own thread: i.e. set up all the callbacks, and then run `ioc.run_for(0)` (to avoid blocking) in an infinite loop. Within this loop the head of the incoming queue can be polled and any pending data sent as a publish. Then in the publish_handler, any incoming published data can be posted into another queue (perhaps one per-topic or per-subsystem) that something elsewhere in the program can consume.

I'm also not sure how to handle dynamically creating and removing subscriptions.

Is the client thread-safe? Can I call `client->publish` or `client->subscribe` from another thread?

So I'm looking for guidance on how to integrate this with the synchronous part of the mqtt_cpp API, please.

**Comment by DavidAntliff** [comment]
> After disconnection, you can still use socket.

Are you aware of any mechanism in ASIO to detect that the connection is disconnected / closed? I read that using the socket is not portable. For now I am just raising a bool flag in close_handler.

Thank you again for all your help with this - I am hopeful that this discussion might help future users of your library too.

**Comment by redboltz** [comment]
> > After disconnection, you can still use socket.
> 
> Are you aware of any mechanism in ASIO to detect that the connection is disconnected / closed? 

No. 
As I mentioned https://github.com/redboltz/mqtt_cpp/issues/838#issuecomment-906123447 , `client::socket()` returns `tcp_endpoint` (it depends on your client type), not `boost::;asio::ip::tcp::socket`. It works well with strand.

Connecting status is checked here:
https://github.com/redboltz/mqtt_cpp/blob/34c9bb628752084d927def5dbb4346c0b77d71ae/include/mqtt/endpoint.hpp#L10242-L10251

**Comment by DavidAntliff** [comment]
Thanks again, I'll close this issue now as I've got it mostly working except for one unresolved thing which I'll open a new issue for.
