### ISSUE TITLE
Broker sends QoS level 2

### ISSUE THREAD

**Issue by DinoMe** [redboltz/mqtt_cpp#843]
Just saw that the broker is sending QoS level 2 (exactly once) with connack.
This is a protocol error per MQTT protocol description https://docs.oasis-open.org/mqtt/mqtt/v5.0/os/mqtt-v5.0-os.html#_Toc3901084.
> Followed by a Byte with a value of either 0 or 1. It is a Protocol Error to include Maximum QoS more than once, or to have a value other than 0 or 1. If the Maximum QoS is absent, the Client uses a Maximum QoS of 2.

So this line has to removed to comply to the protocol.
https://github.com/redboltz/mqtt_cpp/blob/0b94a1aa8c3019a38bf954840809e303bfbbfec2/include/mqtt/broker/broker.hpp#L1061

Thanks for considering.

**Comment by redboltz** [comment]
Thank you for reporting the issue. 
I will fix it soon.

**Comment by DinoMe** [comment]
Great. Thanks a lot for the quick fix!
