### ISSUE TITLE
Program_options not necessary

### ISSUE THREAD

**Issue by ineffective** [redboltz/mqtt_cpp#858]
Correct me if I'm wrong, but it seems that `boost::program_options` is not necessary to build anything using `mqtt_cpp`, it seems that it is only required when building examples? I'm trying to build `deb` package for `mqtt_cpp` from tag  `v11.1.0` for our internal use and I ran into an issue where `mqtt_cpp` requires` boost::program_options` - we have custom build of `boost-1.71.1` and `boost::program_options` library is not included in this build.

I tried doing this:

```diff
diff --git a/CMakeLists.txt b/CMakeLists.txt
index e30f2a7..72f2c1a 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -123,10 +123,10 @@ FIND_PACKAGE (Threads REQUIRED)

 IF (MQTT_USE_LOG)
     MESSAGE (STATUS "Logging enabled")
-    FIND_PACKAGE (Boost 1.67.0 REQUIRED COMPONENTS system date_time log filesystem thread program_options)
+    FIND_PACKAGE (Boost 1.67.0 REQUIRED COMPONENTS system date_time log filesystem thread)
 ELSE ()
     MESSAGE (STATUS "Logging disabled")
-    FIND_PACKAGE (Boost 1.67.0 REQUIRED COMPONENTS system date_time program_options)
+    FIND_PACKAGE (Boost 1.67.0 REQUIRED COMPONENTS system date_time)
 ENDIF ()
````

And it seems that everything works. Is it possible to apply this change in future releases?

**Comment by jonesmz** [comment]
> `boost::program_options` is not necessary to build anything using `mqtt_cpp`, it seems that it is only required when building examples

this is correct.

**Comment by jonesmz** [comment]
the cmakelist should really be gating the program options library search behind whether the examples are being built.

**Comment by redboltz** [comment]
Thank you all! @ineffective could you try #859 ?

**Comment by ineffective** [comment]
@redboltz Hi, thank you for fast reaction and sorry for late response (in comparison). It seems that yes, everything works without problems. I'm closing this issue. Thank you!
