### ISSUE TITLE
Problems with sending over WiFi

### ISSUE THREAD

**Issue by ineffective** [redboltz/mqtt_cpp#861]
Hello, I'm using synchronous client to send messages to the server. I'm using persistent connection, I mean I have single connection established for all messages. I have a problem with my service when wifi signal is weak. In such cases client hangs for very long time and only after ~13-15 minutes terminates with information "No route to host" if and only if signal does not get better. This is actually good scenario, because at least client terminates. On the other hand if signal gets better, then messages is not sent anyhow and call to "publish()" hangs indefinitely (probably, our technicians usually restart service in this case after client contacts us - it usually takes 4-5 hours, the longest we have seen is ~2 days (weekend)).

Is there some mechanism that can cause such behavior? I tried to find similar issue but found nothing, but maybe it was fixed in some version > v7.0.1 and <= v11.1.0?

If there is no known problem with it, how should I proceed? Can I set timer right before sending and terminate connection after it expires? I don't really know library internals and boost::asio isn't exactly the easiest library to use, so I'm not certain how call to "publish()" on synchronous client works - I suppose timer's handler will be fired only after call to "publish()" returns, so I will achieve nothing. So maybe I should try to rewrite our service to use async client? I don't think this is very hard but I might be grossly underestimating this endeavour.

Client software uses mqtt_cpp v7.0.1 (probably with patch preventing packet_id_t exhaustion - or maybe it is already present in v7.0.1) so I can't turn on logging as there is none - this is one of the reasons why I'm trying to upgrade to v11.1.0.

**Comment by ineffective** [comment]
Sorry, I completely misunderstood some things - in fact call to publish() returns almost immediately. This probably means that I can safely add deadline_timer that will wait for `pubcomp` or `pubrec` (which one is better? I guest `pubcomp`?) and restart the service. Still I wonder why my service does not disconnect earlier and wait ~15 minutes before reporting "No route to host" (instead of timeout).

**Comment by ineffective** [comment]
> I recommend that detecting blocked location using debugger.

I'm trying to do it, but it is hard to do it from command line via serial line :) I will try to do it and come back to you - maybe there is some way to improve this great library :)

**Comment by redboltz** [comment]
This could be a hint.
mqtt_cpp uses https://www.boost.org/doc/libs/1_77_0/doc/html/boost_asio/reference/ip__basic_resolver/resolve/overload4.html
 to resolve host name. This is a blocking API. It might be wait for a long time until the name server returns result. I don't checked. You can check its implementation.

**Comment by ineffective** [comment]
> This could be a hint.
> mqtt_cpp uses https://www.boost.org/doc/libs/1_77_0/doc/html/boost_asio/reference/ip__basic_resolver/resolve/overload4.html
> to resolve host name. This is a blocking API. It might be wait for a long time until the name server returns result. I don't checked. You can check its implementation.

I don't think this is it, as connection is already established - but it can be a hint if `mqtt_cpp` internally tries to reconnect (possibly few times) if connection is lost. Is such logic implemented in the library? If yes then where can I check an implementation?

**Comment by redboltz** [comment]
No. But if network status is bad, then disconnected. In this case, on_error (set_error_handler callback) is called.
But not automatically reconnect. Reconnect is always from your application code.

**Comment by ineffective** [comment]
I were unable to determine why timeout is so big, so we settled for different solution - after sending message we start timer and reset it in `pubcomp` handler. Performance is slightly worse than it was (obviously), but it is still very good. As far as I understand it is possible only because we use `qos::exactly_once` - never the less it works for us. I'm closing this issue.
