### ISSUE TITLE
Endpoint rejecting correlation_data that contain zeros

### ISSUE THREAD

**Issue by DinoMe** [redboltz/mqtt_cpp#888]
Hi again,

Currently client and server / broker reject messages with a correlation_data property that contains zeros.
The endpoint rejects such a message with a "malformed packet error".

This is because the correlation_data property is processed as a string.
https://github.com/redboltz/mqtt_cpp/blob/a292c9c21ce7af627134769d25dc65af5dfb7a8d/include/mqtt/endpoint.hpp#L6400-L6404

Instead it should be processed as binary data.
```
        case v5::property::id::correlation_data: {
            process_binary(
                force_move(self),
                force_move(session_life_keeper),
                force_move(buf),
```

Maybe I'm wrong here but I didn't find any limitation on correlation data in the MQTT protocol.
https://docs.oasis-open.org/mqtt/mqtt/v5.0/os/mqtt-v5.0-os.html#_Toc3901115

Thanks for considering,
Dino

**Comment by redboltz** [comment]
Thank you for reporting the issue.
The issue should be fixed by #889.
