### ISSUE TITLE
Client unsubscribe will unsubscribe all clients in example server 

### ISSUE THREAD

**Issue by chrisg89** [redboltz/mqtt_cpp#912]
I observed that the example code for the server (all variants) is broken. 

Expectation:
Client A subscribes to topic 'X'
Client B subscribes to topic 'X'
Client C subscribes to topic 'X'
Client C unsubscribes to topic 'X'
Client A publishes to topic 'X'
Client A and Client B receive publish notification for topic 'X'

Actual:
Client A subscribes to topic 'X'
Client B subscribes to topic 'X'
Client C subscribes to topic 'X'
Client C unsubscribes to topic 'X'
Client A publishes to topic 'X'
No client receives the publish notification for topic 'X'

Possible root cause:
The `unsubscribe` handler deletes all entries in the `subs (multi_index_container)` that match the topic name. Instead, it should only delete entries for the client which initiated the unsubscribe.

**Comment by redboltz** [comment]
Thank you for reporting the issue. The issue should be fixed by #913 .
