### ISSUE TITLE
Support more modular dependency builds via `ASIO_STANDALONE` etc

### ISSUE THREAD

**Issue by CraigHutchinson** [redboltz/mqtt_cpp#915]
I have not used `mqtt_cpp` yet and was looking to use this until it needed Boost being pulled into the build. I am not in a place to pull it in at moment and would be nice if there was a more modular build support.

For example see http://think-async.com/Asio/AsioStandalone where  `ASIO_STANDALONE` is documented. Maybe the same can apply to any other boost dependencies as would really help with wider adoption of this project.

**Comment by kleunen** [comment]
mqtt_cpp requires more boost modules than asio, also log and program_options are used, beast, system, date_time, filesystem, thread. Ubuntu provides modularized boost builds, which you can install using apt-get. Also vcpkg provides installing modularized builds. So there are options to install parts of boost that are needed by mqtt_cpp.

**Comment by CraigHutchinson** [comment]
Thanks @kleunen , I've taken a look briefly and it all looks feasible. From what I understand all of the boost modules are now provided separately such as Asio, Beast, and System etc. At the moment I gather mqtt_cpp is depending on the Super-Build of Boost in the Cmake config.  It may not be a significant amount of change to add an alternative check for the module-based dependency as an option. If I had more time on my hands at present I would check.

At this time I have gone with Mosquitto due to ease of integration. I much prefer the design of mqtt_cpp however and maybe will come back to this in future. If it were possible to simplify mqtt_cpp integration into the build it woudl be great so I will plan to look into this sometime in future and hopefully make a pull-request if all goes well!

**Comment by kleunen** [comment]
yes, if you can make a pull request, that would be helpful.
