### ISSUE TITLE
`get_client_id()` in the server's connection handler will return empty ("") string

### ISSUE THREAD

**Issue by chrisg89** [redboltz/mqtt_cpp#916]
**In an older version of `mqtt_cpp` (V3.0.0):**
A call to `ep.client_id()` in the server's `connect handler` returns a string containing the connected client id.

**In the current version of `mqtt_cpp` (V12.0.0):**
A call to `ep->get_client_id()` in the server's `connect handler` returns an empty string.

Although the user application could store the clientId, it is very convenient to have it stored in the ep and retrievable via `get_client_id()`.

This appears to me like a possible bug. Feel free to close if this is by design.

**Comment by redboltz** [comment]
Thank you for reporting the issue. The issue should be fixed by #917
