### ISSUE TITLE
#925 cause CI timeout on Windows

### ISSUE THREAD

**Issue by redboltz** [redboltz/mqtt_cpp#928]
https://dev.azure.com/redboltz/redboltz/_build/results?buildId=2355&view=logs&j=b02611a8-afa6-57f9-a609-f526117c2f48&t=2a20281f-1fda-53bb-a383-d51a668378ba&l=974

**Comment by redboltz** [comment]
I noticed it after the PR merged.

**Comment by redboltz** [comment]
CI on #926 (it contains #925) , the issue isn't observed. The issue may environmental issue on CI.

**Comment by HINEOWAKEUP** [comment]
> https://dev.azure.com/redboltz/redboltz/_build/results?buildId=2355&view=logs&j=b02611a8-afa6-57f9-a609-f526117c2f48&t=2a20281f-1fda-53bb-a383-d51a668378ba&l=974

How can I have view access permit for this link?

**Comment by HINEOWAKEUP** [comment]
Do you know how to use Azure DevOps to build you source hosted on Azure?

**Comment by redboltz** [comment]
I accessed the URL ang got "Build not found" message.
It seems that azure devops pipelines has become storing only recent 8 logs.

I close this issue because the issue no longer reprocuded and the log information has been lost.

If azure devops pipelines related issue would be found, then please report it as a new issue and copy paste the log (focused on the issue). URL would be removed soon.
