### ISSUE TITLE
Mocking MQTT sync_client publish calls

### ISSUE THREAD

**Issue by alex-saoulis** [redboltz/mqtt_cpp#936]
I am currently looking at adding tests to a programme that uses this library. One aspects of the tests would be to mock out the client->publish method so that I can inspect the arguments during test time. One obvious way to do this would be to rely on a virtual publish function to override through a derived class:

``` 
using mqttClient = mqtt::callable_overlay<mqtt::sync_client<mqtt::tcp_endpoint<boost::asio::ip::tcp::socket, mqtt::strand>>>;

class mqttClientMock : public mqttClient {
   public:
      std::string m_topic{};
      std::string m_message{};
      template <typename T>
      void publish(std::string topic, std::string message, T mqttFlag){
         m_topic = topic;
         m_message = message;
      }
};
```

but this method doesn't work: `a 'final' class type cannot be used as a base class`. 

Is there a way to mock mqtt::sync_client::publish directly before the callable overlay step? Let me know if you have any suggestions; if there is no workaround I will just need to templatize my code to accept my own mock class that doesn't inherit from the mqtt library.

**Comment by redboltz** [comment]
callable_overlay is for set_xxx_handler() functions. 
endpoint has virtual on_xxx event handling functions.
But publish is not designed as  virtual functions. It shouldn't be overriedn.
If you want to check the arguments for publish, then you need to write a wrapper of publish function.
The functions checking the parameters and then delegate the parameters to the original publish function.

**Comment by alex-saoulis** [comment]
Thanks for such a quick response!

> But publish is not designed as virtual functions. It shouldn't be overriden.

That makes sense - I won't try to override it. I've realised that I can call `client->publish` while not connected to anything during my tests and it won't cause an issue, so I will use your suggestion of writing a wrapper function and checking the arguments for each publish call.
