### ISSUE TITLE
Update vcpkg port

### ISSUE THREAD

**Issue by Tradias** [redboltz/mqtt_cpp#939]
The vcpkg port of mqtt_cpp is currently at 12.0.0. Let's update it to 13.0.0.

**Comment by redboltz** [comment]
I'm not sure how it works. I don't do anything at 12.0.0 and before.
I guess that someone do something (send PR to vcpkg github??).
Could you do this?

**Comment by dempo93** [comment]
@redboltz @Tradias 
Hi, I just opened the pr
https://github.com/microsoft/vcpkg/pull/25162

**Comment by Tradias** [comment]
Vcpkg port update has been merged. Thank you dempo93
