### ISSUE TITLE
set_v5_pubrel_handler has no impact in example cli

### ISSUE THREAD

**Issue by pauljohnston2009** [redboltz/mqtt_cpp#955]
using the example_cli I am unable to get the pubrel handler to be invoked (qos 0 and 1 seem to work fine, and hit the correct handlers)

I expect it to print `pubrel (v5)` but instead it gets just

```
publish test test 2
< pubrec (v5)
<   packet_id:1
<   reason_code:success
<   props:
< pubcomp (v5)
<   packet_id:1
<   reason_code:success
<   props:
```

The topic is still updated on the server, just does not appear to call the callback.

cmake options
```
SET (MQTT_USE_STATIC_BOOST TRUE)
SET (MQTT_STD_VARIANT TRUE)
SET (MQTT_STD_OPTIONAL TRUE)
SET (MQTT_STD_STRING_VIEW TRUE)
SET (MQTT_STD_ANY TRUE)
SET (MQTT_STD_SHARED_PTR_ARRAY TRUE)
SET (MQTT_USE_TLS TRUE)
```

using commit: 5726b50c071093d1e22c506b4cb4fdf1171977af
mqtt server running docker image eclipse-mosquitto:2.0.14, configured for tls

cmd line args
```
--host=127.0.0.1
--port=8883
--username=mqtt
--password=mqtt
--verify_file=ca.crt
--protocol=mqtts
--cfg=none
```

Any help is appreciated.

**Comment by pauljohnston2009** [comment]
On a second look at the mqtt spec it appears the client only sends PUBREL, and never receives it. So the responses I'm getting would appear correct. https://docs.oasis-open.org/mqtt/mqtt/v5.0/os/mqtt-v5.0-os.html#_Toc385349369

Is there a reason the set_pubrel_handler and set_v5_pubrel_handler are included in the client example? It would appear they are server only handlers.

Is there an easy way to determine that the handlers are 'server only' or 'client only'.  The callable_overlay struct appears to be used for both server and client.

**Comment by redboltz** [comment]
Publish is initiated by not only client but also broker.

QoS2 publish sequence

```
Initiated by client

client            broker
  |                 |
  | publish         |
  |---------------->|
  |                 |
  | pubrec          |
  |<----------------|
  |                 |
  | pubrel          |
  |---------------->|
  |                 |
  | pubcomp         |
  |<----------------|


Initiated by broker

client            broker
  |                 |
  | publish         |
  |<----------------|
  |                 |
  | pubrec          |
  |---------------->|
  |                 |
  | pubrel          |
  |<----------------|
  |                 |
  | pubcomp         |
  |---------------->|
```

When client receives pubrel, then the handler is called.

> Is there an easy way to determine that the handlers are 'server only' or 'client only'? The callable_overlay struct appears to be used for both server and client.

No, you need to read the spec. Check the sender, then the receiver is a counter part.

Quick note:

- Send by only client (server would receive via the handler)
   - CONNECT
   - SUBSCRIBE
   - UNSUBSCRIBE
   - PINGREQ
- Send by only server (client would receive via the handler)
   - CONNACK
   - SUBACK
   - UNSUBACK
   - PINGRESP
- Both
   -  PUBLISH
   - PUBACK
   - PUBREC
   - PUBREL
   - PUBCOMP
   - AUTH
   - DISCONNECT

**Comment by pauljohnston2009** [comment]
Thank you, that cleared up a lot of my confusion.
