### ISSUE TITLE
send_connack ends in assertion.

### ISSUE THREAD

**Issue by siemeT** [redboltz/mqtt_cpp#965]
I'm connecting to mqtt_cpp from an (older) mosquitto client. 

The code ends up in an assertion when calling connack on the endpoint (unrecognized protocol version). 

Shouldn't the stack be robust to this, even if the mosquitto client somehow sets something inappropriate for the protocol version? 

https://github.com/redboltz/mqtt_cpp/blob/3b1dfe2392a3eaad94ca6520d1746323fdf4ee68/include/mqtt/endpoint.hpp#L9625

**Comment by redboltz** [comment]
Thank you for reporting the issue.
I need more information. Could you post the backtrace of assertion failed case?
I need to know who call it.

**Comment by redboltz** [comment]
I found invalid `async_send_connack()` call in broker.hpp.
I will fix it.

https://github.com/redboltz/mqtt_cpp/blob/3b1dfe2392a3eaad94ca6520d1746323fdf4ee68/include/mqtt/broker/broker.hpp#L163-L192

It is weied that the issue is `async_send_connack()` call but not `send_connack()` call.

**Comment by redboltz** [comment]
I noticed that the fix isn't needed:

The protocol_version is checked correctly.

https://github.com/redboltz/mqtt_cpp/blob/3b1dfe2392a3eaad94ca6520d1746323fdf4ee68/include/mqtt/broker/broker.hpp#L196-L221

**Comment by siemeT** [comment]
Thank you for the thorough investigation, much appreciated. 

The connack is send from the on_connect() handler. 

I can't share the stack with you because of company confidentiality.

I'm still debugging the issue but it might be stack corruption. 

I'll let you know if it is anything you have to deal with.

**Comment by siemeT** [comment]
I can confirm that the root cause is memory corruption that has nothing to do with the mqtt cpp stack.

You can close the issue. 

Great work by the way and have a nice weekend.
