### ISSUE TITLE
Gtest mqtt_cpp/include/mqtt/server.hpp

### ISSUE THREAD

**Issue by mohanict** [redboltz/mqtt_cpp#967]
Hi,

In my header file, class has below variable.
class Test{
MQTT_NS::server<> mServer;
};

In cpp file, mServer would be used to perform certain operations. During unit testing with Gtest, I don't want to test server, instead I want to mock it

Is there any reference Gtest code to mock MQTT_NS::server<> ?

**Comment by redboltz** [comment]
No, there is no gtest related code and examples in mqtt_cpp.
