### ISSUE TITLE
Possible memory leaks

### ISSUE THREAD

**Issue by chrisg89** [redboltz/mqtt_cpp#968]
Hello mqtt_cpp team,

I believe I may have found an issue in the library. I’m not sure if the observed behavior is an issue or intentional by design. I will break down the problem into three pieces:

1. Explain the scenario
2. Explain how my application uses the `mqtt_cpp` library
3. Explain the problem in `mqtt_cpp` under the aforementioned scenario + use-case

## 1. The scenario:

Setup:
- 1 Broker
- ClientA
- ClientB

The following sequence of events take place:
1. clientA and clientB have established a connection to a MQTT broker.
2. ClientA subscribed to topic "X" using QOS1.
3. ClientB published a message to topic "X" using QOS1.
4. Broker received PUBLISH from ClientB.
5. Broker will PUBLISH the message on topic "X" to clientA using QOS1
6. ClientA will receive the message
7. ClientA will respond with a PUBACK

## 2. The application use-case

This is how my application uses the `mqtt_cpp` library:

1. The `async_client` is used.
2. The main thread of the application creates the `IoContext` and runs it in another thread. This `IoContext` services the `async_client`
3. The application can forcefully stop the `IoContext` at any time (i.e. call to `io.stop()`), terminate the thread, and destroy the `IoContext`

## 3. The problem

Assume that `mqtt_cpp` just received the PUBLISH message on topic "X" as described in the scenario. 

The client will call `async_send_puback` which will call `do_async_write(...)` and pass to it the following completion handler:

```
            do_async_write(
                force_move(msg),
                [this, self = this->shared_from_this(), packet_id, func = force_move(func)]
                (error_code ec) {
                    if (func) func(ec);
                    on_pub_res_sent(packet_id);
                }
```
Notice the capture of `shared_from_this()`.

let's look into `do_async_write(...)`. We observe that the request is added to the the `queue_`:
```
                if (can_send()) {
                    queue_.emplace_back(force_move(mv), force_move(func));
                    // Only need to start async writes if there was nothing in the queue before the above item.
                    if (queue_.size() > 1) return;
                    do_async_write();
                }
```
Notice that the completion handler (with capture of `shared_from_this()`) is also added to the `queue_`. Next, let's assume that the application will forcefully stop the `IoContext` BEFORE `queue_` is emptied.

At this moment in time, we have a circular dependency:

The client contains a `queue_`
The `queue_` contains the request to send the puback
The request contains the completion token
The completion token contains the shared_from_this() to the client

Since the `IoContext` was stopped by the main thread, the `IoContext` can not service any more async operations. The `queue_` will not be emptied which means the client can not be destroyed (circular dependency). When the application exits, it will exit with an open file descriptor and memory leaks. Tools like `valgrind` confirm the presence of open file descriptors and memory leaks upon termination of the application.

There are other scenarios where a similar issue can occur. Anytime the `queue_` contains a completion handler with captured `shared_from_this()` the circular dependency arises. If the `IoContext` is stopped at this moment in time, memory leaks will follow. 

# 4. Possible work around
One solution we came up with is to not forcefully stop the `IoContext`. Instead, the application MUST call `async_disconnect` and wait for the client to close ( the client empties the queue in this case breaking the circular dependency). Once this is finished, the `IoContext` will break out of `run()` as there is no more work to be done. The application can now close without any leaks.

# 5. Questions
1. Is this behavior by design or is this a bug in the library?
2. Should the user be allowed to stop the `IoContext` at any time or is this a misuse of the library?

Thank you for your time!

**Comment by redboltz** [comment]
> 1. Is this behavior by design or is this a bug in the library?

It is by design.

> 2. Should the user be allowed to stop the IoContext at any time or is this a misuse of the library?

stop() would prevent clean shutdown, so it is misuse of the library.

The correct way to forcefully shutdown is `async_force_disconnect()`. 
https://github.com/redboltz/mqtt_cpp/blob/6b243717fedac09cfc1b37d741b4a573fe11d8cf/include/mqtt/endpoint.hpp#L2278-L2287

If the socket is not closed by the broker side due to broker freeze, the socket is closed immediately from the client side. It helps the shutdown triggered by your application.

**Comment by chrisg89** [comment]
Thanks for the confirmation. Closing the issue.
