### ISSUE TITLE
use preexisting open socket file descriptor

### ISSUE THREAD

**Issue by siemeT** [redboltz/mqtt_cpp#969]
Hi,

I have a use case where I am required to use an already open socket descriptor to start an mqtt connection with.

I was able to make this work doing the below. But I would rather not have to patch the stack every time.

Could support for this use case be added to the stack in a cleaner way and as part of the repo?

**auto ep = std::make_shared<MQTT_NS::tcp_endpoint<as::ip::tcp::socket, MQTT_NS::strand>>(mIoc);
ep->lowest_layer().assign(boost::asio::ip::tcp::v6(), socketFileDescriptor);
client->async_connect(std::move(ep), [&](MQTT_NS::error_code ec) {});**

void async_connect_impl(
        v5::properties props,
        any session_life_keeper,
        async_handler_t func) {
        auto r = std::make_shared<as::ip::tcp::resolver>(ioc_);
        auto p = r.get();
        p->async_resolve(
            host_,
            port_,
            [
                this,
                self = this->shared_from_this(),
                props = force_move(props),
                session_life_keeper = force_move(session_life_keeper),
                func = force_move(func),
                r = force_move(r)
            ]
            (
                error_code ec,
                as::ip::tcp::resolver::results_type eps
            ) mutable {
                if (ec) {
                    if (func) func(ec);
                    return;
                }
**#if 0**
                as::async_connect(
                    socket_->lowest_layer(), eps.begin(), eps.end(),
                    [
                        this,
                        self = force_move(self),
                        props = force_move(props),
                        session_life_keeper = force_move(session_life_keeper),
                        func = force_move(func)
                    ]
                    (error_code ec, auto /* unused */) mutable {
                        if (ec) {
                            if (func) func(ec);
                            return;
                        }
                        base::set_connect();
                        if (ping_duration_ != std::chrono::steady_clock::duration::zero()) {
                            set_timer();
                        }
                        async_handshake_socket(*socket_, force_move(props), force_move(session_life_keeper), force_move(func));
                    }
                );
**#endif**
                ** base::set_connect();
                if (ping_duration_ != std::chrono::steady_clock::duration::zero()) {
                   set_timer();
                }
                async_handshake_socket(*socket_, force_move(props), force_move(session_life_keeper), force_move(func)); **
            }
        );
    }

**Comment by redboltz** [comment]
Could you try #970 ?

**Comment by siemeT** [comment]
It seems to behave the same as my crude hack. 

Great work, thanks man.

**Comment by redboltz** [comment]
merged.

**Comment by siemeT** [comment]
Will there be a release version for this? 

(I need to request to pull this in via corporate channels).
