### ISSUE TITLE
CMake error on INSTALL(EXPORT ...) when adding the mqtt_cpp package with CPM.cmake

### ISSUE THREAD

**Issue by lproj** [redboltz/mqtt_cpp#989]
Hi,

I've already opened a ticket on CPM.cmake regarding the issue below. Feel free to close this issue one if you think it is better to answer there.

With regard to the boost example in the CPM.cmake repository, I am trying to add a package right after the CPMAddPackage(NAME Boost ...) line:

set(MQTT_BUILD_EXAMPLES OFF CACHE BOOL "build mqtt_cpp examples" FORCE)
set(MQTT_BUILD_TESTS OFF CACHE BOOL "build mqtt_cpp tests" FORCE)
cpmaddpackage("gh:redboltz/mqtt_cpp#master")

However, I get this error when trying to build the project with cmake (from Ubuntu 22.04):

-- Configuring done
CMake Error: install(EXPORT "mqtt_cpp_ifaceTargets" ...) includes target "mqtt_cpp_iface" which requires target "boost_system" that is not in any export set.
CMake Error: install(EXPORT "mqtt_cpp_ifaceTargets" ...) includes target "mqtt_cpp_iface" which requires target "boost_date_time" that is not in any export set.

Do you know why this happens? It seems to me that the Boost targets do not get exported for some reasons.

Thanks in advance.

**Comment by redboltz** [comment]
I'm not sure why it happens but #990 would solve the issue. Please try it.
Boost.System was a normal library but now it is a header-only library. I'm not sure Boost.DataTime is the same situation.
But accoding to your log, only they output the error.

**Comment by redboltz** [comment]
Unfortunately, CI failed. In order to merge #990, CI should be passed.
https://github.com/redboltz/mqtt_cpp/actions/runs/6850513492/job/18624825988?pr=990

I have no time to solve it serveral weeks, sorry.
If someone fix the CI issue, please create the PR based on `fix_989` branch.

**Comment by redboltz** [comment]
I got a time by chance, so I have fixed the CI issue.

**Comment by lproj** [comment]
Thanks for you help and keep up the good work!
