### ISSUE TITLE
No callback when internet connection is turned off

### ISSUE THREAD

**Issue by kuzenko** [redboltz/mqtt_cpp#991]
Dear @faithandbrave, I have found an issue that nothing is called for me when I turned wifi off.
I tried all the handlers: close_handler, disconnect_handler, error_handler, but nothing is called.
Please advice where I would be able to detect when we were disconnected from broker, 
when internet connection was shutdown and socket connection was closed.
Thanks in advance

**Comment by redboltz** [comment]
- Before MQTT connection is established
   -  See #984. If you asyn `async_*` APIs, then you can set your own timeout using something like `as::steady_timer`. If you use sync APIs. there is no way to detect timeout.
- After MQTT connection is established
  - You can use 
     https://github.com/redboltz/mqtt_cpp/blob/ac2d324c59c628513959079805f785136e26c7ca/include/mqtt/endpoint.hpp#L4976-L4988
    to check  broker's response. In order to use the function, you need to pass `keep_alive_sec` > 0 to `connect()` or `async_connect()` funtion.

**Comment by kuzenko** [comment]
Thanks for quick response, I will try.

**Comment by redboltz** [comment]
NOTE:
endpoint/client configuration funtions like set_pingresp_timeout() should be called before connect()/async_connect() is called.
I worte "After MQTT connection is established", it doesn't mean set_pingresp_timeout() should be called after the connection established. It measn set_pingresp_timeout() can detect disconnection after the connection is established.

**Comment by kuzenko** [comment]
Dear @redboltz, I think I have found a bug, sometimes an error comes to error_handler when I am turning wifi off, but sometimes it doesn't. I am using it to reschedule the timer. Please advice how to resolve such situation. Here is my code:

`int main(int argc, char** argv) {
    const std::string host = "broker.hivemq.com";
    const std::string port = "1883";

    MQTT_NS::setup_log();

    boost::asio::io_context ioc;

    // Create no TLS client
    auto c = MQTT_NS::make_async_client( ioc, host, port );

    // Setup client
    c->set_client_id( "cid1" );
    c->set_clean_session( true );

    c->set_keep_alive_sec( std::numeric_limits<uint16_t>::max() );
    std::chrono::steady_clock::duration pingrespDuration( 6 );
    c->set_pingresp_timeout( pingrespDuration );

    boost::asio::steady_timer tim_connect_wait_limit( ioc );
    boost::asio::steady_timer tim_reconnect_delay( ioc );

    std::function<void()> connect;
    std::function<void()> reconnect;

    connect =
            [&] {
                std::cout << "async_connect" << std::endl;
                c->async_connect(
                        [&]
                                (MQTT_NS::error_code ec){
                            std::cout << "async_connect callback error message: " << ec.message() << std::endl;
                            if ( ec ) {
                                std::cout << "Trying to reconnect again..." << std::endl;
                                reconnect();
                            } else {
                                std::cout << "Sending publish test..." << std::endl;
                                c->async_publish("mqtt_client_cpp/topic2_1", "test2_1", MQTT_NS::qos::at_least_once);
                            }
                        }
                );

                //std::cout << "tim_connect_wait_limit set" << std::endl;
                tim_connect_wait_limit.expires_after(std::chrono::seconds(3));
                tim_connect_wait_limit.async_wait(
                        [&](boost::system::error_code ec) {
                            if (ec) {
                                std::cout << "tim_connect_wait_limit callback: " << ec.message() << std::endl;
                            }

                            /*if (!ec) {
                                c->async_force_disconnect(
                                        [&](boost::system::error_code ec) {
                                            std::cout << "async_force_disconnect callback: " << ec.message() << std::endl;
                                        }
                                );
                            }*/
                        }
                );
            };
    reconnect =
            [&] {
                std::cout << "Trying to reconnect..." << std::endl;
                tim_reconnect_delay.expires_after( std::chrono::seconds( 6 ) );
                tim_reconnect_delay.async_wait(
                        [&]( boost::system::error_code ec ) {
                            std::cout << "async_wait callback with error: " << ec.message() << std::endl;
                            if ( !ec ) {
                                std::cout << "Trying to connect..." << std::endl;
                                connect();
                            }
                        }
                );
            };

    // Setup handlers
    c->set_connack_handler(
            [&](bool sp, MQTT_NS::connect_return_code connack_return_code){
                std::cout << "Connack handler called" << std::endl;
                std::cout << "  Session Present: " << std::boolalpha << sp << std::endl;
                std::cout << "  Connack Return Code: "
                          << MQTT_NS::connect_return_code_to_str(connack_return_code) << std::endl;
                if ( connack_return_code == MQTT_NS::connect_return_code::accepted ) {
                    tim_connect_wait_limit.cancel();
                }
                else {
                    reconnect();
                }
                return true;
            });
    c->set_close_handler(
            [&]
                    (){
                std::cout << "closed." << std::endl;
                //reconnect();
            });
    c->set_error_handler(
            [&]
                    (MQTT_NS::error_code ec){
                std::cout << "error: " << ec.message() << std::endl;
                reconnect();
            });

    c->set_disconnect_handler([]
                    (){
                std::cout << "[server] disconnect received." << std::endl;
            });

    connect();
    ioc.run();
}`

**Comment by kuzenko** [comment]
I have an internet checker in my application, but some callbacks should be called when we lose connection, right? 
Maybe connected() method of a client returns correct state, I have not checked that yet.

**Comment by redboltz** [comment]
See https://docs.oasis-open.org/mqtt/mqtt/v5.0/os/mqtt-v5.0-os.html#_Keep_Alive_1

It seems that 

```cpp
    c->set_keep_alive_sec( std::numeric_limits<uint16_t>::max() );
```

is too long so no PINGREQ packet would be sent. For example try `c->set_keep_alive_sec(30);`.

**Comment by kuzenko** [comment]
> See https://docs.oasis-open.org/mqtt/mqtt/v5.0/os/mqtt-v5.0-os.html#_Keep_Alive_1
> 
> It seems that
> 
> ```c++
>     c->set_keep_alive_sec( std::numeric_limits<uint16_t>::max() );
> ```
> 
> is too long so no PINGREQ packet would be sent. For example try `c->set_keep_alive_sec(30);`.

But if I do that, we will be disconnected from broker, after 30 seconds, no? I just need to have stable connection to broker.

**Comment by redboltz** [comment]
> I have an internet checker in my application, but some callbacks should be called when we lose connection, right? Maybe connected() method of a client returns correct state, I have not checked that yet. The first scenario (Before MQTT connection is established) works for me as far as I see pretty stable.

It depends on your environment. For example, enabling TCP heartbeat is optional. If it is not set, and simply unplug socket, there is no way to detect disconnection. It is TCP spec.

**Comment by redboltz** [comment]
> > See https://docs.oasis-open.org/mqtt/mqtt/v5.0/os/mqtt-v5.0-os.html#_Keep_Alive_1
> > It seems that
> > ```c++
> >     c->set_keep_alive_sec( std::numeric_limits<uint16_t>::max() );
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > is too long so no PINGREQ packet would be sent. For example try `c->set_keep_alive_sec(30);`.
> 
> But if I do that, we will be disconnected from broker, after 30 seconds, no? I just need to have stable connection to broker.

Read link. I am not your teacher.

**Comment by kuzenko** [comment]
> > I have an internet checker in my application, but some callbacks should be called when we lose connection, right? Maybe connected() method of a client returns correct state, I have not checked that yet. The first scenario (Before MQTT connection is established) works for me as far as I see pretty stable.
> 
> It depends on your environment. For example, enabling TCP heartbeat is optional. If it is not set, and simply unplug socket, there is no way to detect disconnection. It is TCP spec.

I see, thanks
