### ISSUE TITLE
Sporadic Segmentation fault on disconnect

### ISSUE THREAD

**Issue by ahmedwahdan** [redboltz/mqtt_cpp#992]
A sporadic Segmentation fault occurs most probably when disconnecting and resetting the client object while the on_ping request is called.

MQTT CPP version: 13.2.0
Implementation:
- async_disconnect
- client->reset();
- 
![mqtt_sig2](https://github.com/redboltz/mqtt_cpp/assets/5406736/ff2f6501-098b-4c01-89d5-36da580e6379)
![image](https://github.com/redboltz/mqtt_cpp/assets/5406736/186731e1-dd04-49aa-b973-9d07baefafb3)
![mqtt_sig](https://github.com/redboltz/mqtt_cpp/assets/5406736/aa3435ac-11e6-42a6-b3a2-ebf70148ddfa)
![image](https://github.com/redboltz/mqtt_cpp/assets/5406736/41e56344-2406-4e27-9809-f9c53f7b31d8)

In another crash the error code was 127
ec = {val_ = 1534805528, failed_ = 127, cat_ = 0x7f5b7b4648}

**Comment by redboltz** [comment]
Thank you for reporting the issue.
Please create https://stackoverflow.com/help/minimal-reproducible-example 
It is required in order to analyse the issue.

**Comment by ahmedwahdan** [comment]
This was due application race condition, closing the issue
