### ISSUE TITLE
Problem with connection to AWS IoT Broker with TLS with ALPN

### ISSUE THREAD

**Issue by rkalicinski** [redboltz/mqtt_cpp#996]
I tried to connect to AWS IoT Broker using mqtt_cpp. AWS requires ALPN to be configured on TLS but mqtt_cpp does not support it directly so I needed to use native OpenSSL function to set it up:
```   boost::asio::io_context ioc;
    auto c = MQTT_NS::make_tls_sync_client(ioc, "{AWS host}", 443); 
    static const unsigned char protos[5] = {4, 'm','q','t','t'};
    auto res = SSL_CTX_set_alpn_protos(c->get_ssl_context().native_handle(), protos, 5);
    c->connect();
```
Unfortunately connection does not succeed and end up with "End of file".
What could be missing here?
Additionally, I'm limited to C++14 so cannot use asyc_mqtt instead.

**Comment by rkalicinski** [comment]
@redboltz Thank you for Your kind asist. I confirm that Your hint helped and now connection works like a charm :)

**Comment by redboltz** [comment]
@rkalicinski  you are welcome :)
